// vocab-es.js
// Spanish <-> English vocabulary for Espanyao 🐱
// Format: { id, es, en, pos, sample }
// - es: base form (no article for nouns)
// - en: English meaning
// - pos: part of speech with gender info for nouns, e.g., "noun(f)", "noun(m)"
// - sample: short example sentence in simple Spanish

const VOCAB_ES = [
  { id: 1, es: "ser", en: "to be", pos: "verb", sample: "Quiero ser una buena persona." },
  { id: 2, es: "estar", en: "to be (state)", pos: "verb", sample: "Estoy muy cansado hoy." },
  { id: 3, es: "tener", en: "to have", pos: "verb", sample: "Tengo dos hermanos." },
  { id: 4, es: "hacer", en: "to do; to make", pos: "verb", sample: "Tengo que hacer la tarea." },
  { id: 5, es: "poder", en: "can; to be able to", pos: "verb", sample: "No puedo dormir bien." },
  { id: 6, es: "ir", en: "to go", pos: "verb", sample: "Voy al trabajo en metro." },
  { id: 7, es: "decir", en: "to say; to tell", pos: "verb", sample: "Siempre digo la verdad." },
  { id: 8, es: "ver", en: "to see", pos: "verb", sample: "Quiero ver esa película." },
  { id: 9, es: "dar", en: "to give", pos: "verb", sample: "Te voy a dar un regalo." },
  { id: 10, es: "saber", en: "to know (facts)", pos: "verb", sample: "No sé la respuesta." },
  { id: 11, es: "querer", en: "to want; to love", pos: "verb", sample: "Quiero aprender español." },
  { id: 12, es: "llegar", en: "to arrive", pos: "verb", sample: "Llego tarde a clase." },
  { id: 13, es: "pasar", en: "to happen; to pass", pos: "verb", sample: "¿Qué pasa aquí?" },
  { id: 14, es: "deber", en: "must; should", pos: "verb", sample: "Debo estudiar más." },
  { id: 15, es: "poner", en: "to put", pos: "verb", sample: "Pongo el libro en la mesa." },
  { id: 16, es: "parecer", en: "to seem", pos: "verb", sample: "Parece una buena idea." },
  { id: 17, es: "quedar", en: "to stay; to remain", pos: "verb", sample: "Me quedo en casa hoy." },
  { id: 18, es: "creer", en: "to believe", pos: "verb", sample: "Creo en ti." },
  { id: 19, es: "hablar", en: "to speak; to talk", pos: "verb", sample: "Hablo español con mis amigos." },
  { id: 20, es: "llevar", en: "to carry; to wear", pos: "verb", sample: "Llevo una chaqueta roja." },

  { id: 21, es: "dejar", en: "to leave; to let", pos: "verb", sample: "Dejo el bolso en la silla." },
  { id: 22, es: "seguir", en: "to follow; to continue", pos: "verb", sample: "Sigue las instrucciones." },
  { id: 23, es: "encontrar", en: "to find", pos: "verb", sample: "No puedo encontrar mi teléfono." },
  { id: 24, es: "llamar", en: "to call", pos: "verb", sample: "Te llamo mañana." },
  { id: 25, es: "venir", en: "to come", pos: "verb", sample: "¿Puedes venir a mi casa?" },
  { id: 26, es: "pensar", en: "to think", pos: "verb", sample: "Pienso mucho en el futuro." },
  { id: 27, es: "salir", en: "to go out; to leave", pos: "verb", sample: "Salgo con mis amigos el sábado." },
  { id: 28, es: "volver", en: "to return; to come back", pos: "verb", sample: "Vuelvo a casa tarde." },
  { id: 29, es: "tomar", en: "to take; to drink", pos: "verb", sample: "Tomo café por la mañana." },
  { id: 30, es: "conocer", en: "to know; to meet", pos: "verb", sample: "Quiero conocer nuevas personas." },
  { id: 31, es: "vivir", en: "to live", pos: "verb", sample: "Vivo en una ciudad grande." },
  { id: 32, es: "sentir", en: "to feel", pos: "verb", sample: "Siento un poco de frío." },
  { id: 33, es: "tratar", en: "to try; to treat", pos: "verb", sample: "Trato de aprender cada día." },
  { id: 34, es: "mirar", en: "to look at", pos: "verb", sample: "Miro el cielo por la noche." },
  { id: 35, es: "contar", en: "to count; to tell", pos: "verb", sample: "Mi abuelo cuenta historias." },
  { id: 36, es: "empezar", en: "to start; to begin", pos: "verb", sample: "La clase empieza a las nueve." },
  { id: 37, es: "esperar", en: "to wait; to hope", pos: "verb", sample: "Espero el autobús." },
  { id: 38, es: "buscar", en: "to look for; to search", pos: "verb", sample: "Busco un buen restaurante." },
  { id: 39, es: "trabajar", en: "to work", pos: "verb", sample: "Trabajo en una oficina." },
  { id: 40, es: "estudiar", en: "to study", pos: "verb", sample: "Estudio español todos los días." },

  { id: 41, es: "comer", en: "to eat", pos: "verb", sample: "Comemos juntos los domingos." },
  { id: 42, es: "beber", en: "to drink", pos: "verb", sample: "Bebo mucha agua." },
  { id: 43, es: "jugar", en: "to play (games, sports)", pos: "verb", sample: "Juego al fútbol con mis amigos." },
  { id: 44, es: "dormir", en: "to sleep", pos: "verb", sample: "Duermo ocho horas cada noche." },
  { id: 45, es: "abrir", en: "to open", pos: "verb", sample: "Abro la ventana porque hace calor." },
  { id: 46, es: "cerrar", en: "to close", pos: "verb", sample: "Cierro la puerta lentamente." },
  { id: 47, es: "leer", en: "to read", pos: "verb", sample: "Leo un libro interesante." },
  { id: 48, es: "escribir", en: "to write", pos: "verb", sample: "Escribo un correo a mi profesor." },
  { id: 49, es: "correr", en: "to run", pos: "verb", sample: "Corro en el parque por la mañana." },
  { id: 50, es: "caminar", en: "to walk", pos: "verb", sample: "Camino a casa después de clase." },

  { id: 51, es: "casa", en: "house; home", pos: "noun(f)", sample: "Mi casa es pequeña pero cómoda." },
  { id: 52, es: "libro", en: "book", pos: "noun(m)", sample: "Tengo un libro de gramática." },
  { id: 53, es: "mesa", en: "table", pos: "noun(f)", sample: "Pon el vaso en la mesa." },
  { id: 54, es: "silla", en: "chair", pos: "noun(f)", sample: "Necesito otra silla." },
  { id: 55, es: "amigo", en: "friend (male)", pos: "noun(m)", sample: "Mi mejor amigo vive lejos." },
  { id: 56, es: "amiga", en: "friend (female)", pos: "noun(f)", sample: "Mi amiga estudia medicina." },
  { id: 57, es: "familia", en: "family", pos: "noun(f)", sample: "Paso tiempo con mi familia los fines de semana." },
  { id: 58, es: "escuela", en: "school", pos: "noun(f)", sample: "La escuela está cerca de mi casa." },
  { id: 59, es: "trabajo", en: "work; job", pos: "noun(m)", sample: "Busco un trabajo a tiempo parcial." },
  { id: 60, es: "ciudad", en: "city", pos: "noun(f)", sample: "Barcelona es una ciudad bonita." },

  { id: 61, es: "pueblo", en: "town; village", pos: "noun(m)", sample: "Mi abuela vive en un pueblo pequeño." },
  { id: 62, es: "calle", en: "street", pos: "noun(f)", sample: "La calle está muy tranquila." },
  { id: 63, es: "agua", en: "water", pos: "noun(f)", sample: "Bebo agua todos los días." },
  { id: 64, es: "comida", en: "food; meal", pos: "noun(f)", sample: "La comida está muy rica." },
  { id: 65, es: "tiempo", en: "time; weather", pos: "noun(m)", sample: "No tengo tiempo para salir." },
  { id: 66, es: "día", en: "day", pos: "noun(m)", sample: "Hoy es un buen día." },
  { id: 67, es: "noche", en: "night", pos: "noun(f)", sample: "Me gusta la ciudad por la noche." },
  { id: 68, es: "mano", en: "hand", pos: "noun(f)", sample: "Levanta la mano, por favor." },
  { id: 69, es: "cara", en: "face", pos: "noun(f)", sample: "Tiene una cara muy simpática." },
  { id: 70, es: "niño", en: "boy; child", pos: "noun(m)", sample: "El niño juega en el parque." },

  { id: 71, es: "niña", en: "girl; child", pos: "noun(f)", sample: "La niña canta una canción." },
  { id: 72, es: "padre", en: "father", pos: "noun(m)", sample: "Mi padre trabaja mucho." },
  { id: 73, es: "madre", en: "mother", pos: "noun(f)", sample: "Mi madre cocina muy bien." },
  { id: 74, es: "hermano", en: "brother", pos: "noun(m)", sample: "Tengo un hermano mayor." },
  { id: 75, es: "hermana", en: "sister", pos: "noun(f)", sample: "Mi hermana estudia en la universidad." },
  { id: 76, es: "perro", en: "dog", pos: "noun(m)", sample: "El perro corre en el jardín." },
  { id: 77, es: "gato", en: "cat", pos: "noun(m)", sample: "El gato duerme en el sofá." },
  { id: 78, es: "coche", en: "car", pos: "noun(m)", sample: "Compro un coche nuevo." },
  { id: 79, es: "autobús", en: "bus", pos: "noun(m)", sample: "Voy en autobús a la escuela." },
  { id: 80, es: "tren", en: "train", pos: "noun(m)", sample: "El tren llega a las ocho." },

  { id: 81, es: "dinero", en: "money", pos: "noun(m)", sample: "No tengo mucho dinero." },
  { id: 82, es: "país", en: "country", pos: "noun(m)", sample: "España es un país europeo." },
  { id: 83, es: "mundo", en: "world", pos: "noun(m)", sample: "El mundo es muy grande." },
  { id: 84, es: "problema", en: "problem", pos: "noun(m)", sample: "Tengo un problema con el ordenador." },
  { id: 85, es: "pregunta", en: "question", pos: "noun(f)", sample: "Tengo una pregunta importante." },
  { id: 86, es: "respuesta", en: "answer", pos: "noun(f)", sample: "La respuesta es correcta." },
  { id: 87, es: "clase", en: "class; lesson", pos: "noun(f)", sample: "La clase empieza a las diez." },
  { id: 88, es: "lengua", en: "language; tongue", pos: "noun(f)", sample: "El español es una lengua bonita." },
  { id: 89, es: "palabra", en: "word", pos: "noun(f)", sample: "No conozco esta palabra." },
  { id: 90, es: "número", en: "number", pos: "noun(m)", sample: "Escribe tu número de teléfono." },

  { id: 91, es: "música", en: "music", pos: "noun(f)", sample: "Escucho música todos los días." },
  { id: 92, es: "película", en: "movie; film", pos: "noun(f)", sample: "Vemos una película en casa." },
  { id: 93, es: "foto", en: "photo", pos: "noun(f)", sample: "Mira esta foto de mi viaje." },
  { id: 94, es: "historia", en: "story; history", pos: "noun(f)", sample: "Me gusta la historia de este país." },
  { id: 95, es: "juego", en: "game", pos: "noun(m)", sample: "Este juego es muy divertido." },
  { id: 96, es: "computadora", en: "computer (LatAm)", pos: "noun(f)", sample: "Trabajo mucho con la computadora." },
  { id: 97, es: "ordenador", en: "computer (Spain)", pos: "noun(m)", sample: "Mi ordenador es muy rápido." },
  { id: 98, es: "teléfono", en: "telephone; phone", pos: "noun(m)", sample: "Mi teléfono está en la mesa." },
  { id: 99, es: "llave", en: "key", pos: "noun(f)", sample: "No encuentro la llave de la puerta." },
  { id: 100, es: "puerta", en: "door", pos: "noun(f)", sample: "Cierra la puerta, por favor." },

  { id: 101, es: "ventana", en: "window", pos: "noun(f)", sample: "Abro la ventana para ver el cielo." },
  { id: 102, es: "cama", en: "bed", pos: "noun(f)", sample: "La cama es muy cómoda." },
  { id: 103, es: "ropa", en: "clothes", pos: "noun(f)", sample: "Lavo la ropa el domingo." },
  { id: 104, es: "zapato", en: "shoe", pos: "noun(m)", sample: "Mis zapatos están sucios." },
  { id: 105, es: "camisa", en: "shirt", pos: "noun(f)", sample: "Llevo una camisa blanca." },
  { id: 106, es: "chaqueta", en: "jacket", pos: "noun(f)", sample: "Necesito una chaqueta en invierno." },
  { id: 107, es: "fruta", en: "fruit", pos: "noun(f)", sample: "Como fruta por la mañana." },
  { id: 108, es: "pan", en: "bread", pos: "noun(m)", sample: "Como pan con mantequilla." },
  { id: 109, es: "leche", en: "milk", pos: "noun(f)", sample: "Bebo leche fría." },
  { id: 110, es: "café", en: "coffee", pos: "noun(m)", sample: "El café está muy caliente." },

  { id: 111, es: "té", en: "tea", pos: "noun(m)", sample: "Prefiero té por la noche." },
  { id: 112, es: "cerveza", en: "beer", pos: "noun(f)", sample: "Bebe poca cerveza." },
  { id: 113, es: "vino", en: "wine", pos: "noun(m)", sample: "Tomamos vino en la cena." },
  { id: 114, es: "restaurante", en: "restaurant", pos: "noun(m)", sample: "El restaurante es muy famoso." },
  { id: 115, es: "tienda", en: "shop; store", pos: "noun(f)", sample: "La tienda cierra a las nueve." },
  { id: 116, es: "supermercado", en: "supermarket", pos: "noun(m)", sample: "Voy al supermercado cada semana." },
  { id: 117, es: "plaza", en: "square (city)", pos: "noun(f)", sample: "Nos vemos en la plaza central." },
  { id: 118, es: "parque", en: "park", pos: "noun(m)", sample: "Corremos en el parque." },
  { id: 119, es: "mar", en: "sea", pos: "noun(m)", sample: "Me gusta nadar en el mar." },
  { id: 120, es: "playa", en: "beach", pos: "noun(f)", sample: "La playa está llena de gente." },

  { id: 121, es: "bueno", en: "good", pos: "adj", sample: "Es un buen amigo." },
  { id: 122, es: "malo", en: "bad", pos: "adj", sample: "Es una mala idea." },
  { id: 123, es: "grande", en: "big; large", pos: "adj", sample: "La casa es muy grande." },
  { id: 124, es: "pequeño", en: "small; little", pos: "adj", sample: "Tengo un perro pequeño." },
  { id: 125, es: "nuevo", en: "new", pos: "adj", sample: "Este libro es nuevo." },
  { id: 126, es: "viejo", en: "old", pos: "adj", sample: "Mi coche es viejo." },
  { id: 127, es: "bonito", en: "pretty; nice", pos: "adj", sample: "El parque es muy bonito." },
  { id: 128, es: "feo", en: "ugly", pos: "adj", sample: "El edificio es un poco feo." },
  { id: 129, es: "fácil", en: "easy", pos: "adj", sample: "El ejercicio es fácil." },
  { id: 130, es: "difícil", en: "difficult", pos: "adj", sample: "Aprender una lengua es difícil." },

  { id: 131, es: "rápido", en: "fast; quick", pos: "adj", sample: "El tren es muy rápido." },
  { id: 132, es: "lento", en: "slow", pos: "adj", sample: "El ordenador es muy lento." },
  { id: 133, es: "feliz", en: "happy", pos: "adj", sample: "Estoy muy feliz hoy." },
  { id: 134, es: "triste", en: "sad", pos: "adj", sample: "Ella está triste esta semana." },
  { id: 135, es: "cansado", en: "tired", pos: "adj", sample: "Estoy cansado después del trabajo." },
  { id: 136, es: "contento", en: "glad; pleased", pos: "adj", sample: "Estoy contento con el resultado." },
  { id: 137, es: "frío", en: "cold", pos: "adj", sample: "Hace mucho frío en invierno." },
  { id: 138, es: "caliente", en: "hot; warm", pos: "adj", sample: "La sopa está muy caliente." },
  { id: 139, es: "lleno", en: "full", pos: "adj", sample: "El vaso está lleno de agua." },
  { id: 140, es: "vacío", en: "empty", pos: "adj", sample: "El autobús está casi vacío." },

  { id: 141, es: "aquí", en: "here", pos: "adv", sample: "Estoy aquí, en la entrada." },
  { id: 142, es: "allí", en: "there", pos: "adv", sample: "Mi amigo vive allí." },
  { id: 143, es: "hoy", en: "today", pos: "adv", sample: "Hoy no tengo clase." },
  { id: 144, es: "ayer", en: "yesterday", pos: "adv", sample: "Ayer fuimos al cine." },
  { id: 145, es: "mañana", en: "tomorrow", pos: "adv", sample: "Mañana tengo un examen." },
  { id: 146, es: "siempre", en: "always", pos: "adv", sample: "Siempre llego temprano." },
  { id: 147, es: "nunca", en: "never", pos: "adv", sample: "Nunca como muy tarde." },
  { id: 148, es: "a veces", en: "sometimes", pos: "adv", sample: "A veces estudio en la biblioteca." },
  { id: 149, es: "muy", en: "very", pos: "adv", sample: "Estoy muy ocupado." },
  { id: 150, es: "también", en: "also; too", pos: "adv", sample: "Yo también quiero ir." },

  { id: 151, es: "solo", en: "only; alone", pos: "adv/adj", sample: "Estoy solo en casa." },
  { id: 152, es: "ya", en: "already; now", pos: "adv", sample: "Ya he terminado la tarea." },
  { id: 153, es: "todavía", en: "still; yet", pos: "adv", sample: "Todavía no sé la respuesta." },
  { id: 154, es: "después", en: "afterwards; later", pos: "adv", sample: "Hablamos después de clase." },
  { id: 155, es: "antes", en: "before", pos: "adv", sample: "Desayuno antes de trabajar." },
  { id: 156, es: "luego", en: "then; later", pos: "adv", sample: "Primero estudio, luego juego." },
  { id: 157, es: "bien", en: "well", pos: "adv", sample: "Ella canta muy bien." },
  { id: 158, es: "mal", en: "badly", pos: "adv", sample: "Hoy me siento mal." },
  { id: 159, es: "mucho", en: "much; a lot", pos: "adv/det", sample: "Trabajo mucho durante la semana." },
  { id: 160, es: "poco", en: "little; few", pos: "adv/det", sample: "Tengo poco tiempo libre." },

  { id: 161, es: "yo", en: "I", pos: "pron", sample: "Yo estudio en la universidad." },
  { id: 162, es: "tú", en: "you (singular, informal)", pos: "pron", sample: "Tú hablas muy bien español." },
  { id: 163, es: "él", en: "he", pos: "pron", sample: "Él trabaja en un banco." },
  { id: 164, es: "ella", en: "she", pos: "pron", sample: "Ella vive en Madrid." },
  { id: 165, es: "nosotros", en: "we (masc./mixed)", pos: "pron", sample: "Nosotros estudiamos juntos." },
  { id: 166, es: "nosotras", en: "we (fem.)", pos: "pron", sample: "Nosotras somos amigas." },
  { id: 167, es: "ustedes", en: "you (plural)", pos: "pron", sample: "Ustedes hablan muy rápido." },
  { id: 168, es: "ellos", en: "they (masc./mixed)", pos: "pron", sample: "Ellos juegan al baloncesto." },
  { id: 169, es: "ellas", en: "they (fem.)", pos: "pron", sample: "Ellas trabajan en la misma oficina." },
  { id: 170, es: "gente", en: "people", pos: "noun(f)", sample: "Hay mucha gente en la calle." },

  { id: 171, es: "este", en: "this (masc.)", pos: "det", sample: "Este libro es interesante." },
  { id: 172, es: "esta", en: "this (fem.)", pos: "det", sample: "Esta casa es grande." },
  { id: 173, es: "ese", en: "that (masc.)", pos: "det", sample: "Quiero ese coche." },
  { id: 174, es: "esa", en: "that (fem.)", pos: "det", sample: "No me gusta esa idea." },
  { id: 175, es: "aquel", en: "that (over there, masc.)", pos: "det", sample: "¿Ves aquel edificio alto?" },
  { id: 176, es: "aquella", en: "that (over there, fem.)", pos: "det", sample: "Me gusta aquella montaña." },
  { id: 177, es: "muchos", en: "many (masc.)", pos: "det", sample: "Hay muchos estudiantes en la clase." },
  { id: 178, es: "muchas", en: "many (fem.)", pos: "det", sample: "Hay muchas preguntas en el examen." },
  { id: 179, es: "pocos", en: "few (masc.)", pos: "det", sample: "Quedan pocos asientos libres." },
  { id: 180, es: "pocas", en: "few (fem.)", pos: "det", sample: "Hay pocas tiendas abiertas hoy." },

  { id: 181, es: "porque", en: "because", pos: "conj", sample: "Llego tarde porque hay tráfico." },
  { id: 182, es: "pero", en: "but", pos: "conj", sample: "Quiero salir, pero estoy cansado." },
  { id: 183, es: "o", en: "or", pos: "conj", sample: "¿Café o té?" },
  { id: 184, es: "y", en: "and", pos: "conj", sample: "Pan y queso son una buena combinación." },
  { id: 185, es: "si", en: "if", pos: "conj", sample: "Si tienes tiempo, llámame." },
  { id: 186, es: "cuando", en: "when", pos: "conj", sample: "Te llamo cuando llegue a casa." },
  { id: 187, es: "dónde", en: "where", pos: "adv", sample: "¿Dónde está el baño?" },
  { id: 188, es: "cómo", en: "how", pos: "adv", sample: "¿Cómo estás hoy?" },
  { id: 189, es: "qué", en: "what", pos: "pron", sample: "¿Qué haces ahora?" },
  { id: 190, es: "quién", en: "who", pos: "pron", sample: "¿Quién es esa persona?" },

  { id: 191, es: "cuándo", en: "when", pos: "adv", sample: "¿Cuándo es el examen?" },
  { id: 192, es: "cuánto", en: "how much", pos: "adv/pron", sample: "¿Cuánto cuesta este libro?" },
  { id: 193, es: "dentro", en: "inside", pos: "adv", sample: "La llave está dentro de la bolsa." },
  { id: 194, es: "fuera", en: "outside", pos: "adv", sample: "Los niños juegan fuera de la casa." },
  { id: 195, es: "encima", en: "on top; above", pos: "adv", sample: "El gato está encima de la mesa." },
  { id: 196, es: "debajo", en: "under; below", pos: "adv", sample: "El perro duerme debajo de la cama." },
  { id: 197, es: "cerca", en: "near; close", pos: "adv", sample: "La estación está cerca de aquí." },
  { id: 198, es: "lejos", en: "far", pos: "adv", sample: "Mi casa está lejos del centro." },
  { id: 199, es: "siempre que", en: "whenever; as long as", pos: "conj", sample: "Puedes venir siempre que quieras." },
  { id: 200, es: "a menudo", en: "often", pos: "adv", sample: "Voy al gimnasio a menudo." },

  { id: 201, es: "alto", en: "tall; high", pos: "adj", sample: "El edificio es muy alto." },
  { id: 202, es: "bajo", en: "short; low", pos: "adj", sample: "El sonido está muy bajo." },
  { id: 203, es: "ancho", en: "wide", pos: "adj", sample: "La calle es muy ancha." },
  { id: 204, es: "estrecho", en: "narrow", pos: "adj", sample: "El pasillo es estrecho." },
  { id: 205, es: "joven", en: "young", pos: "adj", sample: "Ella es muy joven." },
  { id: 206, es: "mayor", en: "older", pos: "adj", sample: "Mi hermano es mayor que yo." },
  { id: 207, es: "menor", en: "younger", pos: "adj", sample: "Mi hermana es menor." },
  { id: 208, es: "calmo", en: "calm", pos: "adj", sample: "El mar está calmo hoy." },
  { id: 209, es: "ruidoso", en: "noisy", pos: "adj", sample: "El lugar es muy ruidoso." },
  { id: 210, es: "claro", en: "clear; light", pos: "adj", sample: "El cielo está claro." },
  { id: 211, es: "oscuro", en: "dark", pos: "adj", sample: "El cuarto está oscuro." },
  { id: 212, es: "caro", en: "expensive", pos: "adj", sample: "Ese reloj es muy caro." },
  { id: 213, es: "barato", en: "cheap", pos: "adj", sample: "El libro es barato." },
  { id: 214, es: "correcto", en: "correct", pos: "adj", sample: "Tu respuesta es correcta." },
  { id: 215, es: "incorrecto", en: "wrong", pos: "adj", sample: "Eso es incorrecto." },
  { id: 216, es: "aburrido", en: "boring", pos: "adj", sample: "La clase es aburrida." },
  { id: 217, es: "interesante", en: "interesting", pos: "adj", sample: "El libro es interesante." },
  { id: 218, es: "divertido", en: "fun", pos: "adj", sample: "El juego es muy divertido." },
  { id: 219, es: "tranquilo", en: "quiet", pos: "adj", sample: "El lugar es tranquilo." },
  { id: 220, es: "peligroso", en: "dangerous", pos: "adj", sample: "Es peligroso caminar solo." },

  { id: 221, es: "montaña", en: "mountain", pos: "noun(f)", sample: "La montaña es muy alta." },
  { id: 222, es: "río", en: "river", pos: "noun(m)", sample: "El río pasa por la ciudad." },
  { id: 223, es: "lago", en: "lake", pos: "noun(m)", sample: "El lago es hermoso." },
  { id: 224, es: "bosque", en: "forest", pos: "noun(m)", sample: "Caminamos por el bosque." },
  { id: 225, es: "flor", en: "flower", pos: "noun(f)", sample: "La flor es amarilla." },
  { id: 226, es: "árbol", en: "tree", pos: "noun(m)", sample: "El árbol es viejo." },
  { id: 227, es: "cielo", en: "sky", pos: "noun(m)", sample: "El cielo está azul." },
  { id: 228, es: "sol", en: "sun", pos: "noun(m)", sample: "El sol brilla fuerte." },
  { id: 229, es: "luna", en: "moon", pos: "noun(f)", sample: "La luna está llena." },
  { id: 230, es: "estrella", en: "star", pos: "noun(f)", sample: "Veo una estrella." },

  { id: 231, es: "viajar", en: "to travel", pos: "verb", sample: "Quiero viajar a España." },
  { id: 232, es: "cocinar", en: "to cook", pos: "verb", sample: "Cocino pasta hoy." },
  { id: 233, es: "bailar", en: "to dance", pos: "verb", sample: "Bailo con mis amigos." },
  { id: 234, es: "pintar", en: "to paint", pos: "verb", sample: "Pinto un cuadro nuevo." },
  { id: 235, es: "nadar", en: "to swim", pos: "verb", sample: "Nado en la piscina." },
  { id: 236, es: "gritar", en: "to shout", pos: "verb", sample: "Grito de alegría." },
  { id: 237, es: "comprar", en: "to buy", pos: "verb", sample: "Compro pan en la tienda." },
  { id: 238, es: "vender", en: "to sell", pos: "verb", sample: "Vendo mi bicicleta." },
  { id: 239, es: "romper", en: "to break", pos: "verb", sample: "Rompo el papel." },
  { id: 240, es: "ayudar", en: "to help", pos: "verb", sample: "Ayudo a mi hermano." },

  { id: 401, es: "levantarse", en: "to get up", pos: "verb", sample: "Me levanto a las siete de la mañana." },
  { id: 402, es: "sentarse", en: "to sit down", pos: "verb", sample: "Nos sentamos en la última fila." },
  { id: 403, es: "llamarse", en: "to be called", pos: "verb", sample: "Me llamo Ana." },
  { id: 404, es: "acordarse", en: "to remember", pos: "verb", sample: "No me acuerdo de su nombre." },
  { id: 405, es: "olvidar", en: "to forget", pos: "verb", sample: "Siempre olvido las llaves." },
  { id: 406, es: "lavar", en: "to wash", pos: "verb", sample: "Lavo los platos después de cenar." },
  { id: 407, es: "limpiar", en: "to clean", pos: "verb", sample: "Limpio mi habitación los domingos." },
  { id: 408, es: "planchar", en: "to iron", pos: "verb", sample: "Plancho la camisa para la entrevista." },
  { id: 409, es: "cortar", en: "to cut", pos: "verb", sample: "Corto el pan con cuidado." },
  { id: 410, es: "ganar", en: "to win; to earn", pos: "verb", sample: "Ella gana poco dinero pero es feliz." },

  { id: 411, es: "perder", en: "to lose", pos: "verb", sample: "Pierdo el autobús muchas veces." },
  { id: 412, es: "cambiar", en: "to change", pos: "verb", sample: "Quiero cambiar de trabajo." },
  { id: 413, es: "mejorar", en: "to improve", pos: "verb", sample: "Quiero mejorar mi español." },
  { id: 414, es: "empeorar", en: "to get worse", pos: "verb", sample: "El tiempo empeora por la tarde." },
  { id: 415, es: "llover", en: "to rain", pos: "verb", sample: "Hoy llueve todo el día." },
  { id: 416, es: "nevar", en: "to snow", pos: "verb", sample: "En enero casi siempre nieva." },
  { id: 417, es: "entrar", en: "to enter", pos: "verb", sample: "Entramos en el edificio en silencio." },
  { id: 418, es: "saludar", en: "to greet", pos: "verb", sample: "Saludo a mis vecinos cada mañana." },
  { id: 419, es: "sonreír", en: "to smile", pos: "verb", sample: "Ella siempre sonríe." },
  { id: 420, es: "reír", en: "to laugh", pos: "verb", sample: "Nos reímos mucho con esa película." },

  { id: 421, es: "llorar", en: "to cry", pos: "verb", sample: "El niño llora porque tiene sueño." },
  { id: 422, es: "besar", en: "to kiss", pos: "verb", sample: "Besa a su hijo antes de dormir." },
  { id: 423, es: "abrazar", en: "to hug", pos: "verb", sample: "Nos abrazamos al vernos." },
  { id: 424, es: "visitar", en: "to visit", pos: "verb", sample: "Visitamos a nuestros abuelos los sábados." },
  { id: 425, es: "invitar", en: "to invite", pos: "verb", sample: "Te invito a mi fiesta de cumpleaños." },
  { id: 426, es: "entristecer", en: "to make sad", pos: "verb", sample: "La noticia nos entristece mucho." },
  { id: 427, es: "alegrar", en: "to make happy", pos: "verb", sample: "Tu mensaje me alegra el día." },
  { id: 428, es: "preocuparse", en: "to worry", pos: "verb", sample: "No te preocupes por eso." },
  { id: 429, es: "relajarse", en: "to relax", pos: "verb", sample: "Me relajo escuchando música." },
  { id: 430, es: "sonar", en: "to ring; to sound", pos: "verb", sample: "El teléfono suena cada cinco minutos." },

  { id: 431, es: "suceder", en: "to happen", pos: "verb", sample: "¿Qué sucedió ayer?" },
  { id: 432, es: "apagar", en: "to turn off", pos: "verb", sample: "Apago la luz antes de dormir." },
  { id: 433, es: "encender", en: "to turn on", pos: "verb", sample: "Enciendo la televisión por la noche." },
  { id: 434, es: "recordar", en: "to remember", pos: "verb", sample: "Recuerdo bien ese día." },
  { id: 435, es: "probar", en: "to try; to taste", pos: "verb", sample: "Quiero probar este plato nuevo." },
  { id: 436, es: "firmar", en: "to sign", pos: "verb", sample: "Firma aquí, por favor." },
  { id: 437, es: "mandar", en: "to send", pos: "verb", sample: "Mando un correo a mi jefe." },
  { id: 438, es: "prestar", en: "to lend", pos: "verb", sample: "¿Puedes prestarme tu libro?" },
  { id: 439, es: "devolver", en: "to return (something)", pos: "verb", sample: "Devuelvo el libro a la biblioteca." },
  { id: 440, es: "tirar", en: "to throw away", pos: "verb", sample: "Tiro la basura cada noche." },

  { id: 441, es: "recoger", en: "to pick up; to collect", pos: "verb", sample: "Recojo a mi hijo del colegio." },
  { id: 442, es: "aprender", en: "to learn", pos: "verb", sample: "Aprendo español en línea." },
  { id: 443, es: "enseñar", en: "to teach; to show", pos: "verb", sample: "Mi profesora me enseña gramática." },
  { id: 444, es: "olerse", en: "to smell", pos: "verb", sample: "La sopa huele muy bien." },
  { id: 445, es: "gustar", en: "to like", pos: "verb", sample: "Me gusta mucho esta canción." },
  { id: 446, es: "encantar", en: "to love (to like a lot)", pos: "verb", sample: "Me encanta el chocolate." },
  { id: 447, es: "interesar", en: "to interest", pos: "verb", sample: "La historia me interesa mucho." },
  { id: 448, es: "importar", en: "to matter", pos: "verb", sample: "No me importa el resultado." },
  { id: 449, es: "molestar", en: "to bother", pos: "verb", sample: "Lo siento, ¿te molesto?" },
  { id: 450, es: "discutir", en: "to argue; to discuss", pos: "verb", sample: "No quiero discutir contigo." },

  { id: 451, es: "pelear", en: "to fight", pos: "verb", sample: "Los niños se pelean por el juguete." },
  { id: 452, es: "evitar", en: "to avoid", pos: "verb", sample: "Intento evitar el tráfico." },
  { id: 453, es: "entrar en contacto", en: "to get in touch", pos: "verb", sample: "Quiero entrar en contacto con ellos." },
  { id: 454, es: "usar", en: "to use", pos: "verb", sample: "Uso esta aplicación todos los días." },
  { id: 455, es: "apoyar", en: "to support", pos: "verb", sample: "Apoyo a mis amigos en todo." },
  { id: 456, es: "proteger", en: "to protect", pos: "verb", sample: "Necesitamos proteger el medio ambiente." },
  { id: 457, es: "cuidar", en: "to take care of", pos: "verb", sample: "Cuido a mi hermana pequeña." },
  { id: 458, es: "romperse", en: "to break (itself)", pos: "verb", sample: "Se rompe fácilmente." },
  { id: 459, es: "equivocarse", en: "to make a mistake", pos: "verb", sample: "Me equivoco muchas veces, pero aprendo." },
  { id: 460, es: "descansar", en: "to rest", pos: "verb", sample: "Descanso un poco después de comer." },

  { id: 461, es: "pasear", en: "to go for a walk", pos: "verb", sample: "Paseamos por el parque." },
  { id: 462, es: "tiritar", en: "to shiver", pos: "verb", sample: "El niño tirita de frío." },
  { id: 463, es: "toser", en: "to cough", pos: "verb", sample: "Toso mucho por la noche." },
  { id: 464, es: "estornudar", en: "to sneeze", pos: "verb", sample: "Ella estornuda por la alergia." },
  { id: 465, es: "curar", en: "to heal; to cure", pos: "verb", sample: "El médico cura al paciente." },
  { id: 466, es: "visita", en: "visit", pos: "noun(f)", sample: "Tenemos una visita importante hoy." },
  { id: 467, es: "cita", en: "appointment; date", pos: "noun(f)", sample: "Tengo una cita con el médico." },
  { id: 468, es: "reunión", en: "meeting", pos: "noun(f)", sample: "La reunión empieza a las tres." },
  { id: 469, es: "entrevista", en: "interview", pos: "noun(f)", sample: "Estoy nervioso por la entrevista." },
  { id: 470, es: "vacaciones", en: "vacation; holidays", pos: "noun(f,pl)", sample: "Nos vamos de vacaciones en agosto." },

  { id: 471, es: "fiesta", en: "party", pos: "noun(f)", sample: "La fiesta fue muy divertida." },
  { id: 472, es: "cumpleaños", en: "birthday", pos: "noun(m)", sample: "Hoy es mi cumpleaños." },
  { id: 473, es: "boda", en: "wedding", pos: "noun(f)", sample: "La boda fue en una iglesia pequeña." },
  { id: 474, es: "aniversario", en: "anniversary", pos: "noun(m)", sample: "Celebran su aniversario cada año." },
  { id: 475, es: "regalo", en: "gift", pos: "noun(m)", sample: "Recibo un regalo bonito." },
  { id: 476, es: "sorpresa", en: "surprise", pos: "noun(f)", sample: "La fiesta fue una sorpresa." },
  { id: 477, es: "entrada", en: "entrance; ticket", pos: "noun(f)", sample: "Compramos entradas para el concierto." },
  { id: 478, es: "salida", en: "exit; departure", pos: "noun(f)", sample: "La salida está al fondo del pasillo." },
  { id: 479, es: "esquina", en: "corner (street)", pos: "noun(f)", sample: "Nos vemos en la esquina del banco." },
  { id: 480, es: "cruce", en: "crossing; intersection", pos: "noun(m)", sample: "Cruza en el cruce con cuidado." },

  { id: 481, es: "semáforo", en: "traffic light", pos: "noun(m)", sample: "El semáforo está en rojo." },
  { id: 482, es: "acera", en: "sidewalk", pos: "noun(f)", sample: "Caminamos por la acera." },
  { id: 483, es: "carretera", en: "road; highway", pos: "noun(f)", sample: "La carretera está vacía." },
  { id: 484, es: "cartera", en: "wallet", pos: "noun(f)", sample: "No encuentro mi cartera." },
  { id: 485, es: "bolso", en: "bag; handbag", pos: "noun(m)", sample: "Deja el bolso en la silla." },
  { id: 486, es: "maleta", en: "suitcase", pos: "noun(f)", sample: "Preparo la maleta para el viaje." },
  { id: 487, es: "billete", en: "ticket; bill", pos: "noun(m)", sample: "Necesito un billete de tren." },
  { id: 488, es: "pasaporte", en: "passport", pos: "noun(m)", sample: "Lleva el pasaporte contigo." },
  { id: 489, es: "documento", en: "document", pos: "noun(m)", sample: "Guardo los documentos en la carpeta." },
  { id: 490, es: "firma", en: "signature", pos: "noun(f)", sample: "Tu firma va aquí." },

  { id: 491, es: "correo", en: "mail; post", pos: "noun(m)", sample: "Reviso el correo cada mañana." },
  { id: 492, es: "paquete", en: "package", pos: "noun(m)", sample: "El paquete llega mañana." },
  { id: 493, es: "sobre", en: "envelope", pos: "noun(m)", sample: "Pon la carta en el sobre." },
  { id: 494, es: "sello", en: "stamp", pos: "noun(m)", sample: "Necesitas un sello para la carta." },
  { id: 495, es: "periódico", en: "newspaper", pos: "noun(m)", sample: "Leo el periódico los domingos." },
  { id: 496, es: "revista", en: "magazine", pos: "noun(f)", sample: "Compro una revista en el kiosco." },
  { id: 497, es: "noticia", en: "news item", pos: "noun(f)", sample: "La noticia está en la portada." },
  { id: 498, es: "canal", en: "channel", pos: "noun(m)", sample: "Cambio de canal en la televisión." },
  { id: 499, es: "pantalla", en: "screen", pos: "noun(f)", sample: "La pantalla del móvil está rota." },
  { id: 500, es: "teclado", en: "keyboard", pos: "noun(m)", sample: "Escribo rápido en el teclado." },

  { id: 501, es: "ratón", en: "mouse", pos: "noun(m)", sample: "El ratón del ordenador no funciona." },
  { id: 502, es: "contraseña", en: "password", pos: "noun(f)", sample: "No recuerdo mi contraseña." },
  { id: 503, es: "página", en: "page", pos: "noun(f)", sample: "La respuesta está en la página diez." },
  { id: 504, es: "archivo", en: "file", pos: "noun(m)", sample: "Guardo el archivo en el escritorio." },
  { id: 505, es: "carpeta", en: "folder", pos: "noun(f)", sample: "Tengo muchas carpetas en el ordenador." },
  { id: 506, es: "red", en: "network; internet", pos: "noun(f)", sample: "La red no funciona bien hoy." },
  { id: 507, es: "mensaje", en: "message", pos: "noun(m)", sample: "Te envío un mensaje luego." },
  { id: 508, es: "llamada", en: "call", pos: "noun(f)", sample: "Tengo una llamada perdida." },
  { id: 509, es: "pantalla táctil", en: "touch screen", pos: "noun(f)", sample: "La pantalla táctil es muy cómoda." },
  { id: 510, es: "batería", en: "battery", pos: "noun(f)", sample: "La batería del móvil está baja." },

  { id: 511, es: "enchufe", en: "socket; plug", pos: "noun(m)", sample: "El enchufe está detrás de la mesa." },
  { id: 512, es: "cable", en: "cable", pos: "noun(m)", sample: "Necesito un cable más largo." },
  { id: 513, es: "luz", en: "light", pos: "noun(f)", sample: "Apaga la luz, por favor." },
  { id: 514, es: "sombra", en: "shadow", pos: "noun(f)", sample: "La sombra del árbol es grande." },
  { id: 515, es: "calor", en: "heat", pos: "noun(m)", sample: "Hace mucho calor en verano." },
  { id: 516, es: "frío", en: "cold", pos: "noun(m)", sample: "El frío entra por la ventana." },
  { id: 517, es: "lluvia", en: "rain", pos: "noun(f)", sample: "La lluvia es muy fuerte hoy." },
  { id: 518, es: "nieve", en: "snow", pos: "noun(f)", sample: "La nieve cubre la ciudad." },
  { id: 519, es: "viento", en: "wind", pos: "noun(m)", sample: "El viento sopla muy fuerte." },
  { id: 520, es: "tormenta", en: "storm", pos: "noun(f)", sample: "Hay una tormenta esta noche." },

  { id: 521, es: "primavera", en: "spring (season)", pos: "noun(f)", sample: "La primavera es mi estación favorita." },
  { id: 522, es: "verano", en: "summer", pos: "noun(m)", sample: "En verano vamos a la playa." },
  { id: 523, es: "otoño", en: "autumn; fall", pos: "noun(m)", sample: "En otoño caen las hojas." },
  { id: 524, es: "invierno", en: "winter", pos: "noun(m)", sample: "En invierno hace mucho frío." },
  { id: 525, es: "enero", en: "January", pos: "noun(m)", sample: "El curso empieza en enero." },
  { id: 526, es: "febrero", en: "February", pos: "noun(m)", sample: "Febrero es un mes corto." },
  { id: 527, es: "marzo", en: "March", pos: "noun(m)", sample: "En marzo llueve bastante." },
  { id: 528, es: "abril", en: "April", pos: "noun(m)", sample: "Abril es un mes lluvioso." },
  { id: 529, es: "mayo", en: "May", pos: "noun(m)", sample: "En mayo hay muchas flores." },
  { id: 530, es: "junio", en: "June", pos: "noun(m)", sample: "En junio empieza el verano." },

  { id: 531, es: "julio", en: "July", pos: "noun(m)", sample: "En julio hace mucho calor." },
  { id: 532, es: "agosto", en: "August", pos: "noun(m)", sample: "Agosto es un mes de vacaciones." },
  { id: 533, es: "septiembre", en: "September", pos: "noun(m)", sample: "En septiembre vuelven las clases." },
  { id: 534, es: "octubre", en: "October", pos: "noun(m)", sample: "Octubre es un mes tranquilo." },
  { id: 535, es: "noviembre", en: "November", pos: "noun(m)", sample: "Noviembre suele ser frío." },
  { id: 536, es: "diciembre", en: "December", pos: "noun(m)", sample: "En diciembre decoramos la casa." },
  { id: 537, es: "lunes", en: "Monday", pos: "noun(m)", sample: "El lunes empiezo un nuevo trabajo." },
  { id: 538, es: "martes", en: "Tuesday", pos: "noun(m)", sample: "El martes tengo examen." },
  { id: 539, es: "miércoles", en: "Wednesday", pos: "noun(m)", sample: "El miércoles voy al gimnasio." },
  { id: 540, es: "jueves", en: "Thursday", pos: "noun(m)", sample: "El jueves cenamos juntos." },

  { id: 541, es: "viernes", en: "Friday", pos: "noun(m)", sample: "El viernes salimos de fiesta." },
  { id: 542, es: "sábado", en: "Saturday", pos: "noun(m)", sample: "El sábado descanso en casa." },
  { id: 543, es: "domingo", en: "Sunday", pos: "noun(m)", sample: "El domingo comemos con la familia." },
  { id: 544, es: "minuto", en: "minute", pos: "noun(m)", sample: "Espérame un minuto." },
  { id: 545, es: "hora", en: "hour; time", pos: "noun(f)", sample: "La película dura dos horas." },
  { id: 546, es: "semana", en: "week", pos: "noun(f)", sample: "Trabajo cuarenta horas a la semana." },
  { id: 547, es: "mes", en: "month", pos: "noun(m)", sample: "Pago el alquiler cada mes." },
  { id: 548, es: "año", en: "year", pos: "noun(m)", sample: "Este año estudio mucho." },
  { id: 549, es: "siglo", en: "century", pos: "noun(m)", sample: "Es una iglesia del siglo XVIII." },
  { id: 550, es: "momento", en: "moment", pos: "noun(m)", sample: "Es un momento muy especial." },

  { id: 551, es: "siempre", en: "always", pos: "adv", sample: "Siempre llego temprano." },
  { id: 552, es: "casi", en: "almost", pos: "adv", sample: "Casi olvido tu cumpleaños." },
  { id: 553, es: "nunca jamás", en: "never ever", pos: "adv", sample: "Nunca jamás vuelvo a hacerlo." },
  { id: 554, es: "tal vez", en: "maybe", pos: "adv", sample: "Tal vez voy a la fiesta." },
  { id: 555, es: "quizás", en: "perhaps", pos: "adv", sample: "Quizás tienes razón." },
  { id: 556, es: "aproximadamente", en: "approximately", pos: "adv", sample: "Llegamos en aproximadamente diez minutos." },
  { id: 557, es: "realmente", en: "really", pos: "adv", sample: "Realmente me gusta este lugar." },
  { id: 558, es: "simplemente", en: "simply", pos: "adv", sample: "Simplemente no tengo tiempo." },
  { id: 559, es: "especialmente", en: "especially", pos: "adv", sample: "Me gusta especialmente el chocolate negro." },
  { id: 560, es: "finalmente", en: "finally", pos: "adv", sample: "Finalmente terminamos el proyecto." },

  { id: 561, es: "además", en: "besides; moreover", pos: "adv", sample: "Es barato y, además, es bonito." },
  { id: 562, es: "por eso", en: "therefore", pos: "adv", sample: "Está enfermo, por eso no viene." },
  { id: 563, es: "por ejemplo", en: "for example", pos: "adv", sample: "Me gustan los deportes, por ejemplo el tenis." },
  { id: 564, es: "por fin", en: "at last", pos: "adv", sample: "Por fin llegas a casa." },
  { id: 565, es: "claro que sí", en: "of course", pos: "expr", sample: "¿Vienes conmigo? Claro que sí." },
  { id: 566, es: "claro que no", en: "of course not", pos: "expr", sample: "¿Te molesta? Claro que no." },
  { id: 567, es: "tal", en: "such", pos: "det", sample: "Nunca he visto tal cosa." },
  { id: 568, es: "cualquier", en: "any", pos: "det", sample: "Puedes elegir cualquier libro." },
  { id: 569, es: "ningún", en: "no; none (masc.)", pos: "det", sample: "No tengo ningún problema." },
  { id: 570, es: "ninguna", en: "no; none (fem.)", pos: "det", sample: "No hay ninguna tienda abierta." },

  { id: 571, es: "algún", en: "some (masc.)", pos: "det", sample: "Tengo algún dinero en efectivo." },
  { id: 572, es: "alguna", en: "some (fem.)", pos: "det", sample: "Tengo alguna idea para el proyecto." },
  { id: 573, es: "varios", en: "several (masc.)", pos: "det", sample: "Hay varios libros en la mesa." },
  { id: 574, es: "varias", en: "several (fem.)", pos: "det", sample: "Tengo varias preguntas." },
  { id: 575, es: "propio", en: "own (masc.)", pos: "adj", sample: "Quiero tener mi propio cuarto." },
  { id: 576, es: "propia", en: "own (fem.)", pos: "adj", sample: "Ella tiene su propia empresa." },
  { id: 577, es: "seguro", en: "sure; safe (masc.)", pos: "adj", sample: "Estoy seguro de la respuesta." },
  { id: 578, es: "segura", en: "sure; safe (fem.)", pos: "adj", sample: "Ella está segura de su decisión." },
  { id: 579, es: "peligro", en: "danger", pos: "noun(m)", sample: "Ese lugar es un peligro para los niños." },
  { id: 580, es: "seguridad", en: "safety; security", pos: "noun(f)", sample: "La seguridad es muy importante." },

  { id: 581, es: "salud", en: "health", pos: "noun(f)", sample: "La salud es lo más importante." },
  { id: 582, es: "enfermedad", en: "illness", pos: "noun(f)", sample: "La enfermedad dura pocos días." },
  { id: 583, es: "fiebre", en: "fever", pos: "noun(f)", sample: "Tengo fiebre y dolor de cabeza." },
  { id: 584, es: "cita médica", en: "medical appointment", pos: "noun(f)", sample: "Tengo una cita médica mañana." },
  { id: 585, es: "medicamento", en: "medicine", pos: "noun(m)", sample: "Toma este medicamento después de comer." },
  { id: 586, es: "pastilla", en: "pill; tablet", pos: "noun(f)", sample: "Tomo una pastilla al día." },
  { id: 587, es: "inyección", en: "injection", pos: "noun(f)", sample: "El médico pone una inyección." },
  { id: 588, es: "herida", en: "wound", pos: "noun(f)", sample: "La herida no es grave." },
  { id: 589, es: "dolor", en: "pain", pos: "noun(m)", sample: "Tengo dolor de espalda." },
  { id: 590, es: "ambulancia", en: "ambulance", pos: "noun(f)", sample: "Llaman a la ambulancia rápidamente." },

  { id: 591, es: "policía", en: "police; police officer", pos: "noun(f)", sample: "La policía llega al lugar." },
  { id: 592, es: "banco", en: "bank; bench", pos: "noun(m)", sample: "Trabajo en un banco del centro." },
  { id: 593, es: "iglesia", en: "church", pos: "noun(f)", sample: "La iglesia está en la plaza." },
  { id: 594, es: "museo", en: "museum", pos: "noun(m)", sample: "El museo cierra a las seis." },
  { id: 595, es: "castillo", en: "castle", pos: "noun(m)", sample: "Visitamos un castillo antiguo." },
  { id: 596, es: "puente", en: "bridge", pos: "noun(m)", sample: "El puente cruza el río." },
  { id: 597, es: "isla", en: "island", pos: "noun(f)", sample: "La isla es muy pequeña." },
  { id: 598, es: "campo", en: "countryside; field", pos: "noun(m)", sample: "Mis abuelos viven en el campo." },
  { id: 599, es: "granja", en: "farm", pos: "noun(f)", sample: "En la granja hay muchas vacas." },
  { id: 600, es: "ciudad natal", en: "hometown", pos: "noun(f)", sample: "Echo de menos mi ciudad natal." },

  { id: 601, es: "color", en: "color", pos: "noun(m)", sample: "Mi color favorito es el azul." },
  { id: 602, es: "rojo", en: "red", pos: "adj", sample: "El coche rojo es muy rápido." },
  { id: 603, es: "azul", en: "blue", pos: "adj", sample: "El cielo está azul hoy." },
  { id: 604, es: "verde", en: "green", pos: "adj", sample: "El campo está muy verde." },
  { id: 605, es: "amarillo", en: "yellow", pos: "adj", sample: "Llevo un jersey amarillo." },
  { id: 606, es: "negro", en: "black", pos: "adj", sample: "El gato negro duerme en el sofá." },
  { id: 607, es: "blanco", en: "white", pos: "adj", sample: "La camisa blanca está limpia." },
  { id: 608, es: "marrón", en: "brown", pos: "adj", sample: "Tengo zapatos marrones." },
  { id: 609, es: "gris", en: "gray", pos: "adj", sample: "El día está gris y frío." },
  { id: 610, es: "rosa", en: "pink", pos: "adj", sample: "Compré flores rosa." },

  { id: 611, es: "naranja", en: "orange", pos: "adj", sample: "Me gusta el jersey naranja." },
  { id: 612, es: "morado", en: "purple", pos: "adj", sample: "Pinto la pared de color morado." },
  { id: 613, es: "claro", en: "light (color)", pos: "adj", sample: "Prefiero colores claros." },
  { id: 614, es: "oscuro", en: "dark (color)", pos: "adj", sample: "El azul oscuro es elegante." },
  { id: 615, es: "ropa interior", en: "underwear", pos: "noun(f)", sample: "Compro ropa interior nueva." },
  { id: 616, es: "pantalón", en: "trousers; pants", pos: "noun(m)", sample: "Este pantalón es cómodo." },
  { id: 617, es: "falda", en: "skirt", pos: "noun(f)", sample: "La falda es muy corta." },
  { id: 618, es: "vestido", en: "dress", pos: "noun(m)", sample: "Lleva un vestido elegante." },
  { id: 619, es: "abrigo", en: "coat", pos: "noun(m)", sample: "En invierno uso un abrigo largo." },
  { id: 620, es: "sombrero", en: "hat", pos: "noun(m)", sample: "El sombrero la protege del sol." },

  { id: 621, es: "gorra", en: "cap", pos: "noun(f)", sample: "Lleva una gorra azul." },
  { id: 622, es: "bufanda", en: "scarf", pos: "noun(f)", sample: "Me pongo una bufanda cuando hace frío." },
  { id: 623, es: "guante", en: "glove", pos: "noun(m)", sample: "He perdido un guante." },
  { id: 624, es: "calcetín", en: "sock", pos: "noun(m)", sample: "Tengo calcetines de colores." },
  { id: 625, es: "vaqueros", en: "jeans", pos: "noun(m,pl)", sample: "Siempre llevo vaqueros los fines de semana." },
  { id: 626, es: "traje", en: "suit", pos: "noun(m)", sample: "Lleva un traje negro en la boda." },
  { id: 627, es: "corbata", en: "tie", pos: "noun(f)", sample: "La corbata es demasiado corta." },
  { id: 628, es: "bolsillo", en: "pocket", pos: "noun(m)", sample: "Guardo las llaves en el bolsillo." },
  { id: 629, es: "talla", en: "size", pos: "noun(f)", sample: "Esta talla es demasiado grande." },
  { id: 630, es: "probador", en: "fitting room", pos: "noun(m)", sample: "El probador está al fondo." },

  { id: 631, es: "precio", en: "price", pos: "noun(m)", sample: "El precio es muy alto." },
  { id: 632, es: "oferta", en: "offer; sale", pos: "noun(f)", sample: "Este producto está en oferta." },
  { id: 633, es: "descuento", en: "discount", pos: "noun(m)", sample: "Hay un diez por ciento de descuento." },
  { id: 634, es: "caja", en: "cash register; box", pos: "noun(f)", sample: "Pagamos en la caja." },
  { id: 635, es: "dependiente", en: "shop assistant", pos: "noun(m)", sample: "El dependiente es muy amable." },
  { id: 636, es: "cliente", en: "customer", pos: "noun(m)", sample: "La tienda tiene muchos clientes." },
  { id: 637, es: "moneda", en: "coin", pos: "noun(f)", sample: "No tengo monedas pequeñas." },
  { id: 638, es: "tarjeta", en: "card", pos: "noun(f)", sample: "Pago con tarjeta de crédito." },
  { id: 639, es: "efectivo", en: "cash", pos: "noun(m)", sample: "Prefiero pagar en efectivo." },
  { id: 640, es: "cuenta", en: "bill; account", pos: "noun(f)", sample: "La cuenta, por favor." },

  { id: 641, es: "propina", en: "tip", pos: "noun(f)", sample: "Dejamos poca propina." },
  { id: 642, es: "carrito", en: "shopping cart", pos: "noun(m)", sample: "Cojo un carrito en el supermercado." },
  { id: 643, es: "lista", en: "list", pos: "noun(f)", sample: "Hago una lista de la compra." },
  { id: 644, es: "panadería", en: "bakery", pos: "noun(f)", sample: "Compro pan en la panadería." },
  { id: 645, es: "farmacia", en: "pharmacy", pos: "noun(f)", sample: "La farmacia abre hasta las nueve." },
  { id: 646, es: "carnicería", en: "butcher's shop", pos: "noun(f)", sample: "La carne es de la carnicería de la esquina." },
  { id: 647, es: "pescadería", en: "fish shop", pos: "noun(f)", sample: "El pescado fresco está en la pescadería." },
  { id: 648, es: "frutería", en: "fruit shop", pos: "noun(f)", sample: "Las naranjas son de la frutería." },
  { id: 649, es: "mercado", en: "market", pos: "noun(m)", sample: "El mercado está lleno de gente." },
  { id: 650, es: "centro comercial", en: "shopping mall", pos: "noun(m)", sample: "Vamos al centro comercial por la tarde." },

  { id: 651, es: "pared", en: "wall", pos: "noun(f)", sample: "Cuelgo un cuadro en la pared." },
  { id: 652, es: "suelo", en: "floor", pos: "noun(m)", sample: "El suelo está frío." },
  { id: 653, es: "techo", en: "ceiling; roof", pos: "noun(m)", sample: "El techo es muy alto." },
  { id: 654, es: "escalera", en: "stairs", pos: "noun(f)", sample: "Subimos por la escalera." },
  { id: 655, es: "ascensor", en: "elevator", pos: "noun(m)", sample: "Tomamos el ascensor al quinto piso." },
  { id: 656, es: "sótano", en: "basement", pos: "noun(m)", sample: "Guardan vino en el sótano." },
  { id: 657, es: "jardín", en: "garden", pos: "noun(m)", sample: "El jardín tiene muchas flores." },
  { id: 658, es: "balcón", en: "balcony", pos: "noun(m)", sample: "Tomamos café en el balcón." },
  { id: 659, es: "pasillo", en: "hallway; corridor", pos: "noun(m)", sample: "El pasillo es estrecho." },
  { id: 660, es: "entrada", en: "entrance", pos: "noun(f)", sample: "La entrada está a la derecha." },

  { id: 661, es: "cocina", en: "kitchen", pos: "noun(f)", sample: "La cocina es pequeña pero moderna." },
  { id: 662, es: "baño", en: "bathroom", pos: "noun(m)", sample: "El baño está al final del pasillo." },
  { id: 663, es: "salón", en: "living room", pos: "noun(m)", sample: "Vemos la tele en el salón." },
  { id: 664, es: "comedor", en: "dining room", pos: "noun(m)", sample: "Comemos en el comedor." },
  { id: 665, es: "nevera", en: "fridge", pos: "noun(f)", sample: "La nevera está casi vacía." },
  { id: 666, es: "horno", en: "oven", pos: "noun(m)", sample: "Cocino la pizza en el horno." },
  { id: 667, es: "microondas", en: "microwave", pos: "noun(m)", sample: "Caliento la comida en el microondas." },
  { id: 668, es: "fregadero", en: "sink", pos: "noun(m)", sample: "Los platos están en el fregadero." },
  { id: 669, es: "plato", en: "plate; dish", pos: "noun(m)", sample: "Lavo los platos después de cenar." },
  { id: 670, es: "vaso", en: "glass", pos: "noun(m)", sample: "Quiero un vaso de agua." },

  { id: 671, es: "cuchillo", en: "knife", pos: "noun(m)", sample: "El cuchillo no corta bien." },
  { id: 672, es: "tenedor", en: "fork", pos: "noun(m)", sample: "Falta un tenedor en la mesa." },
  { id: 673, es: "cuchara", en: "spoon", pos: "noun(f)", sample: "Necesito una cuchara para la sopa." },
  { id: 674, es: "taza", en: "cup; mug", pos: "noun(f)", sample: "Bebo té en una taza grande." },
  { id: 675, es: "sartén", en: "pan (for cooking)", pos: "noun(f)", sample: "Frío los huevos en la sartén." },
  { id: 676, es: "olla", en: "pot", pos: "noun(f)", sample: "La sopa está en la olla." },
  { id: 677, es: "tabla de cortar", en: "cutting board", pos: "noun(f)", sample: "Corto el pan en la tabla de cortar." },
  { id: 678, es: "cuchillo de cocina", en: "kitchen knife", pos: "noun(m)", sample: "El cuchillo de cocina es nuevo." },
  { id: 679, es: "mantel", en: "tablecloth", pos: "noun(m)", sample: "Ponemos el mantel antes de comer." },
  { id: 680, es: "servilleta", en: "napkin", pos: "noun(f)", sample: "Pásame una servilleta, por favor." },

  { id: 681, es: "desayuno", en: "breakfast", pos: "noun(m)", sample: "El desayuno es a las ocho." },
  { id: 682, es: "almuerzo", en: "lunch", pos: "noun(m)", sample: "El almuerzo es a mediodía." },
  { id: 683, es: "cena", en: "dinner", pos: "noun(f)", sample: "La cena es ligera." },
  { id: 684, es: "merienda", en: "afternoon snack", pos: "noun(f)", sample: "Tomamos una merienda en el parque." },
  { id: 685, es: "hambre", en: "hunger", pos: "noun(f)", sample: "Tengo mucha hambre." },
  { id: 686, es: "sed", en: "thirst", pos: "noun(f)", sample: "Tengo sed, necesito agua." },
  { id: 687, es: "sal", en: "salt", pos: "noun(f)", sample: "La sopa tiene mucha sal." },
  { id: 688, es: "azúcar", en: "sugar", pos: "noun(m)", sample: "Pongo azúcar en el café." },
  { id: 689, es: "aceite", en: "oil", pos: "noun(m)", sample: "Freímos las patatas en aceite." },
  { id: 690, es: "vinagre", en: "vinegar", pos: "noun(m)", sample: "El vinagre está en la mesa." },

  { id: 691, es: "carne", en: "meat", pos: "noun(f)", sample: "Comemos poca carne." },
  { id: 692, es: "pescado", en: "fish (food)", pos: "noun(m)", sample: "El pescado está muy fresco." },
  { id: 693, es: "verdura", en: "vegetable", pos: "noun(f)", sample: "La sopa tiene muchas verduras." },
  { id: 694, es: "ensalada", en: "salad", pos: "noun(f)", sample: "Como ensalada todos los días." },
  { id: 695, es: "arroz", en: "rice", pos: "noun(m)", sample: "El arroz es muy común." },
  { id: 696, es: "pasta", en: "pasta", pos: "noun(f)", sample: "La pasta está al dente." },
  { id: 697, es: "huevo", en: "egg", pos: "noun(m)", sample: "Desayuno pan con huevo." },
  { id: 698, es: "queso", en: "cheese", pos: "noun(m)", sample: "El queso es francés." },
  { id: 699, es: "mantequilla", en: "butter", pos: "noun(f)", sample: "Pongo mantequilla en el pan." },
  { id: 700, es: "yogur", en: "yogurt", pos: "noun(m)", sample: "Tomo yogur de postre." },

  { id: 701, es: "manzana", en: "apple", pos: "noun(f)", sample: "Como una manzana cada día." },
  { id: 702, es: "naranja", en: "orange (fruit)", pos: "noun(f)", sample: "El zumo de naranja es natural." },
  { id: 703, es: "plátano", en: "banana", pos: "noun(m)", sample: "El plátano está muy dulce." },
  { id: 704, es: "uva", en: "grape", pos: "noun(f)", sample: "Las uvas están maduras." },
  { id: 705, es: "fresa", en: "strawberry", pos: "noun(f)", sample: "Me encanta el helado de fresa." },
  { id: 706, es: "limón", en: "lemon", pos: "noun(m)", sample: "Pongo limón en el té." },
  { id: 707, es: "melón", en: "melon", pos: "noun(m)", sample: "El melón está frío y rico." },
  { id: 708, es: "sandía", en: "watermelon", pos: "noun(f)", sample: "La sandía es muy refrescante." },
  { id: 709, es: "pera", en: "pear", pos: "noun(f)", sample: "La pera está un poco dura." },
  { id: 710, es: "piña", en: "pineapple", pos: "noun(f)", sample: "La piña es muy dulce." },

  { id: 711, es: "tomate", en: "tomato", pos: "noun(m)", sample: "Corto tomate para la ensalada." },
  { id: 712, es: "cebolla", en: "onion", pos: "noun(f)", sample: "La cebolla me hace llorar." },
  { id: 713, es: "zanahoria", en: "carrot", pos: "noun(f)", sample: "Las zanahorias son naranjas." },
  { id: 714, es: "patata", en: "potato", pos: "noun(f)", sample: "Las patatas están fritas." },
  { id: 715, es: "pepino", en: "cucumber", pos: "noun(m)", sample: "El pepino está muy fresco." },
  { id: 716, es: "lechuga", en: "lettuce", pos: "noun(f)", sample: "La ensalada lleva lechuga." },
  { id: 717, es: "ajo", en: "garlic", pos: "noun(m)", sample: "La salsa tiene mucho ajo." },
  { id: 718, es: "pimiento", en: "pepper (vegetable)", pos: "noun(m)", sample: "Los pimientos son rojos y verdes." },
  { id: 719, es: "seta", en: "mushroom", pos: "noun(f)", sample: "Hay setas en la pizza." },
  { id: 720, es: "sopa", en: "soup", pos: "noun(f)", sample: "Tomamos sopa caliente." },

  { id: 721, es: "postre", en: "dessert", pos: "noun(m)", sample: "El postre es un helado." },
  { id: 722, es: "pastel", en: "cake; pastry", pos: "noun(m)", sample: "Preparamos un pastel de chocolate." },
  { id: 723, es: "galleta", en: "cookie; biscuit", pos: "noun(f)", sample: "Como galletas con té." },
  { id: 724, es: "helado", en: "ice cream", pos: "noun(m)", sample: "El helado se derrite rápido." },
  { id: 725, es: "chocolate", en: "chocolate", pos: "noun(m)", sample: "El chocolate negro es mi favorito." },
  { id: 726, es: "caramelo", en: "candy", pos: "noun(m)", sample: "Los niños comen muchos caramelos." },
  { id: 727, es: "tarta", en: "cake", pos: "noun(f)", sample: "La tarta de manzana es casera." },
  { id: 728, es: "miel", en: "honey", pos: "noun(f)", sample: "Pongo miel en el yogur." },
  { id: 729, es: "mermelada", en: "jam", pos: "noun(f)", sample: "La mermelada es de fresa." },
  { id: 730, es: "sabor", en: "flavor; taste", pos: "noun(m)", sample: "Este sabor es muy fuerte." },

  { id: 731, es: "amargo", en: "bitter", pos: "adj", sample: "El café sin azúcar es amargo." },
  { id: 732, es: "dulce", en: "sweet", pos: "adj", sample: "Este pastel es muy dulce." },
  { id: 733, es: "salado", en: "salty", pos: "adj", sample: "El queso está muy salado." },
  { id: 734, es: "picante", en: "spicy", pos: "adj", sample: "La comida mexicana es picante." },
  { id: 735, es: "rico", en: "tasty; rich", pos: "adj", sample: "El plato está muy rico." },
  { id: 736, es: "ligero", en: "light (food)", pos: "adj", sample: "Prefiero un desayuno ligero." },
  { id: 737, es: "pesado", en: "heavy (food)", pos: "adj", sample: "La cena fue un poco pesada." },
  { id: 738, es: "frío", en: "cold (food/drink)", pos: "adj", sample: "El café frío no me gusta." },
  { id: 739, es: "caliente", en: "hot (food/drink)", pos: "adj", sample: "La sopa está caliente." },
  { id: 740, es: "fresco", en: "fresh", pos: "adj", sample: "El pan es muy fresco." },

  { id: 741, es: "cocinar", en: "to cook", pos: "verb", sample: "Me gusta cocinar para mis amigos." },
  { id: 742, es: "freír", en: "to fry", pos: "verb", sample: "Freímos las patatas en aceite." },
  { id: 743, es: "hervir", en: "to boil", pos: "verb", sample: "Hierve el agua para la pasta." },
  { id: 744, es: "mezclar", en: "to mix", pos: "verb", sample: "Mezclo todos los ingredientes." },
  { id: 745, es: "añadir", en: "to add", pos: "verb", sample: "Añadimos sal al final." },
  { id: 746, es: "cortar en trozos", en: "to cut into pieces", pos: "verb", sample: "Corta la carne en trozos pequeños." },
  { id: 747, es: "probar", en: "to taste; to try", pos: "verb", sample: "Debes probar este plato." },
  { id: 748, es: "servir", en: "to serve", pos: "verb", sample: "Servimos la comida caliente." },
  { id: 749, es: "invitar a comer", en: "to invite to eat", pos: "verb", sample: "Los invitamos a comer el domingo." },
  { id: 750, es: "llenar", en: "to fill", pos: "verb", sample: "Lleno el vaso de agua." },

  { id: 751, es: "vaciar", en: "to empty", pos: "verb", sample: "Vacío la basura todas las noches." },
  { id: 752, es: "lavavajillas", en: "dishwasher", pos: "noun(m)", sample: "Ponemos los platos en el lavavajillas." },
  { id: 753, es: "detergente", en: "detergent", pos: "noun(m)", sample: "El detergente está en el armario." },
  { id: 754, es: "esponja", en: "sponge", pos: "noun(f)", sample: "Lavo los platos con una esponja." },
  { id: 755, es: "trapo", en: "cloth; rag", pos: "noun(m)", sample: "Seco la mesa con un trapo." },
  { id: 756, es: "basura", en: "trash; garbage", pos: "noun(f)", sample: "Saco la basura por la noche." },
  { id: 757, es: "contenedor", en: "container; bin", pos: "noun(m)", sample: "El contenedor está en la calle." },
  { id: 758, es: "reciclaje", en: "recycling", pos: "noun(m)", sample: "Hacemos reciclaje en casa." },
  { id: 759, es: "limpio", en: "clean", pos: "adj", sample: "El baño está limpio." },
  { id: 760, es: "sucio", en: "dirty", pos: "adj", sample: "El suelo está sucio." },

  { id: 761, es: "ordenado", en: "tidy; organized", pos: "adj", sample: "Su cuarto está muy ordenado." },
  { id: 762, es: "desordenado", en: "messy", pos: "adj", sample: "Mi escritorio está desordenado." },
  { id: 763, es: "apagar la luz", en: "to turn off the light", pos: "verb", sample: "Apaga la luz al salir." },
  { id: 764, es: "poner la mesa", en: "to set the table", pos: "verb", sample: "Los niños ponen la mesa." },
  { id: 765, es: "recoger la mesa", en: "to clear the table", pos: "verb", sample: "Ella recoge la mesa después de cenar." },
  { id: 766, es: "hacer la cama", en: "to make the bed", pos: "verb", sample: "Hago la cama cada mañana." },
  { id: 767, es: "barrer", en: "to sweep", pos: "verb", sample: "Barro el suelo de la cocina." },
  { id: 768, es: "fregar el suelo", en: "to mop the floor", pos: "verb", sample: "Fregamos el suelo los sábados." },
  { id: 769, es: "lavar la ropa", en: "to do the laundry", pos: "verb", sample: "Lavo la ropa una vez por semana." },
  { id: 770, es: "tender la ropa", en: "to hang the clothes", pos: "verb", sample: "Tiende la ropa en el balcón." },

  { id: 771, es: "planchar la ropa", en: "to iron the clothes", pos: "verb", sample: "Plancha la camisa blanca." },
  { id: 772, es: "doblar la ropa", en: "to fold the clothes", pos: "verb", sample: "Doblo la ropa limpia." },
  { id: 773, es: "armario", en: "wardrobe; closet", pos: "noun(m)", sample: "Guardo la ropa en el armario." },
  { id: 774, es: "cajón", en: "drawer", pos: "noun(m)", sample: "Las cucharas están en el cajón." },
  { id: 775, es: "estantería", en: "shelf", pos: "noun(f)", sample: "Los libros están en la estantería." },
  { id: 776, es: "ropa de cama", en: "bed linen", pos: "noun(f)", sample: "Cambio la ropa de cama cada semana." },
  { id: 777, es: "almohada", en: "pillow", pos: "noun(f)", sample: "La almohada es muy blanda." },
  { id: 778, es: "manta", en: "blanket", pos: "noun(f)", sample: "Me tapo con una manta." },
  { id: 779, es: "sábana", en: "sheet", pos: "noun(f)", sample: "Las sábanas están limpias." },
  { id: 780, es: "colchón", en: "mattress", pos: "noun(m)", sample: "El colchón es cómodo." },

  { id: 781, es: "despertador", en: "alarm clock", pos: "noun(m)", sample: "El despertador suena a las seis." },
  { id: 782, es: "lámpara", en: "lamp", pos: "noun(f)", sample: "Enciendo la lámpara de la mesa." },
  { id: 783, es: "cortina", en: "curtain", pos: "noun(f)", sample: "Cierro las cortinas por la noche." },
  { id: 784, es: "cuadro", en: "picture; painting", pos: "noun(m)", sample: "Hay un cuadro en la pared." },
  { id: 785, es: "espejo", en: "mirror", pos: "noun(m)", sample: "Me miro en el espejo." },
  { id: 786, es: "florero", en: "vase", pos: "noun(m)", sample: "Las flores están en el florero." },
  { id: 787, es: "planta", en: "plant; floor (level)", pos: "noun(f)", sample: "Hay una planta verde en el salón." },
  { id: 788, es: "vecino", en: "neighbor (male)", pos: "noun(m)", sample: "Mi vecino es muy simpático." },
  { id: 789, es: "vecina", en: "neighbor (female)", pos: "noun(f)", sample: "La vecina saluda siempre." },
  { id: 790, es: "barrio", en: "neighborhood", pos: "noun(m)", sample: "Nuestro barrio es tranquilo." },

  { id: 791, es: "ciudad", en: "city", pos: "noun(f)", sample: "La ciudad tiene muchos parques." },
  { id: 792, es: "centro", en: "center; downtown", pos: "noun(m)", sample: "Vivimos cerca del centro." },
  { id: 793, es: "afueras", en: "outskirts", pos: "noun(f,pl)", sample: "Viven en las afueras de la ciudad." },
  { id: 794, es: "parada", en: "stop (bus etc.)", pos: "noun(f)", sample: "La parada de autobús está cerca." },
  { id: 795, es: "estación", en: "station", pos: "noun(f)", sample: "La estación de tren está lejos." },
  { id: 796, es: "cruzar", en: "to cross", pos: "verb", sample: "Cruzamos la calle con cuidado." },
  { id: 797, es: "girar", en: "to turn", pos: "verb", sample: "Gira a la izquierda en el semáforo." },
  { id: 798, es: "seguir recto", en: "to go straight on", pos: "verb", sample: "Sigue recto hasta la plaza." },
  { id: 799, es: "estar perdido", en: "to be lost", pos: "verb", sample: "Estoy perdido, ¿me ayudas?" },
  { id: 800, es: "encontrar el camino", en: "to find the way", pos: "verb", sample: "Finalmente encontramos el camino correcto." },

  { id: 801, es: "familia", en: "family", pos: "noun(f)", sample: "Mi familia es muy grande y unida." },
  { id: 802, es: "padre", en: "father", pos: "noun(m)", sample: "Mi padre cocina muy bien los domingos." },
  { id: 803, es: "madre", en: "mother", pos: "noun(f)", sample: "Mi madre siempre me escucha con paciencia." },
  { id: 804, es: "hijo", en: "son", pos: "noun(m)", sample: "Su hijo juega al fútbol todos los sábados." },
  { id: 805, es: "hija", en: "daughter", pos: "noun(f)", sample: "Su hija estudia medicina en la universidad." },
  { id: 806, es: "hermano", en: "brother", pos: "noun(m)", sample: "Tengo un hermano menor muy divertido." },
  { id: 807, es: "hermana", en: "sister", pos: "noun(f)", sample: "Mi hermana trabaja en una empresa de diseño." },
  { id: 808, es: "abuelo", en: "grandfather", pos: "noun(m)", sample: "Mi abuelo me cuenta historias de su juventud." },
  { id: 809, es: "abuela", en: "grandmother", pos: "noun(f)", sample: "Mi abuela prepara un café delicioso." },
  { id: 810, es: "tío", en: "uncle", pos: "noun(m)", sample: "Mi tío vive en otra ciudad." },
  { id: 811, es: "tía", en: "aunt", pos: "noun(f)", sample: "Mi tía nos invita a comer los fines de semana." },
  { id: 812, es: "primo", en: "cousin (male)", pos: "noun(m)", sample: "Mi primo y yo estudiamos en la misma escuela." },
  { id: 813, es: "prima", en: "cousin (female)", pos: "noun(f)", sample: "Mi prima toca el piano muy bien." },
  { id: 814, es: "sobrino", en: "nephew", pos: "noun(m)", sample: "Voy al parque con mi sobrino cada domingo." },
  { id: 815, es: "sobrina", en: "niece", pos: "noun(f)", sample: "Mi sobrina dibuja animales todo el día." },
  { id: 816, es: "pareja", en: "partner", pos: "noun(f)", sample: "Mi pareja y yo viajamos juntos en verano." },
  { id: 817, es: "esposo", en: "husband", pos: "noun(m)", sample: "Su esposo llega tarde del trabajo." },
  { id: 818, es: "esposa", en: "wife", pos: "noun(f)", sample: "Su esposa estudia español en su tiempo libre." },
  { id: 819, es: "novio", en: "boyfriend", pos: "noun(m)", sample: "Mi novio trabaja en un restaurante." },
  { id: 820, es: "novia", en: "girlfriend; bride", pos: "noun(f)", sample: "Su novia es muy simpática y creativa." },
  { id: 821, es: "hijos", en: "children (one's own)", pos: "noun(m,pl)", sample: "Tienen dos hijos que van al colegio." },
  { id: 822, es: "padres", en: "parents", pos: "noun(m,pl)", sample: "Mis padres viven cerca de aquí." },
  { id: 823, es: "familia política", en: "in-laws", pos: "noun(f)", sample: "Me llevo muy bien con mi familia política." },
  { id: 824, es: "gemelos", en: "twins", pos: "noun(m,pl)", sample: "Los gemelos se visten siempre igual." },
  { id: 825, es: "madrastra", en: "stepmother", pos: "noun(f)", sample: "Se lleva bien con su madrastra." },
  { id: 826, es: "padrastro", en: "stepfather", pos: "noun(m)", sample: "Su padrastro es muy amable con todos." },
  { id: 827, es: "yerno", en: "son-in-law", pos: "noun(m)", sample: "Su yerno los visita cada fin de semana." },
  { id: 828, es: "nuera", en: "daughter-in-law", pos: "noun(f)", sample: "Su nuera habla tres idiomas." },
  { id: 829, es: "suegro", en: "father-in-law", pos: "noun(m)", sample: "Mi suegro juega al ajedrez conmigo." },
  { id: 830, es: "suegra", en: "mother-in-law", pos: "noun(f)", sample: "Mi suegra cocina muy bien la paella." },

  // Partes del cuerpo 831–860
  { id: 831, es: "cabeza", en: "head", pos: "noun(f)", sample: "Me duele la cabeza después de estudiar tanto." },
  { id: 832, es: "cara", en: "face", pos: "noun(f)", sample: "Ella tiene una cara muy sonriente." },
  { id: 833, es: "ojo", en: "eye", pos: "noun(m)", sample: "Cierra un ojo para hacer la foto." },
  { id: 834, es: "nariz", en: "nose", pos: "noun(f)", sample: "Tiene la nariz un poco roja por el frío." },
  { id: 835, es: "boca", en: "mouth", pos: "noun(f)", sample: "No hables con la boca llena, por favor." },
  { id: 836, es: "oreja", en: "ear", pos: "noun(f)", sample: "Me susurró algo al oído, cerca de la oreja." },
  { id: 837, es: "mano", en: "hand", pos: "noun(f)", sample: "Lávate la mano antes de comer." },
  { id: 838, es: "brazo", en: "arm", pos: "noun(m)", sample: "Levanta el brazo si tienes una pregunta." },
  { id: 839, es: "pierna", en: "leg", pos: "noun(f)", sample: "Se hizo daño en la pierna jugando al fútbol." },
  { id: 840, es: "pie", en: "foot", pos: "noun(m)", sample: "Me duelen los pies después de caminar tanto." },
  { id: 841, es: "espalda", en: "back", pos: "noun(f)", sample: "Tengo dolor de espalda por estar sentado." },
  { id: 842, es: "hombro", en: "shoulder", pos: "noun(m)", sample: "Me masajeó el hombro porque estaba tenso." },
  { id: 843, es: "rodilla", en: "knee", pos: "noun(f)", sample: "Se cayó y se lastimó la rodilla." },
  { id: 844, es: "codo", en: "elbow", pos: "noun(m)", sample: "Apoya el codo en la mesa con cuidado." },
  { id: 845, es: "diente", en: "tooth", pos: "noun(m)", sample: "Tengo que ir al dentista por un diente." },
  { id: 846, es: "lengua", en: "tongue", pos: "noun(f)", sample: "Me quemé la lengua con el café caliente." },
  { id: 847, es: "pelo", en: "hair", pos: "noun(m)", sample: "Se peina el pelo todas las mañanas." },
  { id: 848, es: "estómago", en: "stomach", pos: "noun(m)", sample: "Después de comer tanto, me duele el estómago." },
  { id: 849, es: "corazón", en: "heart", pos: "noun(m)", sample: "Mi corazón late muy rápido cuando corro." },
  { id: 850, es: "cintura", en: "waist", pos: "noun(f)", sample: "Se puso un cinturón en la cintura." },
  { id: 851, es: "muñeca", en: "wrist", pos: "noun(f)", sample: "Me duele la muñeca por usar mucho el ratón." },
  { id: 852, es: "dedo", en: "finger", pos: "noun(m)", sample: "Me corté un dedo al cocinar." },
  { id: 853, es: "uña", en: "nail", pos: "noun(f)", sample: "Ella se pinta las uñas de color rojo." },
  { id: 854, es: "pecho", en: "chest", pos: "noun(m)", sample: "Siente presión en el pecho cuando hace ejercicio." },
  { id: 855, es: "cadera", en: "hip", pos: "noun(f)", sample: "Le duele la cadera al caminar." },
  { id: 856, es: "cerebro", en: "brain", pos: "noun(m)", sample: "El cerebro controla todo nuestro cuerpo." },
  { id: 857, es: "pulmón", en: "lung", pos: "noun(m)", sample: "Fumar daña el pulmón y la salud." },
  { id: 858, es: "sangre", en: "blood", pos: "noun(f)", sample: "La sangre transporta oxígeno por el cuerpo." },
  { id: 859, es: "hueso", en: "bone", pos: "noun(m)", sample: "Se rompió un hueso del brazo." },
  { id: 860, es: "piel", en: "skin", pos: "noun(f)", sample: "En verano es importante cuidar la piel." },

  // Sentimientos y carácter 861–890
  { id: 861, es: "alegre", en: "cheerful", pos: "adj", sample: "Ella siempre está alegre por las mañanas." },
  { id: 862, es: "triste", en: "sad", pos: "adj", sample: "Hoy está triste porque extraña a su familia." },
  { id: 863, es: "nervioso", en: "nervous (masc.)", pos: "adj", sample: "Estoy nervioso antes del examen." },
  { id: 864, es: "nerviosa", en: "nervous (fem.)", pos: "adj", sample: "Ella se siente nerviosa antes de hablar en público." },
  { id: 865, es: "contento", en: "happy; glad (masc.)", pos: "adj", sample: "Estoy muy contento con los resultados." },
  { id: 866, es: "contenta", en: "happy; glad (fem.)", pos: "adj", sample: "Ella está contenta con su nuevo trabajo." },
  { id: 867, es: "cansado", en: "tired (masc.)", pos: "adj", sample: "Estoy cansado después de correr tanto." },
  { id: 868, es: "cansada", en: "tired (fem.)", pos: "adj", sample: "Estoy muy cansada y quiero dormir." },
  { id: 869, es: "enfadado", en: "angry (masc.)", pos: "adj", sample: "Él está enfadado porque perdió el tren." },
  { id: 870, es: "enfadada", en: "angry (fem.)", pos: "adj", sample: "Ella está enfadada con su compañero." },
  { id: 871, es: "abierto", en: "open-minded (masc.)", pos: "adj", sample: "Es muy abierto y acepta opiniones diferentes." },
  { id: 872, es: "cerrado", en: "closed; narrow-minded (masc.)", pos: "adj", sample: "Es un poco cerrado y no quiere cambiar." },
  { id: 873, es: "simpático", en: "nice; friendly (masc.)", pos: "adj", sample: "El profesor es muy simpático con los alumnos." },
  { id: 874, es: "simpática", en: "nice; friendly (fem.)", pos: "adj", sample: "La camarera es muy simpática y atenta." },
  { id: 875, es: "antipático", en: "unfriendly (masc.)", pos: "adj", sample: "El vecino parece un poco antipático." },
  { id: 876, es: "antipática", en: "unfriendly (fem.)", pos: "adj", sample: "Su jefa es bastante antipática." },
  { id: 877, es: "tímido", en: "shy (masc.)", pos: "adj", sample: "El niño es tímido y habla poco." },
  { id: 878, es: "tímida", en: "shy (fem.)", pos: "adj", sample: "La estudiante es tímida pero muy amable." },
  { id: 879, es: "valiente", en: "brave", pos: "adj", sample: "Fue muy valiente al decir la verdad." },
  { id: 880, es: "miedoso", en: "fearful (masc.)", pos: "adj", sample: "Es miedoso y no mira películas de terror." },
  { id: 881, es: "miedosa", en: "fearful (fem.)", pos: "adj", sample: "Ella es muy miedosa con los insectos." },
  { id: 882, es: "optimista", en: "optimistic", pos: "adj", sample: "Siempre es optimista incluso en momentos difíciles." },
  { id: 883, es: "pesimista", en: "pessimistic", pos: "adj", sample: "Él es pesimista y piensa que todo saldrá mal." },
  { id: 884, es: "sincero", en: "honest (masc.)", pos: "adj", sample: "Es muy sincero y dice lo que piensa." },
  { id: 885, es: "sincera", en: "honest (fem.)", pos: "adj", sample: "Ella es sincera y no miente nunca." },
  { id: 886, es: "mentiroso", en: "lying; dishonest (masc.)", pos: "adj", sample: "No confío en él porque es mentiroso." },
  { id: 887, es: "mentirosa", en: "lying; dishonest (fem.)", pos: "adj", sample: "Dicen que es mentirosa y exagera todo." },
  { id: 888, es: "tranquilo", en: "calm (masc.)", pos: "adj", sample: "Es muy tranquilo y casi nunca se enfada." },
  { id: 889, es: "paciente", en: "patient", pos: "adj", sample: "La profesora es muy paciente con los niños." },
  { id: 890, es: "impaciente", en: "impatient", pos: "adj", sample: "Soy impaciente y no me gusta esperar mucho." },

  // Verbos frecuentes 891–920
  { id: 891, es: "dormir", en: "to sleep", pos: "verb", sample: "Quiero dormir ocho horas esta noche." },
  { id: 892, es: "despertar", en: "to wake (someone) up", pos: "verb", sample: "Tengo que despertar a mi hermano a las siete." },
  { id: 893, es: "acostarse", en: "to go to bed", pos: "verb", sample: "Suelo acostarme antes de la medianoche." },
  { id: 894, es: "soñar", en: "to dream", pos: "verb", sample: "Me gusta soñar con viajar por el mundo." },
  { id: 895, es: "desayunar", en: "to have breakfast", pos: "verb", sample: "Prefiero desayunar café con pan tostado." },
  { id: 896, es: "almorzar", en: "to have lunch", pos: "verb", sample: "Vamos a almorzar juntos en el restaurante." },
  { id: 897, es: "cenar", en: "to have dinner", pos: "verb", sample: "Hoy vamos a cenar con unos amigos." },
  { id: 898, es: "beber", en: "to drink", pos: "verb", sample: "Debes beber más agua durante el día." },
  { id: 899, es: "comer", en: "to eat", pos: "verb", sample: "Vamos a comer pasta esta noche." },
  { id: 900, es: "estudiar", en: "to study", pos: "verb", sample: "Tengo que estudiar para el examen de mañana." },
  { id: 901, es: "trabajar", en: "to work", pos: "verb", sample: "Ella prefiere trabajar desde casa." },
  { id: 902, es: "descansar", en: "to rest", pos: "verb", sample: "Necesito descansar un rato después de correr." },
  { id: 903, es: "caminar", en: "to walk", pos: "verb", sample: "Me gusta caminar por el parque." },
  { id: 904, es: "correr", en: "to run", pos: "verb", sample: "Suele correr cada mañana antes de trabajar." },
  { id: 905, es: "llamar", en: "to call", pos: "verb", sample: "Voy a llamar a mi amigo esta noche." },
  { id: 906, es: "contestar", en: "to answer", pos: "verb", sample: "Por favor, contesta al teléfono." },
  { id: 907, es: "preguntar", en: "to ask", pos: "verb", sample: "Puedes preguntar si no entiendes algo." },
  { id: 908, es: "explicar", en: "to explain", pos: "verb", sample: "El profesor va a explicar la gramática." },
  { id: 909, es: "escuchar", en: "to listen", pos: "verb", sample: "Debes escuchar con atención en clase." },
  { id: 910, es: "mirar", en: "to look at", pos: "verb", sample: "Vamos a mirar una película esta noche." },
  { id: 911, es: "ver", en: "to see", pos: "verb", sample: "Quiero ver el mar este verano." },
  { id: 912, es: "esperar", en: "to wait; to hope", pos: "verb", sample: "Tenemos que esperar el autobús cinco minutos." },
  { id: 913, es: "buscar", en: "to look for", pos: "verb", sample: "Voy a buscar mis llaves en la mochila." },
  { id: 914, es: "encontrar", en: "to find", pos: "verb", sample: "No puedo encontrar mi teléfono." },
  { id: 915, es: "abrir", en: "to open", pos: "verb", sample: "¿Puedes abrir la ventana, por favor?" },
  { id: 916, es: "cerrar", en: "to close", pos: "verb", sample: "Es hora de cerrar la puerta de la tienda." },
  { id: 917, es: "entrar", en: "to enter", pos: "verb", sample: "No se puede entrar sin permiso." },
  { id: 918, es: "salir", en: "to go out", pos: "verb", sample: "Vamos a salir a cenar esta noche." },
  { id: 919, es: "subir", en: "to go up", pos: "verb", sample: "Tenemos que subir las escaleras hasta el tercer piso." },
  { id: 920, es: "bajar", en: "to go down", pos: "verb", sample: "Puedes bajar del autobús en la próxima parada." },

  // Lugares de la ciudad 921–950
  { id: 921, es: "tienda", en: "shop", pos: "noun(f)", sample: "Voy a la tienda a comprar pan." },
  { id: 922, es: "supermercado", en: "supermarket", pos: "noun(m)", sample: "El supermercado abre a las nueve." },
  { id: 923, es: "cafetería", en: "café", pos: "noun(f)", sample: "Nos vemos en la cafetería de la esquina." },
  { id: 924, es: "restaurante", en: "restaurant", pos: "noun(m)", sample: "Este restaurante tiene comida muy rica." },
  { id: 925, es: "parque", en: "park", pos: "noun(m)", sample: "Los niños juegan en el parque." },
  { id: 926, es: "plaza", en: "square", pos: "noun(f)", sample: "La plaza del centro siempre está llena de gente." },
  { id: 927, es: "cine", en: "cinema", pos: "noun(m)", sample: "Vamos al cine a ver una película." },
  { id: 928, es: "teatro", en: "theatre", pos: "noun(m)", sample: "En el teatro presentan una obra nueva." },
  { id: 929, es: "ayuntamiento", en: "town hall", pos: "noun(m)", sample: "El ayuntamiento está frente a la iglesia." },
  { id: 930, es: "oficina de correos", en: "post office", pos: "noun(f)", sample: "Tengo que ir a la oficina de correos para enviar una carta." },
  { id: 931, es: "estación de tren", en: "train station", pos: "noun(f)", sample: "La estación de tren está cerca del centro." },
  { id: 932, es: "parada de autobús", en: "bus stop", pos: "noun(f)", sample: "La parada de autobús está en la esquina." },
  { id: 933, es: "aeropuerto", en: "airport", pos: "noun(m)", sample: "Llegamos al aeropuerto dos horas antes del vuelo." },
  { id: 934, es: "hospital", en: "hospital", pos: "noun(m)", sample: "El hospital está abierto las veinticuatro horas." },
  { id: 935, es: "clínica", en: "clinic", pos: "noun(f)", sample: "Voy a la clínica para una revisión médica." },
  { id: 936, es: "farmacia de guardia", en: "24-hour pharmacy", pos: "noun(f)", sample: "Buscamos una farmacia de guardia por la noche." },
  { id: 937, es: "oficina", en: "office", pos: "noun(f)", sample: "Trabajo en una oficina en el centro de la ciudad." },
  { id: 938, es: "universidad", en: "university", pos: "noun(f)", sample: "La universidad tiene muchos estudiantes extranjeros." },
  { id: 939, es: "instituto", en: "high school", pos: "noun(m)", sample: "Mi hermana estudia en un instituto público." },
  { id: 940, es: "colegio", en: "school", pos: "noun(m)", sample: "El colegio de mi barrio es pequeño." },
  { id: 941, es: "gimnasio", en: "gym", pos: "noun(m)", sample: "Voy al gimnasio tres veces a la semana." },
  { id: 942, es: "estadio", en: "stadium", pos: "noun(m)", sample: "El partido será en el estadio nacional." },
  { id: 943, es: "piscina", en: "swimming pool", pos: "noun(f)", sample: "En verano vamos a la piscina municipal." },
  { id: 944, es: "biblioteca pública", en: "public library", pos: "noun(f)", sample: "Estudio en la biblioteca pública porque es tranquila." },
  { id: 945, es: "museo de arte", en: "art museum", pos: "noun(m)", sample: "Visitamos el museo de arte el sábado pasado." },
  { id: 946, es: "centro comercial grande", en: "large shopping mall", pos: "noun(m)", sample: "Hay un centro comercial grande cerca de aquí." },
  { id: 947, es: "zona peatonal", en: "pedestrian area", pos: "noun(f)", sample: "La zona peatonal está llena de tiendas y cafés." },
  { id: 948, es: "barrio antiguo", en: "old town", pos: "noun(m)", sample: "Nos gusta pasear por el barrio antiguo." },
  { id: 949, es: "puerto", en: "port; harbor", pos: "noun(m)", sample: "El barco sale del puerto a las ocho." },
  { id: 950, es: "cementerio", en: "cemetery", pos: "noun(m)", sample: "El cementerio está en las afueras de la ciudad." },

  // Tecnología básica 951–975
  { id: 951, es: "ordenador portátil", en: "laptop", pos: "noun(m)", sample: "Trabajo con mi ordenador portátil en la cafetería." },
  { id: 952, es: "tableta", en: "tablet", pos: "noun(f)", sample: "Leo libros en la tableta antes de dormir." },
  { id: 953, es: "auriculares", en: "headphones", pos: "noun(m,pl)", sample: "Uso auriculares para escuchar música en el metro." },
  { id: 954, es: "altavoz", en: "speaker", pos: "noun(m)", sample: "El altavoz no funciona bien, suena muy bajo." },
  { id: 955, es: "cargador", en: "charger", pos: "noun(m)", sample: "Olvidé el cargador del móvil en casa." },
  { id: 956, es: "aplicación", en: "app; application", pos: "noun(f)", sample: "Descargué una aplicación para aprender idiomas." },
  { id: 957, es: "usuario", en: "user", pos: "noun(m)", sample: "Cada usuario tiene una contraseña diferente." },
  { id: 958, es: "perfil", en: "profile", pos: "noun(m)", sample: "Actualicé mi foto de perfil en la red social." },
  { id: 959, es: "comentario", en: "comment", pos: "noun(m)", sample: "Dejó un comentario muy positivo en el vídeo." },
  { id: 960, es: "cuenta de usuario", en: "user account", pos: "noun(f)", sample: "No puedo entrar en mi cuenta de usuario." },
  { id: 961, es: "enlace", en: "link", pos: "noun(m)", sample: "Te envío el enlace por correo electrónico." },
  { id: 962, es: "navegador", en: "browser", pos: "noun(m)", sample: "Uso otro navegador porque es más rápido." },
  { id: 963, es: "contraseña segura", en: "secure password", pos: "noun(f)", sample: "Es importante tener una contraseña segura." },
  { id: 964, es: "videojuego", en: "video game", pos: "noun(m)", sample: "Este videojuego es muy popular entre los jóvenes." },
  { id: 965, es: "mensaje de texto", en: "text message", pos: "noun(m)", sample: "Te envío un mensaje de texto cuando llegue." },
  { id: 966, es: "correo electrónico", en: "email", pos: "noun(m)", sample: "Recibí tu correo electrónico esta mañana." },
  { id: 967, es: "red social", en: "social network", pos: "noun(f)", sample: "Paso demasiado tiempo en la red social." },
  { id: 968, es: "archivo adjunto", en: "attachment", pos: "noun(m)", sample: "No olvides abrir el archivo adjunto del correo." },
  { id: 969, es: "memoria USB", en: "USB drive", pos: "noun(f)", sample: "Guardé los documentos en una memoria USB." },
  { id: 970, es: "mandar un mensaje", en: "to send a message", pos: "verb", sample: "Voy a mandar un mensaje al grupo." },
  { id: 971, es: "subir una foto", en: "to upload a photo", pos: "verb", sample: "Quiero subir una foto a mi perfil." },
  { id: 972, es: "descargar un archivo", en: "to download a file", pos: "verb", sample: "Tardo mucho en descargar un archivo tan grande." },
  { id: 973, es: "hacer clic", en: "to click", pos: "verb", sample: "Tienes que hacer clic en el botón azul." },
  { id: 974, es: "activar", en: "to activate", pos: "verb", sample: "Debes activar tu cuenta con este enlace." },
  { id: 975, es: "desactivar", en: "to deactivate", pos: "verb", sample: "Puedes desactivar las notificaciones cuando quieras." },

  // Naturaleza 976–1000
  { id: 976, es: "naturaleza", en: "nature", pos: "noun(f)", sample: "Me gusta pasar tiempo en la naturaleza." },
  { id: 977, es: "paisaje", en: "landscape", pos: "noun(m)", sample: "El paisaje de la montaña es impresionante." },
  { id: 978, es: "valle", en: "valley", pos: "noun(m)", sample: "El río pasa por un valle muy profundo." },
  { id: 979, es: "colina", en: "hill", pos: "noun(f)", sample: "Subimos la colina para ver la ciudad desde arriba." },
  { id: 980, es: "cascada", en: "waterfall", pos: "noun(f)", sample: "La cascada es muy alta y hermosa." },
  { id: 981, es: "playa", en: "beach", pos: "noun(f)", sample: "En verano vamos a la playa todos los días." },
  { id: 982, es: "desierto", en: "desert", pos: "noun(m)", sample: "El desierto es muy seco y caliente." },
  { id: 983, es: "selva", en: "jungle", pos: "noun(f)", sample: "La selva está llena de animales y plantas." },
  { id: 984, es: "océano", en: "ocean", pos: "noun(m)", sample: "El océano es profundo y misterioso." },
  { id: 985, es: "mar", en: "sea", pos: "noun(m)", sample: "Me gusta nadar en el mar por la mañana." },
  { id: 986, es: "orilla", en: "shore", pos: "noun(f)", sample: "Caminamos por la orilla del río al atardecer." },
  { id: 987, es: "isla pequeña", en: "small island", pos: "noun(f)", sample: "Nos alojamos en una isla pequeña y tranquila." },
  { id: 988, es: "roca", en: "rock", pos: "noun(f)", sample: "Hay una roca grande en medio del camino." },
  { id: 989, es: "arena", en: "sand", pos: "noun(f)", sample: "La arena de esta playa es muy fina." },
  { id: 990, es: "hoja", en: "leaf", pos: "noun(f)", sample: "La hoja del árbol cayó al suelo." },
  { id: 991, es: "rama", en: "branch", pos: "noun(f)", sample: "El pájaro se sentó en una rama." },
  { id: 992, es: "raíz", en: "root", pos: "noun(f)", sample: "Las raíces del árbol son muy profundas." },
  { id: 993, es: "arbusto", en: "bush", pos: "noun(m)", sample: "El gato se escondió detrás del arbusto." },
  { id: 994, es: "prado", en: "meadow", pos: "noun(m)", sample: "Las vacas comen en el prado verde." },
  { id: 995, es: "sendero", en: "path", pos: "noun(m)", sample: "Seguimos el sendero hasta el lago." },
  { id: 996, es: "cabaña", en: "cabin", pos: "noun(f)", sample: "Pasamos la noche en una cabaña de madera." },
  { id: 997, es: "granero", en: "barn", pos: "noun(m)", sample: "El granero está lleno de heno." },
  { id: 998, es: "cielo estrellado", en: "starry sky", pos: "noun(m)", sample: "Miramos el cielo estrellado en silencio." },
  { id: 999, es: "amanecer", en: "sunrise", pos: "noun(m)", sample: "El amanecer en la playa es muy bonito." },
  { id: 1000, es: "atardecer", en: "sunset", pos: "noun(m)", sample: "El atardecer pinta el cielo de colores." }
];

export { VOCAB_ES };
