// vocab-n3.js — JLPT N3 단어장
// Phase 1 구조 작업용 샘플 데이터 (Phase 3에서 전체 데이터로 교체 예정)
// id 범위: 10001~19999 (배포된 id는 변경·재사용 금지)

const VOCAB_N3 = [
  {
    id: 10001,
    jpKana: "かいけつ",
    jpKanji: "解決",
    krMeaning: "해결",
    note: "",
    example: "問題はもう【解決】しました。",
  },
  {
    id: 10002,
    jpKana: "かんきょう",
    jpKanji: "環境",
    krMeaning: "환경",
    note: "",
    example: "この町は【環境】がいいです。",
  },
  {
    id: 10003,
    jpKana: "かんさつ",
    jpKanji: "観察",
    krMeaning: "관찰",
    note: "",
    example: "毎日花を【観察】しています。",
  },
  {
    id: 10004,
    jpKana: "がまん",
    jpKanji: "我慢",
    krMeaning: "참음. 인내",
    note: "",
    example: "痛くても【我慢】しました。",
  },
  {
    id: 10005,
    jpKana: "きろく",
    jpKanji: "記録",
    krMeaning: "기록",
    note: "",
    example: "ノートに【記録】しています。",
  },
  {
    id: 10006,
    jpKana: "きんちょう",
    jpKanji: "緊張",
    krMeaning: "긴장",
    note: "",
    example: "試験の前は【緊張】します。",
  },
  {
    id: 10007,
    jpKana: "くんれん",
    jpKanji: "訓練",
    krMeaning: "훈련",
    note: "",
    example: "犬の【訓練】をしています。",
  },
  {
    id: 10008,
    jpKana: "けんさ",
    jpKanji: "検査",
    krMeaning: "검사",
    note: "",
    example: "病院で【検査】を受けました。",
  },
  {
    id: 10009,
    jpKana: "こうか",
    jpKanji: "効果",
    krMeaning: "효과",
    note: "",
    example: "この薬は【効果】があります。",
  },
  {
    id: 10010,
    jpKana: "こんざつ",
    jpKanji: "混雑",
    krMeaning: "혼잡",
    note: "",
    example: "朝の駅は【混雑】しています。",
  },
  {
    id: 10011,
    jpKana: "しょうじきだ",
    jpKanji: "正直だ",
    krMeaning: "정직하다. 솔직하다",
    note: "",
    example: "彼はとても【正直】な人です。",
  },
  {
    id: 10012,
    jpKana: "そうぞう",
    jpKanji: "想像",
    krMeaning: "상상",
    note: "",
    example: "十年後の生活を【想像】します。",
  },
  {
    id: 10013,
    jpKana: "たんじゅんだ",
    jpKanji: "単純だ",
    krMeaning: "단순하다",
    note: "",
    example: "これは【単純】な問題です。",
  },
  {
    id: 10014,
    jpKana: "ちょうさ",
    jpKanji: "調査",
    krMeaning: "조사",
    note: "",
    example: "事故の原因を【調査】します。",
  },
  {
    id: 10015,
    jpKana: "ほんやく",
    jpKanji: "翻訳",
    krMeaning: "번역",
    note: "",
    example: "英語の本を【翻訳】しました。",
  },
];
