// vocab-n2.js — JLPT N2 단어장
// Phase 1 구조 작업용 샘플 데이터 (Phase 3에서 전체 데이터로 교체 예정)
// id 범위: 20001~29999 (배포된 id는 변경·재사용 금지)

const VOCAB_N2 = [
  {
    id: 20001,
    jpKana: "あんいだ",
    jpKanji: "安易だ",
    krMeaning: "안이하다. 손쉽다",
    note: "",
    example: "【安易】な考えは危ないです。",
  },
  {
    id: 20002,
    jpKana: "いじ",
    jpKanji: "維持",
    krMeaning: "유지",
    note: "",
    example: "健康を【維持】したいです。",
  },
  {
    id: 20003,
    jpKana: "いっち",
    jpKanji: "一致",
    krMeaning: "일치",
    note: "",
    example: "二人の意見が【一致】しました。",
  },
  {
    id: 20004,
    jpKana: "えんぜつ",
    jpKanji: "演説",
    krMeaning: "연설",
    note: "",
    example: "彼は長い【演説】をしました。",
  },
  {
    id: 20005,
    jpKana: "かくちょう",
    jpKanji: "拡張",
    krMeaning: "확장",
    note: "",
    example: "店を【拡張】する予定です。",
  },
  {
    id: 20006,
    jpKana: "かんそく",
    jpKanji: "観測",
    krMeaning: "관측",
    note: "",
    example: "星の【観測】が趣味です。",
  },
  {
    id: 20007,
    jpKana: "きじゅん",
    jpKanji: "基準",
    krMeaning: "기준",
    note: "",
    example: "合格の【基準】は何ですか。",
  },
  {
    id: 20008,
    jpKana: "きちょうだ",
    jpKanji: "貴重だ",
    krMeaning: "귀중하다. 소중하다",
    note: "",
    example: "これは【貴重】な経験です。",
  },
  {
    id: 20009,
    jpKana: "さくじょ",
    jpKanji: "削除",
    krMeaning: "삭제",
    note: "",
    example: "古いデータを【削除】しました。",
  },
  {
    id: 20010,
    jpKana: "だきょう",
    jpKanji: "妥協",
    krMeaning: "타협",
    note: "",
    example: "最後まで【妥協】しませんでした。",
  },
  {
    id: 20011,
    jpKana: "ちゅうしょう",
    jpKanji: "抽象",
    krMeaning: "추상",
    note: "",
    example: "この絵は【抽象】的で難しいです。",
  },
  {
    id: 20012,
    jpKana: "むじゅん",
    jpKanji: "矛盾",
    krMeaning: "모순",
    note: "",
    example: "彼の話は【矛盾】しています。",
  },
  {
    id: 20013,
    jpKana: "ゆだん",
    jpKanji: "油断",
    krMeaning: "방심. 부주의",
    note: "",
    example: "最後まで【油断】しないでください。",
  },
  {
    id: 20014,
    jpKana: "よゆう",
    jpKanji: "余裕",
    krMeaning: "여유",
    note: "",
    example: "時間に【余裕】がありません。",
  },
  {
    id: 20015,
    jpKana: "ろんそう",
    jpKanji: "論争",
    krMeaning: "논쟁",
    note: "",
    example: "その問題で【論争】が起きました。",
  },
];
