// vocab-n1.js — JLPT N1 단어장
// Phase 1 구조 작업용 샘플 데이터 (Phase 3에서 전체 데이터로 교체 예정)
// id 범위: 30001~ (배포된 id는 변경·재사용 금지)

const VOCAB_N1 = [
  {
    id: 30001,
    jpKana: "あいまいだ",
    jpKanji: "曖昧だ",
    krMeaning: "애매하다. 모호하다",
    note: "",
    example: "彼の返事は【曖昧】でした。",
  },
  {
    id: 30002,
    jpKana: "かっとう",
    jpKanji: "葛藤",
    krMeaning: "갈등",
    note: "",
    example: "親と子の間に【葛藤】があります。",
  },
  {
    id: 30003,
    jpKana: "かんわ",
    jpKanji: "緩和",
    krMeaning: "완화",
    note: "",
    example: "規制が【緩和】されました。",
  },
  {
    id: 30004,
    jpKana: "かわせ",
    jpKanji: "為替",
    krMeaning: "환. 외환",
    note: "",
    example: "【為替】の変動に注意が必要です。",
  },
  {
    id: 30005,
    jpKana: "けねん",
    jpKanji: "懸念",
    krMeaning: "우려. 근심",
    note: "",
    example: "景気の悪化を【懸念】しています。",
  },
  {
    id: 30006,
    jpKana: "こうけん",
    jpKanji: "貢献",
    krMeaning: "공헌. 기여",
    note: "",
    example: "社会に【貢献】したいです。",
  },
  {
    id: 30007,
    jpKana: "さっとう",
    jpKanji: "殺到",
    krMeaning: "쇄도",
    note: "",
    example: "店に注文が【殺到】しました。",
  },
  {
    id: 30008,
    jpKana: "ざんてい",
    jpKanji: "暫定",
    krMeaning: "잠정",
    note: "",
    example: "これは【暫定】的な案です。",
  },
  {
    id: 30009,
    jpKana: "しゅし",
    jpKanji: "趣旨",
    krMeaning: "취지",
    note: "",
    example: "会議の【趣旨】を説明します。",
  },
  {
    id: 30010,
    jpKana: "はあく",
    jpKanji: "把握",
    krMeaning: "파악",
    note: "",
    example: "状況を正しく【把握】しています。",
  },
  {
    id: 30011,
    jpKana: "ぼうがい",
    jpKanji: "妨害",
    krMeaning: "방해",
    note: "",
    example: "営業を【妨害】してはいけません。",
  },
  {
    id: 30012,
    jpKana: "ぼうだいだ",
    jpKanji: "膨大だ",
    krMeaning: "방대하다",
    note: "",
    example: "【膨大】な資料を読みました。",
  },
  {
    id: 30013,
    jpKana: "ほうわ",
    jpKanji: "飽和",
    krMeaning: "포화",
    note: "",
    example: "この市場はもう【飽和】状態です。",
  },
  {
    id: 30014,
    jpKana: "よくせい",
    jpKanji: "抑制",
    krMeaning: "억제",
    note: "",
    example: "感情を【抑制】するのは大変です。",
  },
  {
    id: 30015,
    jpKana: "ろこつだ",
    jpKanji: "露骨だ",
    krMeaning: "노골적이다",
    note: "",
    example: "彼は【露骨】に嫌な顔をしました。",
  },
];
