const VOCAB_FR = [
  { id: 1, fr: "être", en: "to be", pos: "verb" },
  { id: 2, fr: "avoir", en: "to have", pos: "verb" },
  { id: 3, fr: "aller", en: "to go", pos: "verb" },
  { id: 4, fr: "faire", en: "to do; to make", pos: "verb" },
  { id: 5, fr: "dire", en: "to say; to tell", pos: "verb" },
  { id: 6, fr: "pouvoir", en: "can; to be able to", pos: "verb" },
  { id: 7, fr: "vouloir", en: "to want", pos: "verb" },
  { id: 8, fr: "devoir", en: "must; to have to; to owe", pos: "verb" },
  { id: 9, fr: "savoir", en: "to know (a fact; how to)", pos: "verb" },
  { id: 10, fr: "connaître", en: "to know (be familiar with)", pos: "verb" },
  { id: 11, fr: "venir", en: "to come", pos: "verb" },
  { id: 12, fr: "partir", en: "to leave; to depart", pos: "verb" },
  { id: 13, fr: "prendre", en: "to take", pos: "verb" },
  { id: 14, fr: "mettre", en: "to put; to put on", pos: "verb" },
  { id: 15, fr: "donner", en: "to give", pos: "verb" },
  { id: 16, fr: "trouver", en: "to find", pos: "verb" },
  { id: 17, fr: "chercher", en: "to look for; to search", pos: "verb" },
  { id: 18, fr: "penser", en: "to think", pos: "verb" },
  { id: 19, fr: "croire", en: "to believe", pos: "verb" },
  { id: 20, fr: "comprendre", en: "to understand", pos: "verb" },
  { id: 21, fr: "voir", en: "to see", pos: "verb" },
  { id: 22, fr: "regarder", en: "to watch; to look at", pos: "verb" },
  { id: 23, fr: "entendre", en: "to hear", pos: "verb" },
  { id: 24, fr: "écouter", en: "to listen", pos: "verb" },
  { id: 25, fr: "parler", en: "to speak; to talk", pos: "verb" },
  { id: 26, fr: "demander", en: "to ask (for; to)", pos: "verb" },
  { id: 27, fr: "répondre", en: "to answer; to reply", pos: "verb" },
  { id: 28, fr: "travailler", en: "to work", pos: "verb" },
  { id: 29, fr: "étudier", en: "to study", pos: "verb" },
  { id: 30, fr: "aimer", en: "to like; to love", pos: "verb" },
  { id: 31, fr: "adorer", en: "to adore; to love", pos: "verb" },
  { id: 32, fr: "détester", en: "to hate", pos: "verb" },
  { id: 33, fr: "manger", en: "to eat", pos: "verb" },
  { id: 34, fr: "boire", en: "to drink", pos: "verb" },
  { id: 35, fr: "vivre", en: "to live", pos: "verb" },
  { id: 36, fr: "habiter", en: "to live; to reside", pos: "verb" },
  { id: 37, fr: "arriver", en: "to arrive; to happen", pos: "verb" },
  { id: 38, fr: "rester", en: "to stay; to remain", pos: "verb" },
  { id: 39, fr: "sortir", en: "to go out; to take out", pos: "verb" },
  { id: 40, fr: "entrer", en: "to enter; to come in", pos: "verb" },
  { id: 41, fr: "revenir", en: "to come back", pos: "verb" },
  { id: 42, fr: "retourner", en: "to return; to go back", pos: "verb" },
  { id: 43, fr: "porter", en: "to carry; to wear", pos: "verb" },
  { id: 44, fr: "acheter", en: "to buy", pos: "verb" },
  { id: 45, fr: "payer", en: "to pay", pos: "verb" },
  { id: 46, fr: "coûter", en: "to cost", pos: "verb" },
  { id: 47, fr: "ouvrir", en: "to open", pos: "verb" },
  { id: 48, fr: "fermer", en: "to close; to shut", pos: "verb" },
  { id: 49, fr: "commencer", en: "to begin; to start", pos: "verb" },
  { id: 50, fr: "finir", en: "to finish; to end", pos: "verb" },
  { id: 51, fr: "attendre", en: "to wait for", pos: "verb" },
  { id: 52, fr: "utiliser", en: "to use", pos: "verb" },
  { id: 53, fr: "jouer", en: "to play", pos: "verb" },
  { id: 54, fr: "aider", en: "to help", pos: "verb" },
  { id: 55, fr: "rentrer", en: "to go back home; to return", pos: "verb" },
  { id: 56, fr: "tomber", en: "to fall", pos: "verb" },
  { id: 57, fr: "monter", en: "to go up; to climb", pos: "verb" },
  { id: 58, fr: "descendre", en: "to go down; to get off", pos: "verb" },
  { id: 59, fr: "se lever", en: "to get up", pos: "verb" },
  { id: 60, fr: "se coucher", en: "to go to bed", pos: "verb" },
  { id: 61, fr: "homme", en: "man", pos: "noun" },
  { id: 62, fr: "femme", en: "woman; wife", pos: "noun" },
  { id: 63, fr: "garçon", en: "boy", pos: "noun" },
  { id: 64, fr: "fille", en: "girl; daughter", pos: "noun" },
  { id: 65, fr: "enfant", en: "child", pos: "noun" },
  { id: 66, fr: "ami", en: "friend (male)", pos: "noun" },
  { id: 67, fr: "amie", en: "friend (female)", pos: "noun" },
  { id: 68, fr: "personne", en: "person", pos: "noun" },
  { id: 69, fr: "famille", en: "family", pos: "noun" },
  { id: 70, fr: "père", en: "father", pos: "noun" },
  { id: 71, fr: "mère", en: "mother", pos: "noun" },
  { id: 72, fr: "fils", en: "son", pos: "noun" },
  { id: 73, fr: "frère", en: "brother", pos: "noun" },
  { id: 74, fr: "soeur", en: "sister", pos: "noun" },
  { id: 75, fr: "grand-père", en: "grandfather", pos: "noun" },
  { id: 76, fr: "grand-mère", en: "grandmother", pos: "noun" },
  { id: 77, fr: "oncle", en: "uncle", pos: "noun" },
  { id: 78, fr: "tante", en: "aunt", pos: "noun" },
  { id: 79, fr: "cousin", en: "cousin (male)", pos: "noun" },
  { id: 80, fr: "cousine", en: "cousin (female)", pos: "noun" },
  { id: 81, fr: "mari", en: "husband", pos: "noun" },
  { id: 82, fr: "femme (épouse)", en: "wife", pos: "noun" },
  { id: 83, fr: "voisin", en: "neighbor (male)", pos: "noun" },
  { id: 84, fr: "voisine", en: "neighbor (female)", pos: "noun" },
  { id: 85, fr: "élève", en: "pupil; student", pos: "noun" },
  { id: 86, fr: "étudiant", en: "student (male)", pos: "noun" },
  { id: 87, fr: "étudiante", en: "student (female)", pos: "noun" },
  { id: 88, fr: "professeur", en: "teacher; professor", pos: "noun" },
  { id: 89, fr: "docteur", en: "doctor", pos: "noun" },
  { id: 90, fr: "client", en: "customer; client", pos: "noun" },
  { id: 91, fr: "maison", en: "house; home", pos: "noun" },
  { id: 92, fr: "appartement", en: "apartment; flat", pos: "noun" },
  { id: 93, fr: "chambre", en: "room; bedroom", pos: "noun" },
  { id: 94, fr: "salon", en: "living room; lounge", pos: "noun" },
  { id: 95, fr: "cuisine", en: "kitchen", pos: "noun" },
  { id: 96, fr: "salle de bain", en: "bathroom", pos: "noun" },
  { id: 97, fr: "école", en: "school", pos: "noun" },
  { id: 98, fr: "université", en: "university", pos: "noun" },
  { id: 99, fr: "bureau", en: "office; desk", pos: "noun" },
  { id: 100, fr: "magasin", en: "shop; store", pos: "noun" },
  { id: 101, fr: "supermarché", en: "supermarket", pos: "noun" },
  { id: 102, fr: "marché", en: "market", pos: "noun" },
  { id: 103, fr: "restaurant", en: "restaurant", pos: "noun" },
  { id: 104, fr: "café", en: "café; coffee shop", pos: "noun" },
  { id: 105, fr: "banque", en: "bank", pos: "noun" },
  { id: 106, fr: "hôpital", en: "hospital", pos: "noun" },
  { id: 107, fr: "pharmacie", en: "pharmacy", pos: "noun" },
  { id: 108, fr: "parc", en: "park", pos: "noun" },
  { id: 109, fr: "ville", en: "city; town", pos: "noun" },
  { id: 110, fr: "pays", en: "country (nation)", pos: "noun" },
  { id: 111, fr: "rue", en: "street", pos: "noun" },
  { id: 112, fr: "place", en: "square; place", pos: "noun" },
  { id: 113, fr: "gare", en: "train station", pos: "noun" },
  { id: 114, fr: "arrêt de bus", en: "bus stop", pos: "noun" },
  { id: 115, fr: "aéroport", en: "airport", pos: "noun" },
  { id: 116, fr: "mer", en: "sea", pos: "noun" },
  { id: 117, fr: "montagne", en: "mountain", pos: "noun" },
  { id: 118, fr: "campagne", en: "countryside", pos: "noun" },
  { id: 119, fr: "livre", en: "book", pos: "noun" },
  { id: 120, fr: "stylo", en: "pen", pos: "noun" },
  { id: 121, fr: "crayon", en: "pencil", pos: "noun" },
  { id: 122, fr: "papier", en: "paper", pos: "noun" },
  { id: 123, fr: "ordinateur", en: "computer", pos: "noun" },
  { id: 124, fr: "téléphone", en: "phone", pos: "noun" },
  { id: 125, fr: "table", en: "table", pos: "noun" },
  { id: 126, fr: "chaise", en: "chair", pos: "noun" },
  { id: 127, fr: "lit", en: "bed", pos: "noun" },
  { id: 128, fr: "voiture", en: "car", pos: "noun" },
  { id: 129, fr: "vélo", en: "bicycle", pos: "noun" },
  { id: 130, fr: "bus", en: "bus", pos: "noun" },
  { id: 131, fr: "métro", en: "subway; metro", pos: "noun" },
  { id: 132, fr: "train", en: "train", pos: "noun" },
  { id: 133, fr: "avion", en: "plane; airplane", pos: "noun" },
  { id: 134, fr: "clé", en: "key", pos: "noun" },
  { id: 135, fr: "sac", en: "bag", pos: "noun" },
  { id: 136, fr: "vêtement", en: "clothing; garment", pos: "noun" },
  { id: 137, fr: "chemise", en: "shirt", pos: "noun" },
  { id: 138, fr: "pantalon", en: "trousers; pants", pos: "noun" },
  { id: 139, fr: "robe", en: "dress", pos: "noun" },
  { id: 140, fr: "chaussure", en: "shoe", pos: "noun" },
  { id: 141, fr: "jour", en: "day", pos: "noun" },
  { id: 142, fr: "semaine", en: "week", pos: "noun" },
  { id: 143, fr: "mois", en: "month", pos: "noun" },
  { id: 144, fr: "année", en: "year", pos: "noun" },
  { id: 145, fr: "matin", en: "morning", pos: "noun" },
  { id: 146, fr: "après-midi", en: "afternoon", pos: "noun" },
  { id: 147, fr: "soir", en: "evening", pos: "noun" },
  { id: 148, fr: "nuit", en: "night", pos: "noun" },
  { id: 149, fr: "heure", en: "hour; time (o'clock)", pos: "noun" },
  { id: 150, fr: "temps", en: "time; weather", pos: "noun" },
  { id: 151, fr: "aujourd'hui", en: "today", pos: "adv" },
  { id: 152, fr: "demain", en: "tomorrow", pos: "adv" },
  { id: 153, fr: "hier", en: "yesterday", pos: "adv" },
  { id: 154, fr: "toujours", en: "always", pos: "adv" },
  { id: 155, fr: "souvent", en: "often", pos: "adv" },
  { id: 156, fr: "parfois", en: "sometimes", pos: "adv" },
  { id: 157, fr: "rarement", en: "rarely", pos: "adv" },
  { id: 158, fr: "jamais", en: "never", pos: "adv" },
  { id: 159, fr: "tôt", en: "early", pos: "adv" },
  { id: 160, fr: "tard", en: "late", pos: "adv" },
  { id: 161, fr: "froid", en: "cold", pos: "adj" },
  { id: 162, fr: "chaud", en: "hot; warm", pos: "adj" },
  { id: 163, fr: "beau", en: "beautiful; nice (weather)", pos: "adj" },
  { id: 164, fr: "mauvais", en: "bad", pos: "adj" },
  { id: 165, fr: "pluie", en: "rain", pos: "noun" },
  { id: 166, fr: "neige", en: "snow", pos: "noun" },
  { id: 167, fr: "soleil", en: "sun", pos: "noun" },
  { id: 168, fr: "vent", en: "wind", pos: "noun" },
  { id: 169, fr: "temps libre", en: "free time", pos: "noun" },
  { id: 170, fr: "vacances", en: "holidays; vacation", pos: "noun" },
  { id: 171, fr: "grand", en: "big; tall", pos: "adj" },
  { id: 172, fr: "petit", en: "small; little", pos: "adj" },
  { id: 173, fr: "long", en: "long", pos: "adj" },
  { id: 174, fr: "court", en: "short", pos: "adj" },
  { id: 175, fr: "jeune", en: "young", pos: "adj" },
  { id: 176, fr: "vieux", en: "old", pos: "adj" },
  { id: 177, fr: "nouveau", en: "new", pos: "adj" },
  { id: 178, fr: "vrai", en: "true; real", pos: "adj" },
  { id: 179, fr: "faux", en: "false; wrong", pos: "adj" },
  { id: 180, fr: "facile", en: "easy", pos: "adj" },
  { id: 181, fr: "difficile", en: "difficult", pos: "adj" },
  { id: 182, fr: "intéressant", en: "interesting", pos: "adj" },
  { id: 183, fr: "ennuyeux", en: "boring", pos: "adj" },
  { id: 184, fr: "cher", en: "expensive; dear", pos: "adj" },
  { id: 185, fr: "bon marché", en: "cheap; inexpensive", pos: "adj" },
  { id: 186, fr: "fort", en: "strong", pos: "adj" },
  { id: 187, fr: "faible", en: "weak", pos: "adj" },
  { id: 188, fr: "propre", en: "clean; own", pos: "adj" },
  { id: 189, fr: "sale", en: "dirty", pos: "adj" },
  { id: 190, fr: "content", en: "glad; happy", pos: "adj" },
  { id: 191, fr: "triste", en: "sad", pos: "adj" },
  { id: 192, fr: "fatigué", en: "tired", pos: "adj" },
  { id: 193, fr: "malade", en: "ill; sick", pos: "adj" },
  { id: 194, fr: "prêt", en: "ready", pos: "adj" },
  { id: 195, fr: "important", en: "important", pos: "adj" },
  { id: 196, fr: "beaucoup", en: "a lot; much; many", pos: "adv" },
  { id: 197, fr: "peu", en: "little; few", pos: "adv" },
  { id: 198, fr: "bien", en: "well", pos: "adv" },
  { id: 199, fr: "mal", en: "badly; poorly", pos: "adv" },
  { id: 200, fr: "très", en: "very", pos: "adv" },
  { id: 201, fr: "chat", en: "cat", pos: "noun" },
  { id: 202, fr: "chien", en: "dog", pos: "noun" },
  { id: 203, fr: "poisson", en: "fish", pos: "noun" },
  { id: 204, fr: "oiseau", en: "bird", pos: "noun" },
  { id: 205, fr: "cheval", en: "horse", pos: "noun" },
  { id: 206, fr: "vache", en: "cow", pos: "noun" },
  { id: 207, fr: "mouton", en: "sheep", pos: "noun" },
  { id: 208, fr: "cochon", en: "pig", pos: "noun" },
  { id: 209, fr: "poule", en: "hen", pos: "noun" },
  { id: 210, fr: "crabe", en: "crab", pos: "noun" },
  { id: 211, fr: "pomme", en: "apple", pos: "noun" },
  { id: 212, fr: "banane", en: "banana", pos: "noun" },
  { id: 213, fr: "orange", en: "orange", pos: "noun" },
  { id: 214, fr: "fraise", en: "strawberry", pos: "noun" },
  { id: 215, fr: "raisin", en: "grape", pos: "noun" },
  { id: 216, fr: "légume", en: "vegetable", pos: "noun" },
  { id: 217, fr: "carotte", en: "carrot", pos: "noun" },
  { id: 218, fr: "pomme de terre", en: "potato", pos: "noun" },
  { id: 219, fr: "tomate", en: "tomato", pos: "noun" },
  { id: 220, fr: "pain", en: "bread", pos: "noun" },
  { id: 221, fr: "beurre", en: "butter", pos: "noun" },
  { id: 222, fr: "fromage", en: "cheese", pos: "noun" },
  { id: 223, fr: "eau", en: "water", pos: "noun" },
  { id: 224, fr: "lait", en: "milk", pos: "noun" },
  { id: 225, fr: "thé", en: "tea", pos: "noun" },
  { id: 226, fr: "café", en: "coffee", pos: "noun" },
  { id: 227, fr: "sucre", en: "sugar", pos: "noun" },
  { id: 228, fr: "sel", en: "salt", pos: "noun" },
  { id: 229, fr: "poivre", en: "pepper", pos: "noun" },
  { id: 230, fr: "riz", en: "rice", pos: "noun" },
  { id: 231, fr: "pâtes", en: "pasta", pos: "noun" },
  { id: 232, fr: "poulet", en: "chicken", pos: "noun" },
  { id: 233, fr: "boeuf", en: "beef", pos: "noun" },
  { id: 234, fr: "porc", en: "pork", pos: "noun" },
  { id: 235, fr: "poisson (aliment)", en: "fish (food)", pos: "noun" },
  { id: 236, fr: "salade", en: "salad", pos: "noun" },
  { id: 237, fr: "soupe", en: "soup", pos: "noun" },
  { id: 238, fr: "dessert", en: "dessert", pos: "noun" },
  { id: 239, fr: "gâteau", en: "cake", pos: "noun" },
  { id: 240, fr: "glace", en: "ice cream", pos: "noun" },
  { id: 241, fr: "rouge", en: "red", pos: "adj" },
  { id: 242, fr: "bleu", en: "blue", pos: "adj" },
  { id: 243, fr: "vert", en: "green", pos: "adj" },
  { id: 244, fr: "jaune", en: "yellow", pos: "adj" },
  { id: 245, fr: "noir", en: "black", pos: "adj" },
  { id: 246, fr: "blanc", en: "white", pos: "adj" },
  { id: 247, fr: "gris", en: "gray", pos: "adj" },
  { id: 248, fr: "rose", en: "pink", pos: "adj" },
  { id: 249, fr: "marron", en: "brown", pos: "adj" },
  { id: 250, fr: "orange (couleur)", en: "orange", pos: "adj" },
  { id: 251, fr: "parapluie", en: "umbrella", pos: "noun" },
  { id: 252, fr: "bouteille", en: "bottle", pos: "noun" },
  { id: 253, fr: "verre", en: "glass", pos: "noun" },
  { id: 254, fr: "tasse", en: "cup", pos: "noun" },
  { id: 255, fr: "assiette", en: "plate", pos: "noun" },
  { id: 256, fr: "fourchette", en: "fork", pos: "noun" },
  { id: 257, fr: "couteau", en: "knife", pos: "noun" },
  { id: 258, fr: "cuillère", en: "spoon", pos: "noun" },
  { id: 259, fr: "frigo", en: "fridge", pos: "noun" },
  { id: 260, fr: "four", en: "oven", pos: "noun" },
  { id: 261, fr: "lampe", en: "lamp", pos: "noun" },
  { id: 262, fr: "fenêtre", en: "window", pos: "noun" },
  { id: 263, fr: "porte", en: "door", pos: "noun" },
  { id: 264, fr: "mur", en: "wall", pos: "noun" },
  { id: 265, fr: "plafond", en: "ceiling", pos: "noun" },
  { id: 266, fr: "sol", en: "floor", pos: "noun" },
  { id: 267, fr: "jardin", en: "garden", pos: "noun" },
  { id: 268, fr: "pont", en: "bridge", pos: "noun" },
  { id: 269, fr: "rivière", en: "river", pos: "noun" },
  { id: 270, fr: "lac", en: "lake", pos: "noun" },
  { id: 271, fr: "forêt", en: "forest", pos: "noun" },
  { id: 272, fr: "île", en: "island", pos: "noun" },
  { id: 273, fr: "mercredi", en: "Wednesday", pos: "noun" },
  { id: 274, fr: "jeudi", en: "Thursday", pos: "noun" },
  { id: 275, fr: "vendredi", en: "Friday", pos: "noun" },
  { id: 276, fr: "samedi", en: "Saturday", pos: "noun" },
  { id: 277, fr: "dimanche", en: "Sunday", pos: "noun" },
  { id: 278, fr: "janvier", en: "January", pos: "noun" },
  { id: 279, fr: "février", en: "February", pos: "noun" },
  { id: 280, fr: "mars", en: "March", pos: "noun" },
  { id: 281, fr: "avril", en: "April", pos: "noun" },
  { id: 282, fr: "mai", en: "May", pos: "noun" },
  { id: 283, fr: "juin", en: "June", pos: "noun" },
  { id: 284, fr: "juillet", en: "July", pos: "noun" },
  { id: 285, fr: "août", en: "August", pos: "noun" },
  { id: 286, fr: "septembre", en: "September", pos: "noun" },
  { id: 287, fr: "octobre", en: "October", pos: "noun" },
  { id: 288, fr: "novembre", en: "November", pos: "noun" },
  { id: 289, fr: "décembre", en: "December", pos: "noun" },
  { id: 290, fr: "chaise", en: "chair", pos: "noun" },
  { id: 291, fr: "banc", en: "bench", pos: "noun" },
  { id: 292, fr: "tableau", en: "board; picture", pos: "noun" },
  { id: 293, fr: "chaussette", en: "sock", pos: "noun" },
  { id: 294, fr: "manteau", en: "coat", pos: "noun" },
  { id: 295, fr: "jupe", en: "skirt", pos: "noun" },
  { id: 296, fr: "chapeau", en: "hat", pos: "noun" },
  { id: 297, fr: "gant", en: "glove", pos: "noun" },
  { id: 298, fr: "écharpe", en: "scarf", pos: "noun" },
  { id: 299, fr: "bijou", en: "jewel", pos: "noun" },
  { id: 300, fr: "bracelet", en: "bracelet", pos: "noun" },
  { id: 301, fr: "bague", en: "ring", pos: "noun" },
  { id: 302, fr: "collier", en: "necklace", pos: "noun" },
  { id: 303, fr: "ordinateur portable", en: "laptop", pos: "noun" },
  { id: 304, fr: "télévision", en: "television", pos: "noun" },
  { id: 305, fr: "radio", en: "radio", pos: "noun" },
  { id: 306, fr: "montre", en: "watch", pos: "noun" },
  { id: 307, fr: "horloge", en: "clock", pos: "noun" },
  { id: 308, fr: "sac à dos", en: "backpack", pos: "noun" },
  { id: 309, fr: "valise", en: "suitcase", pos: "noun" },
  { id: 310, fr: "train rapide", en: "fast train", pos: "noun" },
  { id: 311, fr: "camion", en: "truck", pos: "noun" },
  { id: 312, fr: "taxi", en: "taxi", pos: "noun" },
  { id: 313, fr: "moto", en: "motorcycle", pos: "noun" },
  { id: 314, fr: "bateau", en: "boat", pos: "noun" },
  { id: 315, fr: "feu", en: "fire", pos: "noun" },
  { id: 316, fr: "fumée", en: "smoke", pos: "noun" },
  { id: 317, fr: "ciel", en: "sky", pos: "noun" },
  { id: 318, fr: "étoile", en: "star", pos: "noun" },
  { id: 319, fr: "lune", en: "moon", pos: "noun" },
  { id: 320, fr: "terre", en: "earth; ground", pos: "noun" },
  { id: 321, fr: "sable", en: "sand", pos: "noun" },
  { id: 322, fr: "plage", en: "beach", pos: "noun" },
  { id: 323, fr: "vent fort", en: "strong wind", pos: "noun" },
  { id: 324, fr: "orage", en: "storm", pos: "noun" },
  { id: 325, fr: "nuage", en: "cloud", pos: "noun" },
  { id: 326, fr: "grossir", en: "to gain weight", pos: "verb" },
  { id: 327, fr: "maigrir", en: "to lose weight", pos: "verb" },
  { id: 328, fr: "finir", en: "to finish", pos: "verb" },
  { id: 329, fr: "grandir", en: "to grow up", pos: "verb" },
  { id: 330, fr: "choisir", en: "to choose", pos: "verb" },
  { id: 331, fr: "réussir", en: "to succeed", pos: "verb" },
  { id: 332, fr: "perdre", en: "to lose", pos: "verb" },
  { id: 333, fr: "gagner", en: "to win; to earn", pos: "verb" },
  { id: 334, fr: "rire", en: "to laugh", pos: "verb" },
  { id: 335, fr: "pleurer", en: "to cry", pos: "verb" },
  { id: 336, fr: "chanter", en: "to sing", pos: "verb" },
  { id: 337, fr: "danser", en: "to dance", pos: "verb" },
  { id: 338, fr: "nager", en: "to swim", pos: "verb" },
  { id: 339, fr: "courir", en: "to run", pos: "verb" },
  { id: 340, fr: "marcher", en: "to walk", pos: "verb" },
  { id: 341, fr: "se laver", en: "to wash oneself", pos: "verb" },
  { id: 342, fr: "se doucher", en: "to shower", pos: "verb" },
  { id: 343, fr: "se brosser", en: "to brush", pos: "verb" },
  { id: 344, fr: "enseigner", en: "to teach", pos: "verb" },
  { id: 345, fr: "acheter", en: "to buy", pos: "verb" },
  { id: 346, fr: "vendre", en: "to sell", pos: "verb" },
  { id: 347, fr: "porter", en: "to wear; to carry", pos: "verb" },
  { id: 348, fr: "cuisiner", en: "to cook", pos: "verb" },
  { id: 349, fr: "nettoyer", en: "to clean", pos: "verb" },
  { id: 350, fr: "réparer", en: "to repair", pos: "verb" },
  { id: 351, fr: "réserver", en: "to book", pos: "verb" },
  { id: 352, fr: "inviter", en: "to invite", pos: "verb" },
  { id: 353, fr: "accepter", en: "to accept", pos: "verb" },
  { id: 354, fr: "refuser", en: "to refuse", pos: "verb" },
  { id: 355, fr: "espérer", en: "to hope", pos: "verb" },
  { id: 356, fr: "ouvrir", en: "to open", pos: "verb" },
  { id: 357, fr: "fermer", en: "to close", pos: "verb" },
  { id: 358, fr: "apporter", en: "to bring", pos: "verb" },
  { id: 359, fr: "emmener", en: "to take (someone)", pos: "verb" },
  { id: 360, fr: "laisser", en: "to leave (object)", pos: "verb" },
  { id: 361, fr: "vivant", en: "alive", pos: "adj" },
  { id: 362, fr: "mort", en: "dead", pos: "adj" },
  { id: 363, fr: "rapide", en: "fast", pos: "adj" },
  { id: 364, fr: "lent", en: "slow", pos: "adj" },
  { id: 365, fr: "calme", en: "calm", pos: "adj" },
  { id: 366, fr: "bruyant", en: "noisy", pos: "adj" },
  { id: 367, fr: "pauvre", en: "poor", pos: "adj" },
  { id: 368, fr: "riche", en: "rich", pos: "adj" },
  { id: 369, fr: "froid", en: "cold", pos: "adj" },
  { id: 370, fr: "chaud", en: "hot", pos: "adj" },
  { id: 371, fr: "heureux", en: "happy", pos: "adj" },
  { id: 372, fr: "sérieux", en: "serious", pos: "adj" },
  { id: 373, fr: "gentil", en: "kind", pos: "adj" },
  { id: 374, fr: "mignon", en: "cute", pos: "adj" },
  { id: 375, fr: "fortement", en: "strongly", pos: "adv" },
  { id: 376, fr: "lentement", en: "slowly", pos: "adv" },
  { id: 377, fr: "rapidement", en: "quickly", pos: "adv" },
  { id: 378, fr: "hier soir", en: "last night", pos: "adv" },
  { id: 379, fr: "tout de suite", en: "immediately", pos: "adv" },
  { id: 380, fr: "parfois", en: "sometimes", pos: "adv" },
  { id: 381, fr: "souvent", en: "often", pos: "adv" },
  { id: 382, fr: "bientôt", en: "soon", pos: "adv" },
  { id: 383, fr: "loin", en: "far", pos: "adv" },
  { id: 384, fr: "près", en: "near", pos: "adv" },
  { id: 401, fr: "argent", en: "money", pos: "noun" },
  { id: 402, fr: "prix", en: "price", pos: "noun" },
  { id: 403, fr: "cadeau", en: "gift", pos: "noun" },
  { id: 404, fr: "anniversaire", en: "birthday", pos: "noun" },
  { id: 405, fr: "fête", en: "party", pos: "noun" },
  { id: 406, fr: "travail", en: "work", pos: "noun" },
  { id: 407, fr: "emploi", en: "job", pos: "noun" },
  { id: 408, fr: "métier", en: "profession", pos: "noun" },
  { id: 409, fr: "boutique", en: "shop", pos: "noun" },
  { id: 410, fr: "boulangerie", en: "bakery", pos: "noun" },
  { id: 411, fr: "boucherie", en: "butcher shop", pos: "noun" },
  { id: 412, fr: "librairie", en: "bookshop", pos: "noun" },
  { id: 413, fr: "pharmacie", en: "pharmacy", pos: "noun" },
  { id: 414, fr: "poste", en: "post office", pos: "noun" },
  { id: 415, fr: "police", en: "police", pos: "noun" },
  { id: 416, fr: "pompiers", en: "firefighters", pos: "noun" },
  { id: 417, fr: "mairie", en: "town hall", pos: "noun" },
  { id: 418, fr: "gare routière", en: "bus station", pos: "noun" },
  { id: 419, fr: "centre-ville", en: "downtown", pos: "noun" },
  { id: 420, fr: "quartier", en: "neighborhood", pos: "noun" },
  { id: 421, fr: "route", en: "road", pos: "noun" },
  { id: 422, fr: "autoroute", en: "highway", pos: "noun" },
  { id: 423, fr: "feu rouge", en: "traffic light", pos: "noun" },
  { id: 424, fr: "piéton", en: "pedestrian", pos: "noun" },
  { id: 425, fr: "carrefour", en: "intersection", pos: "noun" },
  { id: 426, fr: "rond-point", en: "roundabout", pos: "noun" },
  { id: 427, fr: "chaussée", en: "roadway", pos: "noun" },
  { id: 428, fr: "trottoir", en: "sidewalk", pos: "noun" },
  { id: 429, fr: "arrivée", en: "arrival", pos: "noun" },
  { id: 430, fr: "départ", en: "departure", pos: "noun" },
  { id: 431, fr: "billet", en: "ticket", pos: "noun" },
  { id: 432, fr: "horaire", en: "schedule", pos: "noun" },
  { id: 433, fr: "retard", en: "delay", pos: "noun" },
  { id: 434, fr: "voyage", en: "trip", pos: "noun" },
  { id: 435, fr: "valider", en: "to validate", pos: "verb" },
  { id: 436, fr: "changer", en: "to change", pos: "verb" },
  { id: 437, fr: "visiter", en: "to visit", pos: "verb" },
  { id: 438, fr: "dormir", en: "to sleep", pos: "verb" },
  { id: 439, fr: "réveiller", en: "to wake up", pos: "verb" },
  { id: 440, fr: "s'habiller", en: "to get dressed", pos: "verb" },
  { id: 441, fr: "se déshabiller", en: "to undress", pos: "verb" },
  { id: 442, fr: "préparer", en: "to prepare", pos: "verb" },
  { id: 443, fr: "organiser", en: "to organize", pos: "verb" },
  { id: 444, fr: "réfléchir", en: "to think", pos: "verb" },
  { id: 445, fr: "noter", en: "to write down", pos: "verb" },
  { id: 446, fr: "permettre", en: "to allow", pos: "verb" },
  { id: 447, fr: "interdire", en: "to forbid", pos: "verb" },
  { id: 448, fr: "comparer", en: "to compare", pos: "verb" },
  { id: 449, fr: "corriger", en: "to correct", pos: "verb" },
  { id: 450, fr: "apprendre", en: "to learn", pos: "verb" },
  { id: 451, fr: "réviser", en: "to review", pos: "verb" },
  { id: 452, fr: "pratiquer", en: "to practice", pos: "verb" },
  { id: 453, fr: "répondre", en: "to respond", pos: "verb" },
  { id: 454, fr: "envoyer", en: "to send", pos: "verb" },
  { id: 455, fr: "recevoir", en: "to receive", pos: "verb" },
  { id: 456, fr: "tirer", en: "to pull", pos: "verb" },
  { id: 457, fr: "pousser", en: "to push", pos: "verb" },
  { id: 458, fr: "marcher", en: "to walk", pos: "verb" },
  { id: 459, fr: "rouler", en: "to drive/roll", pos: "verb" },
  { id: 460, fr: "montrer", en: "to show", pos: "verb" },
  { id: 461, fr: "cacher", en: "to hide", pos: "verb" },
  { id: 462, fr: "changer", en: "to change", pos: "verb" },
  { id: 463, fr: "acheter", en: "to buy", pos: "verb" },
  { id: 464, fr: "coiffer", en: "to do hair", pos: "verb" },
  { id: 465, fr: "maquiller", en: "to put makeup", pos: "verb" },
  { id: 466, fr: "raser", en: "to shave", pos: "verb" },
  { id: 467, fr: "tomber malade", en: "to get sick", pos: "verb" },
  { id: 468, fr: "guérir", en: "to heal", pos: "verb" },
  { id: 469, fr: "médecin", en: "doctor", pos: "noun" },
  { id: 470, fr: "infirmier", en: "nurse (m)", pos: "noun" },
  { id: 471, fr: "infirmière", en: "nurse (f)", pos: "noun" },
  { id: 472, fr: "patient", en: "patient", pos: "noun" },
  { id: 473, fr: "ordonnance", en: "prescription", pos: "noun" },
  { id: 474, fr: "douleur", en: "pain", pos: "noun" },
  { id: 475, fr: "mal de tête", en: "headache", pos: "noun" },
  { id: 476, fr: "fièvre", en: "fever", pos: "noun" },
  { id: 477, fr: "toux", en: "cough", pos: "noun" },
  { id: 478, fr: "rhume", en: "cold", pos: "noun" },
  { id: 479, fr: "pharmacie", en: "pharmacy", pos: "noun" },
  { id: 480, fr: "médicament", en: "medicine", pos: "noun" },
  { id: 481, fr: "vitamine", en: "vitamin", pos: "noun" },
  { id: 482, fr: "bande", en: "bandage", pos: "noun" },
  { id: 483, fr: "dent", en: "tooth", pos: "noun" },
  { id: 484, fr: "dos", en: "back", pos: "noun" },
  { id: 485, fr: "bras", en: "arm", pos: "noun" },
  { id: 486, fr: "jambe", en: "leg", pos: "noun" },
  { id: 487, fr: "pied", en: "foot", pos: "noun" },
  { id: 488, fr: "main", en: "hand", pos: "noun" },
  { id: 489, fr: "doigt", en: "finger", pos: "noun" },
  { id: 490, fr: "tête", en: "head", pos: "noun" },
  { id: 491, fr: "visage", en: "face", pos: "noun" },
  { id: 492, fr: "cou", en: "neck", pos: "noun" },
  { id: 493, fr: "épaule", en: "shoulder", pos: "noun" },
  { id: 494, fr: "ventre", en: "belly", pos: "noun" },
  { id: 495, fr: "genou", en: "knee", pos: "noun" },
  { id: 496, fr: "cheville", en: "ankle", pos: "noun" },
  { id: 497, fr: "prochain", en: "next", pos: "adj" },
  { id: 498, fr: "dernier", en: "last", pos: "adj" },
  { id: 499, fr: "premier", en: "first", pos: "adj" },
  { id: 500, fr: "deuxième", en: "second", pos: "adj" },
  { id: 501, fr: "suivant", en: "following", pos: "adj" },
  { id: 502, fr: "ensemble", en: "together", pos: "adv" },
  { id: 503, fr: "seulement", en: "only", pos: "adv" },
  { id: 504, fr: "encore", en: "again", pos: "adv" },
  { id: 505, fr: "déjà", en: "already", pos: "adv" },
  { id: 506, fr: "trop", en: "too much", pos: "adv" },
  { id: 507, fr: "assez", en: "enough", pos: "adv" },
  { id: 508, fr: "peut-être", en: "maybe", pos: "adv" },
  { id: 509, fr: "vraiment", en: "really", pos: "adv" },
  { id: 510, fr: "certainement", en: "certainly", pos: "adv" },
  { id: 511, fr: "simplement", en: "simply", pos: "adv" },
  { id: 512, fr: "facilement", en: "easily", pos: "adv" },
  { id: 513, fr: "difficilement", en: "with difficulty", pos: "adv" },
  { id: 514, fr: "ailleurs", en: "elsewhere", pos: "adv" },
  { id: 515, fr: "ici", en: "here", pos: "adv" },
  { id: 516, fr: "là-bas", en: "over there", pos: "adv" },
  { id: 517, fr: "devant", en: "in front of", pos: "prep" },
  { id: 518, fr: "derrière", en: "behind", pos: "prep" },
  { id: 519, fr: "entre", en: "between", pos: "prep" },
  { id: 520, fr: "par", en: "through/by", pos: "prep" },
  { id: 521, fr: "sans", en: "without", pos: "prep" },
  { id: 522, fr: "contre", en: "against", pos: "prep" },
  { id: 523, fr: "pendant", en: "during", pos: "prep" },
  { id: 524, fr: "depuis", en: "since", pos: "prep" },
  { id: 525, fr: "pour", en: "for", pos: "prep" },
  { id: 526, fr: "vers", en: "towards", pos: "prep" },
  { id: 527, fr: "au-dessus", en: "above", pos: "adv" },
  { id: 528, fr: "au-dessous", en: "below", pos: "adv" },
  { id: 529, fr: "proche", en: "near", pos: "adj" },
  { id: 530, fr: "loin", en: "far", pos: "adj" },
  { id: 531, fr: "court", en: "short", pos: "adj" },
  { id: 532, fr: "large", en: "wide", pos: "adj" },
  { id: 533, fr: "étroit", en: "narrow", pos: "adj" },
  { id: 534, fr: "lourd", en: "heavy", pos: "adj" },
  { id: 535, fr: "léger", en: "light", pos: "adj" },
  { id: 536, fr: "plein", en: "full", pos: "adj" },
  { id: 537, fr: "vide", en: "empty", pos: "adj" },
  { id: 538, fr: "sec", en: "dry", pos: "adj" },
  { id: 539, fr: "humide", en: "wet", pos: "adj" },
  { id: 540, fr: "rapide", en: "fast", pos: "adj" },
  { id: 541, fr: "lent", en: "slow", pos: "adj" },
  { id: 542, fr: "agréable", en: "pleasant", pos: "adj" },
  { id: 543, fr: "désagréable", en: "unpleasant", pos: "adj" },
  { id: 544, fr: "utile", en: "useful", pos: "adj" },
  { id: 545, fr: "inutile", en: "useless", pos: "adj" },
  { id: 546, fr: "normal", en: "normal", pos: "adj" },
  { id: 547, fr: "anormal", en: "abnormal", pos: "adj" },
  { id: 548, fr: "possible", en: "possible", pos: "adj" },
  { id: 549, fr: "impossible", en: "impossible", pos: "adj" },
  { id: 550, fr: "sûr", en: "safe/sure", pos: "adj" },
  { id: 551, fr: "dangereux", en: "dangerous", pos: "adj" },
  { id: 552, fr: "public", en: "public", pos: "adj" },
  { id: 553, fr: "privé", en: "private", pos: "adj" },
  { id: 554, fr: "local", en: "local", pos: "adj" },
  { id: 555, fr: "international", en: "international", pos: "adj" },
  { id: 556, fr: "culture", en: "culture", pos: "noun" },
  { id: 557, fr: "musée", en: "museum", pos: "noun" },
  { id: 558, fr: "cinéma", en: "cinema", pos: "noun" },
  { id: 559, fr: "théâtre", en: "theater", pos: "noun" },
  { id: 560, fr: "concert", en: "concert", pos: "noun" },
  { id: 561, fr: "spectacle", en: "show", pos: "noun" },
  { id: 562, fr: "chanson", en: "song", pos: "noun" },
  { id: 563, fr: "musique", en: "music", pos: "noun" },
  { id: 564, fr: "dessin", en: "drawing", pos: "noun" },
  { id: 565, fr: "peinture", en: "painting", pos: "noun" },
  { id: 566, fr: "photo", en: "photo", pos: "noun" },
  { id: 567, fr: "film", en: "movie", pos: "noun" },
  { id: 568, fr: "jeu", en: "game", pos: "noun" },
  { id: 569, fr: "jouet", en: "toy", pos: "noun" },
  { id: 570, fr: "sport", en: "sport", pos: "noun" },
  { id: 571, fr: "ballon", en: "ball", pos: "noun" },
  { id: 572, fr: "vérité", en: "truth", pos: "noun" },
  { id: 573, fr: "mensonge", en: "lie", pos: "noun" },
  { id: 574, fr: "histoire", en: "story/history", pos: "noun" },
  { id: 575, fr: "nouvelle", en: "news", pos: "noun" },
  { id: 576, fr: "information", en: "information", pos: "noun" },
  { id: 577, fr: "journal", en: "newspaper", pos: "noun" },
  { id: 578, fr: "magazine", en: "magazine", pos: "noun" },
  { id: 579, fr: "site", en: "website", pos: "noun" },
  { id: 580, fr: "internet", en: "internet", pos: "noun" },
  { id: 581, fr: "compte", en: "account", pos: "noun" },
  { id: 582, fr: "mot de passe", en: "password", pos: "noun" },
  { id: 583, fr: "message", en: "message", pos: "noun" },
  { id: 584, fr: "appel", en: "call", pos: "noun" },
  { id: 585, fr: "photo", en: "photo", pos: "noun" },
  { id: 586, fr: "vidéo", en: "video", pos: "noun" },
  { id: 601, fr: "amour", en: "love", pos: "noun" },
  { id: 602, fr: "amitié", en: "friendship", pos: "noun" },
  { id: 603, fr: "paix", en: "peace", pos: "noun" },
  { id: 604, fr: "guerre", en: "war", pos: "noun" },
  { id: 605, fr: "cadeau", en: "gift", pos: "noun" },
  { id: 606, fr: "souvenir", en: "memory", pos: "noun" },
  { id: 607, fr: "travailleur", en: "worker", pos: "noun" },
  { id: 608, fr: "serveur", en: "waiter", pos: "noun" },
  { id: 609, fr: "serveuse", en: "waitress", pos: "noun" },
  { id: 610, fr: "chef", en: "boss", pos: "noun" },
  { id: 611, fr: "clientèle", en: "customers", pos: "noun" },
  { id: 612, fr: "visiteur", en: "visitor", pos: "noun" },
  { id: 613, fr: "touriste", en: "tourist", pos: "noun" },
  { id: 614, fr: "habit", en: "clothes", pos: "noun" },
  { id: 615, fr: "costume", en: "suit", pos: "noun" },
  { id: 616, fr: "pull", en: "sweater", pos: "noun" },
  { id: 617, fr: "veste", en: "jacket", pos: "noun" },
  { id: 618, fr: "short", en: "shorts", pos: "noun" },
  { id: 619, fr: "chausson", en: "slipper", pos: "noun" },
  { id: 620, fr: "ceinture", en: "belt", pos: "noun" },
  { id: 621, fr: "lunettes", en: "glasses", pos: "noun" },
  { id: 622, fr: "sacoche", en: "bag", pos: "noun" },
  { id: 623, fr: "portefeuille", en: "wallet", pos: "noun" },
  { id: 624, fr: "clé USB", en: "USB drive", pos: "noun" },
  { id: 625, fr: "télécommande", en: "remote control", pos: "noun" },
  { id: 626, fr: "prise", en: "plug", pos: "noun" },
  { id: 627, fr: "chargeur", en: "charger", pos: "noun" },
  { id: 628, fr: "oreiller", en: "pillow", pos: "noun" },
  { id: 629, fr: "couverture", en: "blanket", pos: "noun" },
  { id: 630, fr: "drap", en: "sheet", pos: "noun" },
  { id: 631, fr: "serviette", en: "towel", pos: "noun" },
  { id: 632, fr: "brosse", en: "brush", pos: "noun" },
  { id: 633, fr: "peigne", en: "comb", pos: "noun" },
  { id: 634, fr: "savon", en: "soap", pos: "noun" },
  { id: 635, fr: "shampoing", en: "shampoo", pos: "noun" },
  { id: 636, fr: "dentifrice", en: "toothpaste", pos: "noun" },
  { id: 637, fr: "rasoir", en: "razor", pos: "noun" },
  { id: 638, fr: "linge", en: "laundry", pos: "noun" },
  { id: 639, fr: "machine à laver", en: "washing machine", pos: "noun" },
  { id: 640, fr: "séchoir", en: "dryer", pos: "noun" },
  { id: 641, fr: "poubelle", en: "trash can", pos: "noun" },
  { id: 642, fr: "balai", en: "broom", pos: "noun" },
  { id: 643, fr: "serpillière", en: "mop", pos: "noun" },
  { id: 644, fr: "éponge", en: "sponge", pos: "noun" },
  { id: 645, fr: "produit", en: "product", pos: "noun" },
  { id: 646, fr: "goût", en: "taste", pos: "noun" },
  { id: 647, fr: "odeur", en: "smell", pos: "noun" },
  { id: 648, fr: "bruit", en: "noise", pos: "noun" },
  { id: 649, fr: "silence", en: "silence", pos: "noun" },
  { id: 650, fr: "couleur", en: "color", pos: "noun" },
  { id: 651, fr: "forme", en: "shape", pos: "noun" },
  { id: 652, fr: "taille", en: "size", pos: "noun" },
  { id: 653, fr: "quantité", en: "quantity", pos: "noun" },
  { id: 654, fr: "qualité", en: "quality", pos: "noun" },
  { id: 655, fr: "prix", en: "price", pos: "noun" },
  { id: 656, fr: "réduction", en: "discount", pos: "noun" },
  { id: 657, fr: "solde", en: "sale", pos: "noun" },
  { id: 658, fr: "carte", en: "card", pos: "noun" },
  { id: 659, fr: "plan", en: "map", pos: "noun" },
  { id: 660, fr: "itinéraire", en: "route", pos: "noun" },
  { id: 661, fr: "colline", en: "hill", pos: "noun" },
  { id: 662, fr: "prairie", en: "meadow", pos: "noun" },
  { id: 663, fr: "désert", en: "desert", pos: "noun" },
  { id: 664, fr: "jungle", en: "jungle", pos: "noun" },
  { id: 665, fr: "zoo", en: "zoo", pos: "noun" },
  { id: 666, fr: "ferme", en: "farm", pos: "noun" },
  { id: 667, fr: "champs", en: "field", pos: "noun" },
  { id: 668, fr: "coq", en: "rooster", pos: "noun" },
  { id: 669, fr: "âne", en: "donkey", pos: "noun" },
  { id: 670, fr: "lapin", en: "rabbit", pos: "noun" },
  { id: 671, fr: "chien de garde", en: "guard dog", pos: "noun" },
  { id: 672, fr: "tortue", en: "turtle", pos: "noun" },
  { id: 673, fr: "girafe", en: "giraffe", pos: "noun" },
  { id: 674, fr: "lion", en: "lion", pos: "noun" },
  { id: 675, fr: "tigre", en: "tiger", pos: "noun" },
  { id: 676, fr: "éléphant", en: "elephant", pos: "noun" },
  { id: 677, fr: "hérisson", en: "hedgehog", pos: "noun" },
  { id: 678, fr: "ours", en: "bear", pos: "noun" },
  { id: 679, fr: "arbre", en: "tree", pos: "noun" },
  { id: 680, fr: "branche", en: "branch", pos: "noun" },
  { id: 681, fr: "feuille", en: "leaf", pos: "noun" },
  { id: 682, fr: "racine", en: "root", pos: "noun" },
  { id: 683, fr: "herbe", en: "grass", pos: "noun" },
  { id: 684, fr: "fleur", en: "flower", pos: "noun" },
  { id: 685, fr: "inverse", en: "opposite", pos: "noun" },
  { id: 686, fr: "droite", en: "right", pos: "noun" },
  { id: 687, fr: "gauche", en: "left", pos: "noun" },
  { id: 688, fr: "milieu", en: "middle", pos: "noun" },
  { id: 689, fr: "bord", en: "edge", pos: "noun" },
  { id: 690, fr: "haut", en: "top", pos: "noun" },
  { id: 691, fr: "bas", en: "bottom", pos: "noun" },
  { id: 692, fr: "intérieur", en: "inside", pos: "noun" },
  { id: 693, fr: "extérieur", en: "outside", pos: "noun" },
  { id: 694, fr: "loin de", en: "far from", pos: "prep" },
  { id: 695, fr: "près de", en: "near", pos: "prep" },
  { id: 696, fr: "autour de", en: "around", pos: "prep" },
  { id: 697, fr: "à côté de", en: "next to", pos: "prep" },
  { id: 698, fr: "au milieu de", en: "in the middle of", pos: "prep" },
  { id: 699, fr: "au fond de", en: "at the back of", pos: "prep" },
  { id: 700, fr: "par-dessus", en: "over", pos: "prep" },
  { id: 701, fr: "par-dessous", en: "under", pos: "prep" },
  { id: 702, fr: "asseoir", en: "to sit", pos: "verb" },
  { id: 703, fr: "lever", en: "to rise", pos: "verb" },
  { id: 704, fr: "réveiller", en: "to wake", pos: "verb" },
  { id: 705, fr: "saluer", en: "to greet", pos: "verb" },
  { id: 706, fr: "rencontrer", en: "to meet", pos: "verb" },
  { id: 707, fr: "porter", en: "to carry", pos: "verb" },
  { id: 708, fr: "soulever", en: "to lift", pos: "verb" },
  { id: 709, fr: "attraper", en: "to catch", pos: "verb" },
  { id: 710, fr: "jeter", en: "to throw", pos: "verb" },
  { id: 711, fr: "casser", en: "to break", pos: "verb" },
  { id: 712, fr: "réparer", en: "to repair", pos: "verb" },
  { id: 713, fr: "laver", en: "to wash", pos: "verb" },
  { id: 714, fr: "sécher", en: "to dry", pos: "verb" },
  { id: 715, fr: "plier", en: "to fold", pos: "verb" },
  { id: 716, fr: "coller", en: "to glue", pos: "verb" },
  { id: 717, fr: "découper", en: "to cut", pos: "verb" },
  { id: 718, fr: "allumer", en: "to turn on", pos: "verb" },
  { id: 719, fr: "éteindre", en: "to turn off", pos: "verb" },
  { id: 720, fr: "charger", en: "to load", pos: "verb" },
  { id: 721, fr: "vider", en: "to empty", pos: "verb" },
  { id: 722, fr: "remplir", en: "to fill", pos: "verb" },
  { id: 723, fr: "choisir", en: "to choose", pos: "verb" },
  { id: 724, fr: "décider", en: "to decide", pos: "verb" },
  { id: 725, fr: "accompagner", en: "to accompany", pos: "verb" },
  { id: 726, fr: "expliquer", en: "to explain", pos: "verb" },
  { id: 727, fr: "décrire", en: "to describe", pos: "verb" },
  { id: 728, fr: "annoncer", en: "to announce", pos: "verb" },
  { id: 729, fr: "promettre", en: "to promise", pos: "verb" },
  { id: 730, fr: "refuser", en: "to refuse", pos: "verb" },
  { id: 731, fr: "avancer", en: "to move forward", pos: "verb" },
  { id: 732, fr: "reculer", en: "to move back", pos: "verb" },
  { id: 733, fr: "tomber", en: "to fall", pos: "verb" },
  { id: 734, fr: "tourner", en: "to turn", pos: "verb" },
  { id: 735, fr: "glisser", en: "to slip", pos: "verb" },
  { id: 736, fr: "briller", en: "to shine", pos: "verb" },
  { id: 737, fr: "se reposer", en: "to rest", pos: "verb" },
  { id: 738, fr: "respirer", en: "to breathe", pos: "verb" },
  { id: 739, fr: "toucher", en: "to touch", pos: "verb" },
  { id: 740, fr: "garder", en: "to keep", pos: "verb" },
  { id: 741, fr: "changer", en: "to change", pos: "verb" },
  { id: 742, fr: "prêter", en: "to lend", pos: "verb" },
  { id: 743, fr: "emprunter", en: "to borrow", pos: "verb" },
  { id: 744, fr: "calme", en: "calm", pos: "adj" },
  { id: 745, fr: "tranquille", en: "quiet", pos: "adj" },
  { id: 746, fr: "agité", en: "restless", pos: "adj" },
  { id: 747, fr: "mince", en: "thin", pos: "adj" },
  { id: 748, fr: "épais", en: "thick", pos: "adj" },
  { id: 749, fr: "brillant", en: "bright", pos: "adj" },
  { id: 750, fr: "obscur", en: "dark", pos: "adj" },
  { id: 751, fr: "profond", en: "deep", pos: "adj" },
  { id: 752, fr: "superficiel", en: "shallow", pos: "adj" },
  { id: 753, fr: "correct", en: "correct", pos: "adj" },
  { id: 754, fr: "incorrect", en: "incorrect", pos: "adj" },
  { id: 755, fr: "utile", en: "useful", pos: "adj" },
  { id: 756, fr: "nécessaire", en: "necessary", pos: "adj" },
  { id: 757, fr: "chaud", en: "warm", pos: "adj" },
  { id: 758, fr: "froid", en: "cool", pos: "adj" },
  { id: 759, fr: "heureux", en: "happy", pos: "adj" },
  { id: 760, fr: "jaloux", en: "jealous", pos: "adj" },
  { id: 761, fr: "timide", en: "shy", pos: "adj" },
  { id: 762, fr: "curieux", en: "curious", pos: "adj" },
  { id: 763, fr: "sage", en: "wise", pos: "adj" },
  { id: 764, fr: "fou", en: "crazy", pos: "adj" },
  { id: 765, fr: "énorme", en: "huge", pos: "adj" },
  { id: 766, fr: "minuscule", en: "tiny", pos: "adj" },
  { id: 767, fr: "fréquent", en: "frequent", pos: "adj" },
  { id: 768, fr: "rare", en: "rare", pos: "adj" },
  { id: 769, fr: "presque", en: "almost", pos: "adv" },
  { id: 770, fr: "toujours", en: "always", pos: "adv" },
  { id: 771, fr: "souvent", en: "often", pos: "adv" },
  { id: 772, fr: "soudain", en: "suddenly", pos: "adv" },
  { id: 773, fr: "rapidement", en: "quickly", pos: "adv" },
  { id: 774, fr: "prudemment", en: "carefully", pos: "adv" },
  { id: 775, fr: "hier matin", en: "yesterday morning", pos: "adv" },
  { id: 776, fr: "demain soir", en: "tomorrow evening", pos: "adv" },
  { id: 777, fr: "partout", en: "everywhere", pos: "adv" },
  { id: 778, fr: "nulle part", en: "nowhere", pos: "adv" },
  { id: 779, fr: "ensemble", en: "together", pos: "adv" },
  { id: 801, fr: "voyageur", en: "traveler", pos: "noun" },
  { id: 802, fr: "bagage", en: "luggage", pos: "noun" },
  { id: 803, fr: "douane", en: "customs", pos: "noun" },
  { id: 804, fr: "frontière", en: "border", pos: "noun" },
  { id: 805, fr: "passeport", en: "passport", pos: "noun" },
  { id: 806, fr: "billet aller-retour", en: "round-trip ticket", pos: "noun" },
  { id: 807, fr: "hôtel", en: "hotel", pos: "noun" },
  { id: 808, fr: "auberge", en: "hostel", pos: "noun" },
  { id: 809, fr: "réception", en: "reception", pos: "noun" },
  { id: 810, fr: "clef", en: "key", pos: "noun" },
  { id: 811, fr: "ascenseur", en: "elevator", pos: "noun" },
  { id: 812, fr: "escalier", en: "stairs", pos: "noun" },
  { id: 813, fr: "couloir", en: "corridor", pos: "noun" },
  { id: 814, fr: "entrée", en: "entrance", pos: "noun" },
  { id: 815, fr: "sortie", en: "exit", pos: "noun" },
  { id: 816, fr: "abri", en: "shelter", pos: "noun" },
  { id: 817, fr: "destination", en: "destination", pos: "noun" },
  { id: 818, fr: "carte d’identité", en: "ID card", pos: "noun" },
  { id: 819, fr: "invité", en: "guest", pos: "noun" },
  { id: 820, fr: "patron", en: "boss", pos: "noun" },
  { id: 821, fr: "collègue", en: "colleague", pos: "noun" },
  { id: 822, fr: "réunion", en: "meeting", pos: "noun" },
  { id: 823, fr: "pause", en: "break", pos: "noun" },
  { id: 824, fr: "salaire", en: "salary", pos: "noun" },
  { id: 825, fr: "entreprise", en: "company", pos: "noun" },
  { id: 826, fr: "bureau", en: "office", pos: "noun" },
  { id: 827, fr: "dossier", en: "file", pos: "noun" },
  { id: 828, fr: "document", en: "document", pos: "noun" },
  { id: 829, fr: "imprimante", en: "printer", pos: "noun" },
  { id: 830, fr: "stylo à bille", en: "ballpoint pen", pos: "noun" },
  { id: 831, fr: "surprise", en: "surprise", pos: "noun" },
  { id: 832, fr: "espoir", en: "hope", pos: "noun" },
  { id: 833, fr: "peur", en: "fear", pos: "noun" },
  { id: 834, fr: "colère", en: "anger", pos: "noun" },
  { id: 835, fr: "joie", en: "joy", pos: "noun" },
  { id: 836, fr: "tristesse", en: "sadness", pos: "noun" },
  { id: 837, fr: "honte", en: "shame", pos: "noun" },
  { id: 838, fr: "courage", en: "courage", pos: "noun" },
  { id: 839, fr: "patience", en: "patience", pos: "noun" },
  { id: 840, fr: "force", en: "strength", pos: "noun" },
  { id: 841, fr: "faiblesse", en: "weakness", pos: "noun" },
  { id: 842, fr: "goût", en: "taste", pos: "noun" },
  { id: 843, fr: "odeur", en: "smell", pos: "noun" },
  { id: 844, fr: "texture", en: "texture", pos: "noun" },
  { id: 845, fr: "lumière", en: "light", pos: "noun" },
  { id: 846, fr: "ombre", en: "shadow", pos: "noun" },
  { id: 847, fr: "obscurité", en: "darkness", pos: "noun" },
  { id: 848, fr: "air", en: "air", pos: "noun" },
  { id: 849, fr: "température", en: "temperature", pos: "noun" },
  { id: 850, fr: "saison", en: "season", pos: "noun" },
  { id: 851, fr: "printemps", en: "spring", pos: "noun" },
  { id: 852, fr: "été", en: "summer", pos: "noun" },
  { id: 853, fr: "automne", en: "autumn", pos: "noun" },
  { id: 854, fr: "hiver", en: "winter", pos: "noun" },
  { id: 855, fr: "éclair", en: "lightning", pos: "noun" },
  { id: 856, fr: "tonnerre", en: "thunder", pos: "noun" },
  { id: 857, fr: "averse", en: "shower (rain)", pos: "noun" },
  { id: 858, fr: "inondation", en: "flood", pos: "noun" },
  { id: 859, fr: "sécheresse", en: "drought", pos: "noun" },
  { id: 860, fr: "glace (matière)", en: "ice", pos: "noun" },
  { id: 861, fr: "feuille morte", en: "dead leaf", pos: "noun" },
  { id: 862, fr: "rocher", en: "rock", pos: "noun" },
  { id: 863, fr: "falaise", en: "cliff", pos: "noun" },
  { id: 864, fr: "chemin", en: "path", pos: "noun" },
  { id: 865, fr: "sentier", en: "trail", pos: "noun" },
  { id: 866, fr: "direction", en: "direction", pos: "noun" },
  { id: 867, fr: "niveau", en: "level", pos: "noun" },
  { id: 868, fr: "étape", en: "stage", pos: "noun" },
  { id: 869, fr: "but", en: "goal", pos: "noun" },
  { id: 870, fr: "raison", en: "reason", pos: "noun" },
  { id: 871, fr: "cause", en: "cause", pos: "noun" },
  { id: 872, fr: "effet", en: "effect", pos: "noun" },
  { id: 873, fr: "résultat", en: "result", pos: "noun" },
  { id: 874, fr: "conclusion", en: "conclusion", pos: "noun" },
  { id: 875, fr: "imagination", en: "imagination", pos: "noun" },
  { id: 876, fr: "rêve", en: "dream", pos: "noun" },
  { id: 877, fr: "réalité", en: "reality", pos: "noun" },
  { id: 878, fr: "mensonge", en: "lie", pos: "noun" },
  { id: 879, fr: "vérité", en: "truth", pos: "noun" },
  { id: 880, fr: "danger", en: "danger", pos: "noun" },
  { id: 881, fr: "sécurité", en: "safety", pos: "noun" },
  { id: 882, fr: "urgence", en: "emergency", pos: "noun" },
  { id: 883, fr: "risque", en: "risk", pos: "noun" },
  { id: 884, fr: "chance", en: "luck", pos: "noun" },
  { id: 885, fr: "malchance", en: "bad luck", pos: "noun" },
  { id: 886, fr: "côté", en: "side", pos: "noun" },
  { id: 887, fr: "angle", en: "angle", pos: "noun" },
  { id: 888, fr: "pente", en: "slope", pos: "noun" },
  { id: 889, fr: "direction", en: "direction", pos: "noun" },
  { id: 890, fr: "partie", en: "part", pos: "noun" },
  { id: 891, fr: "ensemble", en: "whole", pos: "noun" },
  { id: 892, fr: "sauter", en: "to jump", pos: "verb" },
  { id: 893, fr: "trembler", en: "to shake", pos: "verb" },
  { id: 894, fr: "sentir", en: "to feel/smell", pos: "verb" },
  { id: 895, fr: "respirer", en: "to breathe", pos: "verb" },
  { id: 896, fr: "agir", en: "to act", pos: "verb" },
  { id: 897, fr: "réagir", en: "to react", pos: "verb" },
  { id: 898, fr: "protéger", en: "to protect", pos: "verb" },
  { id: 899, fr: "éviter", en: "to avoid", pos: "verb" },
  { id: 900, fr: "accepter", en: "to accept", pos: "verb" },
  { id: 901, fr: "partager", en: "to share", pos: "verb" },
  { id: 902, fr: "mentir", en: "to lie", pos: "verb" },
  { id: 903, fr: "raconter", en: "to tell (a story)", pos: "verb" },
  { id: 904, fr: "deviner", en: "to guess", pos: "verb" },
  { id: 905, fr: "vider", en: "to empty", pos: "verb" },
  { id: 906, fr: "économiser", en: "to save (money)", pos: "verb" },
  { id: 907, fr: "dépenser", en: "to spend", pos: "verb" },
  { id: 908, fr: "servir", en: "to serve", pos: "verb" },
  { id: 909, fr: "ressembler", en: "to look like", pos: "verb" },
  { id: 910, fr: "profiter de", en: "to take advantage of", pos: "verb" },
  { id: 911, fr: "manquer", en: "to miss", pos: "verb" },
  { id: 912, fr: "supporter", en: "to endure", pos: "verb" },
  { id: 913, fr: "réserver", en: "to reserve", pos: "verb" },
  { id: 914, fr: "commander", en: "to order", pos: "verb" },
  { id: 915, fr: "refaire", en: "to redo", pos: "verb" },
  { id: 916, fr: "réduire", en: "to reduce", pos: "verb" },
  { id: 917, fr: "augmenter", en: "to increase", pos: "verb" },
  { id: 918, fr: "baisser", en: "to lower", pos: "verb" },
  { id: 919, fr: "allonger", en: "to extend", pos: "verb" },
  { id: 920, fr: "rétrécir", en: "to shrink", pos: "verb" },
  { id: 921, fr: "saut", en: "jump", pos: "noun" },
  { id: 922, fr: "chute", en: "fall", pos: "noun" },
  { id: 923, fr: "repos", en: "rest", pos: "noun" },
  { id: 924, fr: "déplacement", en: "movement", pos: "noun" },
  { id: 925, fr: "course", en: "running", pos: "noun" },
  { id: 926, fr: "victoire", en: "victory", pos: "noun" },
  { id: 927, fr: "défaite", en: "defeat", pos: "noun" },
  { id: 928, fr: "geste", en: "gesture", pos: "noun" },
  { id: 929, fr: "signal", en: "signal", pos: "noun" },
  { id: 930, fr: "erreur", en: "mistake", pos: "noun" },
  { id: 931, fr: "faute", en: "fault", pos: "noun" },
  { id: 932, fr: "occasion", en: "opportunity", pos: "noun" },
  { id: 933, fr: "événement", en: "event", pos: "noun" },
  { id: 934, fr: "activité", en: "activity", pos: "noun" },
  { id: 935, fr: "tâche", en: "task", pos: "noun" },
  { id: 936, fr: "semaine prochaine", en: "next week", pos: "adv" },
  { id: 937, fr: "semaine dernière", en: "last week", pos: "adv" },
  { id: 938, fr: "bientôt", en: "soon", pos: "adv" },
  { id: 939, fr: "tardivement", en: "late (adv)", pos: "adv" },
  { id: 940, fr: "franchement", en: "honestly", pos: "adv" },
  { id: 941, fr: "doucement", en: "gently", pos: "adv" },
  { id: 942, fr: "clairement", en: "clearly", pos: "adv" },
  { id: 943, fr: "fortement", en: "strongly", pos: "adv" },
  { id: 944, fr: "rarement", en: "rarely", pos: "adv" },
  { id: 945, fr: "parfois", en: "sometimes", pos: "adv" },
  { id: 946, fr: "environ", en: "approximately", pos: "adv" },
  { id: 947, fr: "exactement", en: "exactly", pos: "adv" },
  { id: 948, fr: "près", en: "near", pos: "adv" },
  { id: 949, fr: "loin", en: "far", pos: "adv" },
  { id: 950, fr: "ailleurs", en: "elsewhere", pos: "adv" },
  { id: 951, fr: "ici", en: "here", pos: "adv" },
  { id: 952, fr: "dedans", en: "inside", pos: "adv" },
  { id: 953, fr: "dehors", en: "outside", pos: "adv" },
  { id: 954, fr: "auparavant", en: "before", pos: "adv" },
  { id: 955, fr: "ensuite", en: "then", pos: "adv" },
  { id: 956, fr: "puis", en: "then", pos: "adv" },
  { id: 957, fr: "d’accord", en: "OK", pos: "adv" },
  { id: 958, fr: "bien sûr", en: "of course", pos: "adv" },
  { id: 959, fr: "à côté de", en: "next to", pos: "prep" },
  { id: 960, fr: "au-dessus de", en: "above", pos: "prep" },
  { id: 961, fr: "au-dessous de", en: "below", pos: "prep" },
  { id: 962, fr: "chez", en: "at someone's place", pos: "prep" },
  { id: 963, fr: "selon", en: "according to", pos: "prep" },
  { id: 964, fr: "grâce à", en: "thanks to", pos: "prep" },
  { id: 965, fr: "à cause de", en: "because of", pos: "prep" },
  { id: 966, fr: "malgré", en: "despite", pos: "prep" },
  { id: 967, fr: "parmi", en: "among", pos: "prep" },
  { id: 968, fr: "par", en: "through", pos: "prep" },
  { id: 969, fr: "contre", en: "against", pos: "prep" },
  { id: 970, fr: "vers", en: "toward", pos: "prep" },
  { id: 1001, fr: "argent de poche", en: "pocket money", pos: "noun" },
  { id: 1002, fr: "budget", en: "budget", pos: "noun" },
  { id: 1003, fr: "facture", en: "bill", pos: "noun" },
  { id: 1004, fr: "compte bancaire", en: "bank account", pos: "noun" },
  { id: 1005, fr: "carte bancaire", en: "bank card", pos: "noun" },
  { id: 1006, fr: "ticket", en: "ticket", pos: "noun" },
  { id: 1007, fr: "reçu", en: "receipt", pos: "noun" },
  { id: 1008, fr: "commande", en: "order", pos: "noun" },
  { id: 1009, fr: "livraison", en: "delivery", pos: "noun" },
  { id: 1010, fr: "marchandise", en: "goods", pos: "noun" },
  { id: 1011, fr: "entrepôt", en: "warehouse", pos: "noun" },
  { id: 1012, fr: "magasinier", en: "storekeeper", pos: "noun" },
  { id: 1013, fr: "vendeur", en: "salesperson", pos: "noun" },
  { id: 1014, fr: "vendeuse", en: "saleswoman", pos: "noun" },
  { id: 1015, fr: "client fidèle", en: "regular customer", pos: "noun" },
  { id: 1016, fr: "publicité", en: "advertisement", pos: "noun" },
  { id: 1017, fr: "promotion", en: "promotion", pos: "noun" },
  { id: 1018, fr: "catalogue", en: "catalog", pos: "noun" },
  { id: 1019, fr: "rayon", en: "department/aisle", pos: "noun" },
  { id: 1020, fr: "panneau", en: "sign", pos: "noun" },
  { id: 1021, fr: "affiche", en: "poster", pos: "noun" },
  { id: 1022, fr: "casque", en: "helmet/headphones", pos: "noun" },
  { id: 1023, fr: "écouteurs", en: "earphones", pos: "noun" },
  { id: 1024, fr: "clavier", en: "keyboard", pos: "noun" },
  { id: 1025, fr: "souris", en: "mouse", pos: "noun" },
  { id: 1026, fr: "écran", en: "screen", pos: "noun" },
  { id: 1027, fr: "fichier", en: "file", pos: "noun" },
  { id: 1028, fr: "application", en: "application", pos: "noun" },
  { id: 1029, fr: "logiciel", en: "software", pos: "noun" },
  { id: 1030, fr: "mot de passe", en: "password", pos: "noun" },
  { id: 1031, fr: "connexion", en: "connection", pos: "noun" },
  { id: 1032, fr: "réseau", en: "network", pos: "noun" },
  { id: 1033, fr: "wifi", en: "wifi", pos: "noun" },
  { id: 1034, fr: "nuage", en: "cloud (tech)", pos: "noun" },
  { id: 1035, fr: "téléchargement", en: "download", pos: "noun" },
  { id: 1036, fr: "chargement", en: "loading", pos: "noun" },
  { id: 1037, fr: "accès", en: "access", pos: "noun" },
  { id: 1038, fr: "données", en: "data", pos: "noun" },
  { id: 1039, fr: "paramètre", en: "setting", pos: "noun" },
  { id: 1040, fr: "alerte", en: "alert", pos: "noun" },
  { id: 1041, fr: "signalement", en: "report", pos: "noun" },
  { id: 1042, fr: "problème", en: "problem", pos: "noun" },
  { id: 1043, fr: "solution", en: "solution", pos: "noun" },
  { id: 1044, fr: "avance", en: "advance", pos: "noun" },
  { id: 1045, fr: "retour", en: "return", pos: "noun" },
  { id: 1046, fr: "déplacement", en: "movement", pos: "noun" },
  { id: 1047, fr: "trajet", en: "route", pos: "noun" },
  { id: 1048, fr: "carte routière", en: "road map", pos: "noun" },
  { id: 1049, fr: "autorisation", en: "authorization", pos: "noun" },
  { id: 1050, fr: "accord", en: "agreement", pos: "noun" },
  { id: 1051, fr: "désaccord", en: "disagreement", pos: "noun" },
  { id: 1052, fr: "réunion", en: "meeting", pos: "noun" },
  { id: 1053, fr: "présentation", en: "presentation", pos: "noun" },
  { id: 1054, fr: "projet", en: "project", pos: "noun" },
  { id: 1055, fr: "tâche", en: "task", pos: "noun" },
  { id: 1056, fr: "mission", en: "mission", pos: "noun" },
  { id: 1057, fr: "objectif", en: "objective", pos: "noun" },
  { id: 1058, fr: "contrôle", en: "control", pos: "noun" },
  { id: 1059, fr: "révision", en: "review", pos: "noun" },
  { id: 1060, fr: "modification", en: "modification", pos: "noun" },
  { id: 1061, fr: "erreur", en: "error", pos: "noun" },
  { id: 1062, fr: "succès", en: "success", pos: "noun" },
  { id: 1063, fr: "échec", en: "failure", pos: "noun" },
  { id: 1064, fr: "niveau", en: "level", pos: "noun" },
  { id: 1065, fr: "progression", en: "progress", pos: "noun" },
  { id: 1066, fr: "résolution", en: "resolution", pos: "noun" },
  { id: 1067, fr: "chômage", en: "unemployment", pos: "noun" },
  { id: 1068, fr: "entretien", en: "interview", pos: "noun" },
  { id: 1069, fr: "candidature", en: "application", pos: "noun" },
  { id: 1070, fr: "stage", en: "internship", pos: "noun" },
  { id: 1071, fr: "stagiaire", en: "intern", pos: "noun" },
  { id: 1072, fr: "agence", en: "agency", pos: "noun" },
  { id: 1073, fr: "bureau d’aide", en: "help desk", pos: "noun" },
  { id: 1074, fr: "se rendre", en: "to go", pos: "verb" },
  { id: 1075, fr: "attacher", en: "to attach", pos: "verb" },
  { id: 1076, fr: "coincer", en: "to jam", pos: "verb" },
  { id: 1077, fr: "effacer", en: "to erase", pos: "verb" },
  { id: 1078, fr: "sauvegarder", en: "to save", pos: "verb" },
  { id: 1079, fr: "télécharger", en: "to download", pos: "verb" },
  { id: 1080, fr: "actualiser", en: "to refresh", pos: "verb" },
  { id: 1081, fr: "réinitialiser", en: "to reset", pos: "verb" },
  { id: 1082, fr: "améliorer", en: "to improve", pos: "verb" },
  { id: 1083, fr: "développer", en: "to develop", pos: "verb" },
  { id: 1084, fr: "tester", en: "to test", pos: "verb" },
  { id: 1085, fr: "corriger", en: "to correct", pos: "verb" },
  { id: 1086, fr: "remarquer", en: "to notice", pos: "verb" },
  { id: 1087, fr: "observer", en: "to observe", pos: "verb" },
  { id: 1088, fr: "tourner", en: "to turn", pos: "verb" },
  { id: 1089, fr: "toucher", en: "to touch", pos: "verb" },
  { id: 1090, fr: "glisser", en: "to slide", pos: "verb" },
  { id: 1091, fr: "souffler", en: "to blow", pos: "verb" },
  { id: 1092, fr: "chauffer", en: "to heat", pos: "verb" },
  { id: 1093, fr: "refroidir", en: "to cool", pos: "verb" },
  { id: 1094, fr: "plier", en: "to fold", pos: "verb" },
  { id: 1095, fr: "déplier", en: "to unfold", pos: "verb" },
  { id: 1096, fr: "commencer à", en: "to begin to", pos: "verb" },
  { id: 1097, fr: "finir de", en: "to finish doing", pos: "verb" },
  { id: 1098, fr: "aider à", en: "to help to", pos: "verb" },
  { id: 1099, fr: "inviter à", en: "to invite to", pos: "verb" },
  { id: 1100, fr: "penser à", en: "to think about", pos: "verb" },
  { id: 1101, fr: "rêver de", en: "to dream of", pos: "verb" },
  { id: 1102, fr: "parler de", en: "to talk about", pos: "verb" },
  { id: 1103, fr: "se souvenir de", en: "to remember", pos: "verb" },
  { id: 1104, fr: "s’occuper de", en: "to take care of", pos: "verb" },
  { id: 1105, fr: "s’habituer à", en: "to get used to", pos: "verb" },
  { id: 1106, fr: "se dépêcher", en: "to hurry", pos: "verb" },
  { id: 1107, fr: "se promener", en: "to take a walk", pos: "verb" },
  { id: 1108, fr: "s’amuser", en: "to have fun", pos: "verb" },
  { id: 1109, fr: "se fâcher", en: "to get angry", pos: "verb" },
  { id: 1110, fr: "se tromper", en: "to make a mistake", pos: "verb" },
  { id: 1111, fr: "se débrouiller", en: "to manage", pos: "verb" },
  { id: 1112, fr: "s’inquiéter", en: "to worry", pos: "verb" },
  { id: 1113, fr: "se calmer", en: "to calm down", pos: "verb" },
  { id: 1114, fr: "simple", en: "simple", pos: "adj" },
  { id: 1115, fr: "compliqué", en: "complicated", pos: "adj" },
  { id: 1116, fr: "proche", en: "close (adj)", pos: "adj" },
  { id: 1117, fr: "lointain", en: "distant", pos: "adj" },
  { id: 1118, fr: "moderne", en: "modern", pos: "adj" },
  { id: 1119, fr: "ancien", en: "old/ancient", pos: "adj" },
  { id: 1120, fr: "plein", en: "full", pos: "adj" },
  { id: 1121, fr: "vide", en: "empty", pos: "adj" },
  { id: 1122, fr: "utile", en: "useful", pos: "adj" },
  { id: 1123, fr: "inutile", en: "useless", pos: "adj" },
  { id: 1124, fr: "célèbre", en: "famous", pos: "adj" },
  { id: 1125, fr: "important", en: "important", pos: "adj" },
  { id: 1126, fr: "principal", en: "main", pos: "adj" },
  { id: 1127, fr: "secondaire", en: "secondary", pos: "adj" },
  { id: 1128, fr: "rapide", en: "fast", pos: "adj" },
  { id: 1129, fr: "lent", en: "slow", pos: "adj" },
  { id: 1130, fr: "bruyant", en: "noisy", pos: "adj" },
  { id: 1131, fr: "silencieux", en: "quiet", pos: "adj" },
  { id: 1132, fr: "humain", en: "human", pos: "adj" },
  { id: 1133, fr: "animal", en: "animal", pos: "adj" },
  { id: 1134, fr: "national", en: "national", pos: "adj" },
  { id: 1135, fr: "local", en: "local", pos: "adj" },
  { id: 1136, fr: "particulièrement", en: "particularly", pos: "adv" },
  { id: 1137, fr: "principalement", en: "mainly", pos: "adv" },
  { id: 1138, fr: "exactement", en: "exactly", pos: "adv" },
  { id: 1139, fr: "précisément", en: "precisely", pos: "adv" },
  { id: 1140, fr: "rarement", en: "rarely", pos: "adv" },
  { id: 1141, fr: "soudainement", en: "suddenly", pos: "adv" },
  { id: 1142, fr: "facilement", en: "easily", pos: "adv" },
  { id: 1143, fr: "difficilement", en: "with difficulty", pos: "adv" },
  { id: 1144, fr: "volontiers", en: "willingly", pos: "adv" },
  { id: 1145, fr: "évidemment", en: "obviously", pos: "adv" },
  { id: 1146, fr: "certainement", en: "certainly", pos: "adv" },
  { id: 1147, fr: "probablement", en: "probably", pos: "adv" },
  { id: 1148, fr: "peut-être", en: "maybe", pos: "adv" },
  { id: 1149, fr: "actuellement", en: "currently", pos: "adv" },
  { id: 1150, fr: "bientôt", en: "soon", pos: "adv" },
  { id: 1151, fr: "longtemps", en: "for a long time", pos: "adv" },
  { id: 1152, fr: "quelquefois", en: "sometimes", pos: "adv" },
  { id: 1153, fr: "tôt", en: "early", pos: "adv" },
  { id: 1154, fr: "tard", en: "late", pos: "adv" },
  { id: 1155, fr: "selon", en: "according to", pos: "prep" },
  { id: 1156, fr: "grâce à", en: "thanks to", pos: "prep" },
  { id: 1157, fr: "malgré", en: "despite", pos: "prep" },
  { id: 1158, fr: "parmi", en: "among", pos: "prep" },
  { id: 1159, fr: "vers", en: "towards", pos: "prep" },
  { id: 1160, fr: "sans", en: "without", pos: "prep" },
  { id: 1161, fr: "avec", en: "with", pos: "prep" },
  { id: 1162, fr: "contre", en: "against", pos: "prep" },
  { id: 1163, fr: "près de", en: "near", pos: "prep" },
  { id: 1164, fr: "loin de", en: "far from", pos: "prep" },
  { id: 1201, fr: "animal domestique", en: "pet", pos: "noun" },
  { id: 1202, fr: "chenil", en: "kennel", pos: "noun" },
  { id: 1203, fr: "plante", en: "plant", pos: "noun" },
  { id: 1204, fr: "pot", en: "pot", pos: "noun" },
  { id: 1205, fr: "graine", en: "seed", pos: "noun" },
  { id: 1206, fr: "jardinage", en: "gardening", pos: "noun" },
  { id: 1207, fr: "outil", en: "tool", pos: "noun" },
  { id: 1208, fr: "marteau", en: "hammer", pos: "noun" },
  { id: 1209, fr: "tournevis", en: "screwdriver", pos: "noun" },
  { id: 1210, fr: "pince", en: "pliers", pos: "noun" },
  { id: 1211, fr: "vis", en: "screw", pos: "noun" },
  { id: 1212, fr: "clou", en: "nail", pos: "noun" },
  { id: 1213, fr: "bois", en: "wood", pos: "noun" },
  { id: 1214, fr: "métal", en: "metal", pos: "noun" },
  { id: 1215, fr: "verre", en: "glass material", pos: "noun" },
  { id: 1216, fr: "plastique", en: "plastic", pos: "noun" },
  { id: 1217, fr: "papier", en: "paper", pos: "noun" },
  { id: 1218, fr: "carton", en: "cardboard", pos: "noun" },
  { id: 1219, fr: "couteau de poche", en: "pocket knife", pos: "noun" },
  { id: 1220, fr: "thermos", en: "thermos", pos: "noun" },
  { id: 1221, fr: "bouteille d’eau", en: "water bottle", pos: "noun" },
  { id: 1222, fr: "gourde", en: "canteen", pos: "noun" },
  { id: 1223, fr: "sac de couchage", en: "sleeping bag", pos: "noun" },
  { id: 1224, fr: "tente", en: "tent", pos: "noun" },
  { id: 1225, fr: "lampe de poche", en: "flashlight", pos: "noun" },
  { id: 1226, fr: "boussole", en: "compass", pos: "noun" },
  { id: 1227, fr: "chemin", en: "path", pos: "noun" },
  { id: 1228, fr: "passage", en: "passage", pos: "noun" },
  { id: 1229, fr: "solitude", en: "loneliness", pos: "noun" },
  { id: 1230, fr: "compagnie", en: "company (presence)", pos: "noun" },
  { id: 1231, fr: "rassemblement", en: "gathering", pos: "noun" },
  { id: 1232, fr: "rencontre", en: "encounter", pos: "noun" },
  { id: 1233, fr: "discussion", en: "discussion", pos: "noun" },
  { id: 1234, fr: "débat", en: "debate", pos: "noun" },
  { id: 1235, fr: "accord", en: "agreement", pos: "noun" },
  { id: 1236, fr: "désaccord", en: "disagreement", pos: "noun" },
  { id: 1237, fr: "autorisation", en: "permission", pos: "noun" },
  { id: 1238, fr: "permission", en: "permission", pos: "noun" },
  { id: 1239, fr: "interdiction", en: "ban", pos: "noun" },
  { id: 1240, fr: "opinion", en: "opinion", pos: "noun" },
  { id: 1241, fr: "point de vue", en: "point of view", pos: "noun" },
  { id: 1242, fr: "suggestion", en: "suggestion", pos: "noun" },
  { id: 1243, fr: "conseil", en: "advice", pos: "noun" },
  { id: 1244, fr: "expérience", en: "experience", pos: "noun" },
  { id: 1245, fr: "tentative", en: "attempt", pos: "noun" },
  { id: 1246, fr: "habitude", en: "habit", pos: "noun" },
  { id: 1247, fr: "coutume", en: "custom", pos: "noun" },
  { id: 1248, fr: "tradition", en: "tradition", pos: "noun" },
  { id: 1249, fr: "fête nationale", en: "national holiday", pos: "noun" },
  { id: 1250, fr: "célébration", en: "celebration", pos: "noun" },
  { id: 1251, fr: "cérémonie", en: "ceremony", pos: "noun" },
  { id: 1252, fr: "invitation", en: "invitation", pos: "noun" },
  { id: 1253, fr: "remerciement", en: "thanks", pos: "noun" },
  { id: 1254, fr: "excuse", en: "apology", pos: "noun" },
  { id: 1255, fr: "promesse", en: "promise", pos: "noun" },
  { id: 1256, fr: "déclaration", en: "statement", pos: "noun" },
  { id: 1257, fr: "information", en: "information", pos: "noun" },
  { id: 1258, fr: "annonce", en: "announcement", pos: "noun" },
  { id: 1259, fr: "rituel", en: "ritual", pos: "noun" },
  { id: 1260, fr: "symbole", en: "symbol", pos: "noun" },
  { id: 1261, fr: "identité", en: "identity", pos: "noun" },
  { id: 1262, fr: "drapeau", en: "flag", pos: "noun" },
  { id: 1263, fr: "étranger", en: "foreigner", pos: "noun" },
  { id: 1264, fr: "étrangère", en: "foreign woman", pos: "noun" },
  { id: 1265, fr: "citoyen", en: "citizen", pos: "noun" },
  { id: 1266, fr: "communauté", en: "community", pos: "noun" },
  { id: 1267, fr: "réseau social", en: "social network", pos: "noun" },
  { id: 1268, fr: "abonné", en: "subscriber", pos: "noun" },
  { id: 1269, fr: "publication", en: "post", pos: "noun" },
  { id: 1270, fr: "commentaire", en: "comment", pos: "noun" },
  { id: 1271, fr: "réaction", en: "reaction", pos: "noun" },
  { id: 1272, fr: "partage", en: "share", pos: "noun" },
  { id: 1273, fr: "journal intime", en: "diary", pos: "noun" },
  { id: 1274, fr: "récit", en: "narrative", pos: "noun" },
  { id: 1275, fr: "poème", en: "poem", pos: "noun" },
  { id: 1276, fr: "auteur", en: "author", pos: "noun" },
  { id: 1277, fr: "éditeur", en: "editor", pos: "noun" },
  { id: 1278, fr: "bibliothèque", en: "library", pos: "noun" },
  { id: 1279, fr: "emprunt", en: "borrowing", pos: "noun" },
  { id: 1280, fr: "retour", en: "return (library)", pos: "noun" },
  { id: 1281, fr: "collection", en: "collection", pos: "noun" },
  { id: 1282, fr: "archive", en: "archive", pos: "noun" },
  { id: 1283, fr: "contenu", en: "content", pos: "noun" },
  { id: 1284, fr: "version", en: "version", pos: "noun" },
  { id: 1285, fr: "original", en: "original", pos: "noun" },
  { id: 1286, fr: "copie", en: "copy", pos: "noun" },
  { id: 1287, fr: "résumé", en: "summary", pos: "noun" },
  { id: 1288, fr: "détail", en: "detail", pos: "noun" },
  { id: 1289, fr: "campagne", en: "campaign", pos: "noun" },
  { id: 1290, fr: "protection", en: "protection", pos: "noun" },
  { id: 1291, fr: "recherche", en: "research", pos: "noun" },
  { id: 1292, fr: "étude", en: "study", pos: "noun" },
  { id: 1293, fr: "science", en: "science", pos: "noun" },
  { id: 1294, fr: "expérience scientifique", en: "experiment", pos: "noun" },
  { id: 1295, fr: "mesure", en: "measurement", pos: "noun" },
  { id: 1296, fr: "analyse", en: "analysis", pos: "noun" },
  { id: 1297, fr: "résultat", en: "result", pos: "noun" },
  { id: 1298, fr: "donnée", en: "data", pos: "noun" },
  { id: 1299, fr: "robot", en: "robot", pos: "noun" },
  { id: 1300, fr: "machine", en: "machine", pos: "noun" },
  { id: 1301, fr: "moteur", en: "engine", pos: "noun" },
  { id: 1302, fr: "câble", en: "cable", pos: "noun" },
  { id: 1303, fr: "interrupteur", en: "switch", pos: "noun" },
  { id: 1304, fr: "bouton", en: "button", pos: "noun" },
  { id: 1305, fr: "signal", en: "signal", pos: "noun" },
  { id: 1306, fr: "bruit", en: "noise", pos: "noun" },
  { id: 1307, fr: "volume", en: "volume", pos: "noun" },
  { id: 1308, fr: "ton", en: "tone", pos: "noun" },
  { id: 1309, fr: "rythme", en: "rhythm", pos: "noun" },
  { id: 1310, fr: "mélodie", en: "melody", pos: "noun" },
  { id: 1311, fr: "public", en: "audience", pos: "noun" },
  { id: 1312, fr: "spectateur", en: "viewer", pos: "noun" },
  { id: 1313, fr: "danseur", en: "dancer", pos: "noun" },
  { id: 1314, fr: "acteur", en: "actor", pos: "noun" },
  { id: 1315, fr: "actrice", en: "actress", pos: "noun" },
  { id: 1316, fr: "dessinateur", en: "illustrator", pos: "noun" },
  { id: 1317, fr: "peintre", en: "painter", pos: "noun" },
  { id: 1318, fr: "musicien", en: "musician", pos: "noun" },
  { id: 1319, fr: "artiste", en: "artist", pos: "noun" },
  { id: 1320, fr: "sculpteur", en: "sculptor", pos: "noun" },
  { id: 1321, fr: "galerie", en: "gallery", pos: "noun" },
  { id: 1322, fr: "exposition", en: "exhibition", pos: "noun" },
  { id: 1323, fr: "studio", en: "studio", pos: "noun" },
  { id: 1324, fr: "tournage", en: "filming", pos: "noun" },
  { id: 1325, fr: "scène", en: "stage", pos: "noun" },
  { id: 1326, fr: "décor", en: "set", pos: "noun" },
  { id: 1327, fr: "costume", en: "costume", pos: "noun" },
  { id: 1328, fr: "lumière", en: "lighting", pos: "noun" },
  { id: 1329, fr: "performance", en: "performance", pos: "noun" },
  { id: 1330, fr: "applaudissement", en: "applause", pos: "noun" },
  { id: 1331, fr: "courageux", en: "brave", pos: "adj" },
  { id: 1332, fr: "timide", en: "shy", pos: "adj" },
  { id: 1333, fr: "créatif", en: "creative", pos: "adj" },
  { id: 1334, fr: "prudent", en: "careful", pos: "adj" },
  { id: 1335, fr: "dangereux", en: "dangerous", pos: "adj" },
  { id: 1336, fr: "fiable", en: "reliable", pos: "adj" },
  { id: 1337, fr: "incroyable", en: "incredible", pos: "adj" },
  { id: 1338, fr: "fantastique", en: "fantastic", pos: "adj" },
  { id: 1339, fr: "quotidien", en: "daily", pos: "adj" },
  { id: 1340, fr: "mensuel", en: "monthly", pos: "adj" },
  { id: 1341, fr: "annuel", en: "yearly", pos: "adj" },
  { id: 1342, fr: "professionnel", en: "professional", pos: "adj" },
  { id: 1343, fr: "personnel", en: "personal", pos: "adj" },
  { id: 1344, fr: "spécial", en: "special", pos: "adj" },
  { id: 1345, fr: "propre", en: "clean", pos: "adj" },
  { id: 1346, fr: "sale", en: "dirty", pos: "adj" },
  { id: 1347, fr: "fragile", en: "fragile", pos: "adj" },
  { id: 1348, fr: "solide", en: "solid", pos: "adj" },
  { id: 1349, fr: "bas", en: "low", pos: "adj" },
  { id: 1350, fr: "haut", en: "high", pos: "adj" },
  { id: 1351, fr: "étroit", en: "narrow", pos: "adj" },
  { id: 1352, fr: "large", en: "wide", pos: "adj" },
  { id: 1353, fr: "profond", en: "deep", pos: "adj" },
  { id: 1354, fr: "vide", en: "empty", pos: "adj" },
  { id: 1355, fr: "plein", en: "full", pos: "adj" },
  { id: 1356, fr: "ancien", en: "old", pos: "adj" },
  { id: 1357, fr: "récent", en: "recent", pos: "adj" },
  { id: 1358, fr: "bref", en: "brief", pos: "adj" },
  { id: 1359, fr: "lentement", en: "slowly", pos: "adv" },
  { id: 1360, fr: "rapidement", en: "quickly", pos: "adv" },
  { id: 1361, fr: "exactement", en: "exactly", pos: "adv" },
  { id: 1362, fr: "simplement", en: "simply", pos: "adv" },
  { id: 1363, fr: "clairement", en: "clearly", pos: "adv" },
  { id: 1364, fr: "heureusement", en: "fortunately", pos: "adv" },
  { id: 1365, fr: "malheureusement", en: "unfortunately", pos: "adv" },
  { id: 1366, fr: "probablement", en: "probably", pos: "adv" },
  { id: 1367, fr: "sûrement", en: "surely", pos: "adv" },
  { id: 1368, fr: "presque", en: "almost", pos: "adv" },
  { id: 1369, fr: "partout", en: "everywhere", pos: "adv" },
  { id: 1370, fr: "nulle part", en: "nowhere", pos: "adv" },
  { id: 1371, fr: "ensemble", en: "together", pos: "adv" },
  { id: 1372, fr: "loin", en: "far", pos: "adv" },
  { id: 1373, fr: "près", en: "close", pos: "adv" },
  { id: 1374, fr: "à travers", en: "through", pos: "prep" },
  { id: 1375, fr: "par rapport à", en: "compared to", pos: "prep" },
  { id: 1376, fr: "selon", en: "according to", pos: "prep" },
  { id: 1377, fr: "malgré", en: "despite", pos: "prep" },
  { id: 1378, fr: "sauf", en: "except", pos: "prep" },
  { id: 1379, fr: "durant", en: "during", pos: "prep" },
  { id: 1380, fr: "auprès de", en: "near/by", pos: "prep" },
  { id: 1381, fr: "parmi", en: "among", pos: "prep" },
];